### ISSUE TITLE
Error while building through Cocoapods

### ISSUE THREAD

**Issue by nightflier** [BlinkID/blinkid-ios#100]
Hi,

as already pointed (and resolved) by other users I'm currently unable to build my project.
During the linking phase I receive the following error `... Pods/PPBlinkOCR/MicroBlink.framework/MicroBlink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64) ...`

I have already tried to delete the Cocoapods master repo, install git-lfs via brew, reboot my macbook and perform a new `pod update` but however the project is still broken.
My currently configuration is:

- Xcode 8.3.3

- Cocoapods 1.3.0

- git-lfs/2.2.1 

Could you please help me?

Thanks,
Matteo

**Comment by cularj** [comment]
Hi @nightflier,

did you try getting the framework using Cocoapods before installing git-lfs?
If you did you should try git lfs pull. 
Please report back if this solved your issue.

Regards,
Jure
