### ISSUE TITLE
Update Recognizer Settings without dismissing the controller

### ISSUE THREAD

**Issue by manomuthu-optisol** [BlinkID/blinkid-ios#102]
Hi,

i have been using blink id default view controller for scanning with MRTD , USDL and EUDL RecognizerSettings there was no issues in using that. But while include the face detection setting with that am getting an error as no privilege available . How to use face detection setting along with MRTD , USDL and EUDL RecognizerSettings. Kindly, give me an idea

Thanks in advance.

Regards,
M.Muthukumar

**Comment by cularj** [comment]
HI @manomuthu-optisol!

If you are updating settings while scanning, make sure to call [coordiantor applySettings] after you update them.  You should create face detector like this:
```
PPFaceDetectorSettings *faceDetectorSettings = [[PPFaceDetectorSettings alloc] init];
PPDetectorRecognizerSettings *detectorRecognizerSetting = [[PPDetectorRecognizerSettings alloc] initWithDetectorSettings:faceDetectorSettings]; 
[settings.scanSettings addRecognizerSettings:detectorRecognizerSetting];

// If you are doing this after presenting scanningViewController add this line: 
[coordinator applySettings];
```
Could you send us the code you use to create and add recognisers?

Regards,
Jure

**Comment by manomuthu-optisol** [comment]
Hi Jure,

Kindly find the below file in which i have my code which am using.


[scanCode.txt](https://github.com/BlinkID/blinkid-ios/files/1211557/scanCode.txt)

**Comment by cularj** [comment]
Hi @manomuthu-optisol,

I went through your code and recreated the error you are getting. I noticed you have a docScanner function in which you create PPDetectorRecgonizerSettings so if you create PPFaceDetectorSettings and add another PPDetectorRecognizerSettings you will get this error. If you look into PPDetectorRecognizerSettings, you will see that the documentation says to create [PPMultiDetectorSettings](http://cocoadocs.org/docsets/PPBlinkID/2.11.0/Classes/PPMultiDetectorSettings.html) if you have [multiple detectors](http://cocoadocs.org/docsets/PPBlinkID/2.11.0/Classes/PPDetectorRecognizerSettings.html), which you have. I can see you created PPMultiDetectorSettings, but you didn't add it to your PPDetectorRecognizerSettings. So if you want to have multiple detector setting at once you should add them all to your PPMultiDetectorSettings. I made a short example from your docScanner function:

```
// MULTI detector
let faceDetectorSettings = PPFaceDetectorSettings()

let multiDetectorSettings = PPMultiDetectorSettings.init(settingsArray: [documentDetectorSettings,mrtdDetectorSettings,faceDetectorSettings])

multiDetectorSettings?.allowMultipleResults = true

// Detector recognizer

let detectorRecognizerSettings = PPDetectorRecognizerSettings.init(detectorSettings: multiDetectorSettings!)
```
So make sure that you have max one PPDetectorRecognizerSettings in your PPSettings, if you need more detectors simultaneously create PPMultiDetectorSettings and add that to your PPDetectorRecognizerSettings.
If you need a separate face detector recognizer, see [PPDocumentFaceRecognizerSettings](http://cocoadocs.org/docsets/PPBlinkID/2.11.0/Classes/PPDocumentFaceRecognizerSettings.html).
Please let us know if this helps.

Kind regards,
Jure

**Comment by manomuthu-optisol** [comment]
Hi jure,

Thanks for your help. Will implement the scenario which you have given and revert back to you as soon as possible.

Thanks and regards,
M.Muthukumar

**Comment by manomuthu-optisol** [comment]
Hi jure,

Thanks a lot. PPDocumentFaceRecognizerSettings have done the trick which i have expected.

Regards,
M.Muthukumar
