### ISSUE TITLE
ID Combined Recognition like Android

### ISSUE THREAD

**Issue by anaroda** [BlinkID/blinkid-ios#103]
Hi,
is it possible to use combined recognition e.g. PPSlovakIDCombinedRecognizerSettings same way as in the Android version? To be informed when recognition of the front side is done to make appropriate changes in the UI to notify the user to flip document and scan back side?

**Comment by Cerovec** [comment]
It's possible.

You need to have custom UI integration (documentation [here](https://github.com/BlinkID/blinkid-ios/wiki/Customizing-Camera-UI)).

Then your custom overlay view controller will get a notification when the first side of the ID is recognized. Callback [`cameraViewController:didFinishRecognitionFirstSide:`](https://github.com/BlinkID/blinkid-ios/blob/master/MicroBlink.framework/Headers/PPOverlayViewController.h#L251) is called on that event.

**Comment by anaroda** [comment]
Thank you, I'll try it this way.

**Comment by anaroda** [comment]
Hi @Cerovec, now I get notification (callback `cameraViewController:didFinishRecognitionFirstSide:`) when the first (front) side of ID is recognized, but is it possible to get notification when user start with back side instead?

**Comment by Cerovec** [comment]
Hi @anaroda - that's the same notification. 

Internally, we set up the recognition for front side, and immediately, when the front side is scanned, we dispatch an event `cameraViewController:didFinishRecognitionFirstSide`, and setup and start scanning back side.

Is there a reason why you cannot use this notification in the way you would like?

**Comment by anaroda** [comment]
Hi @Cerovec,
Thank you. For better control on scanning flow I decided to use separate `PPSlovakIDFrontRecognizerSettings` and `PPSlovakIDBackRecognizerSettings`.
