### ISSUE TITLE
Undefined Symbols on Architecture armv7

### ISSUE THREAD

**Issue by Indox** [BlinkID/blinkid-ios#104]
Undefined symbols for architecture armv7:
  "_cblas_sgemm", referenced from:
      l6245 in MicroBlink(MicroBlink-armv7-master.o)
  "_iconv_open", referenced from:
      l1443 in MicroBlink(MicroBlink-armv7-master.o)
      l1515 in MicroBlink(MicroBlink-armv7-master.o)
  "_iconv", referenced from:
      l1443 in MicroBlink(MicroBlink-armv7-master.o)
      l1515 in MicroBlink(MicroBlink-armv7-master.o)
  "_iconv_close", referenced from:
      l1443 in MicroBlink(MicroBlink-armv7-master.o)
      l1515 in MicroBlink(MicroBlink-armv7-master.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by DoDoENT** [comment]
Make sure you link your app with iconv and Accelerate frameworks.

**Comment by Cerovec** [comment]
@Indox - please let us know if our advice helped.
