### ISSUE TITLE
Fail to get the metadata from Malaysia iKad. 

### ISSUE THREAD

**Issue by RexNexstream** [BlinkID/blinkid-ios#105]
I Initial the setting with the code below:

```
 override func coordinator(_ settings: PPSettings) -> PPCameraCoordinator? {
        let recognizerSettings = PPiKadRecognizerSettings()
        recognizerSettings.displayFullDocumentImage = true
        settings.scanSettings.add(recognizerSettings)
        settings.metadataSettings.dewarpedImage = true;
        let coordinator = PPCameraCoordinator(settings: settings, delegate: nil)
        return coordinator
  }
```

However, I m not able get the PPMetadata from didOutputMetadata and this warning appear :

**Cannot find parser group for location 'MalaysianiKad.FullDocument'. Will not perform OCR and parsing of that location!**

Please advise on this. Thank you

**Comment by cularj** [comment]
Hi @RexNexstream

You can ignore the warning this is normal behaviour.
I modified our sample app and tried to scan Malaysia iKad using our latest SDK and I'm able to get the image in didOutputMetadata. 
You can check the [source of ViewController](https://gist.github.com/cularj/9b45d94ab789902394caf0cba50bda7b) I modified, and try it out in our [BlinkID-sample-swift](https://github.com/BlinkID/blinkid-ios/tree/master/Samples/BlinkID-sample-Swift) app.

Kind regards,
Jure

**Comment by RexNexstream** [comment]
It work now. Thank You
