### ISSUE TITLE
new zealand driver license

### ISSUE THREAD

**Issue by mvayngrib** [BlinkID/blinkid-ios#107]
awesome job guys! Is the New Zealand driver license planned?

**Comment by Cerovec** [comment]
Hi,

thanks! :)

New Zealand has two types of DLs. One is very similar to EU DLs (for which we already have support), and the other is also solvable with our OCR and templating API. However, New Zealand is not currently on our list of countries to support in short-term.

I suggest you contact our sales team on sales@microblink.com.

Best,
Jurica.

**Comment by imizaac** [comment]
Hey mvayngrib. 

If you can get me a photo of a newzealand drivers license I'll hack together an example of how to use the templating API to do this in swift.

**Comment by culoi** [comment]
New Zealand DL is added as the recognizers in version 2.16 of the BlinkID-iOS: https://github.com/BlinkID/blinkid-ios/blob/master/Release%20notes.md#2160
