### ISSUE TITLE
Example app. didOutputResults is never called

### ISSUE THREAD

**Issue by johnrufusj** [BlinkID/blinkid-ios#11]
I just loaded up the example app and the delegate method didOutputResults seems to never be called.  there is no error generated either.  The app runs fine and launches the scanningViewController, but then nothing. Running Xcode 7.1 - iOS 9.1 on the iPhone.

**Comment by Cerovec** [comment]
Is it possible that didOutputResults wasn't called because there are actually no results?
Which document types are you scanning?
Which RecognizerSettings are you setting in your initialization stage?

Thanks,
BlinkID team.

**Comment by johnrufusj** [comment]
I was able to try it on a different device today and it is working as expected. Not sure what is going on with the other device.  I am using PPUsdlRecognizerSettings. Thanks for the response, but it is working as expected.

**Comment by Cerovec** [comment]
Excellent. Let us know if you need any other help!
