### ISSUE TITLE
Passport Custom Scan page size

### ISSUE THREAD

**Issue by nrvraghu** [BlinkID/blinkid-ios#110]
Hi, BlinkID Team
   I am looking out for custom size for passport scan view size will be with width 300 and height 200 like this. Is this will support swift code?

**Comment by imizaac** [comment]
Hey nrvraghu, 

I am not a part of the BlinkID team, but I can tell you that this can be done easily within BlinkId. All you have to do is learn how to use the templating API. I recommend following the sample included in the bundle. 

Unfortunately the documentation is not where it could be for swift in this area, so you will have to translate from Objective-C to swift manually. This may be intimidating, but I can tell you it isn't as hard as you might think. All the names of classes are the same, so you just have to learn the declaration syntax. I'd suggest just giving it a try and using the included sample projects. I was able to do it from the templating sample in Objective-C and an example in swift to get the framework. The Objective-C documentation was helpful, but once again, required translating.
