### ISSUE TITLE
h

### ISSUE THREAD

**Issue by emadabusadq** [BlinkID/blinkid-ios#112]
I have create BlinkID demo license key

but how and where can insert it in the project ?

**Comment by cularj** [comment]
Hi @emadabusadq ,

To set your license key you need to create an instance of PPSettings and set its licenseKey property to your license:

```
PPSettings *settings = [[PPSettings alloc] init];
settings.licenseSettings.licenseKey = @"<your license key here>";
```

After that you setup the recognisers you want to use and other settings you wish to set, for instructions with examples check out our [guide](https://github.com/BlinkID/blinkid-ios/wiki/Getting-started#3-initiating-the-scanning-process) on how to get started.

Kind regards,
Jure

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
