### ISSUE TITLE
USDL no field for Issuing Jurisdiction Name

### ISSUE THREAD

**Issue by webwizgordon** [BlinkID/blinkid-ios#114]
The [Android SDK](https://github.com/BlinkID/blinkid-android/blob/master/DriversLicenseKeys.md) has the field `USDLScanResult.kIssuingJurisdictionName` but the iOS SDK has no equivalent `kPPIssuingJurisdictionName` key for USDL results.

**Comment by cularj** [comment]
Hi @webwizgordon ,

thank you for reporting this, we will add `kPPIssuingJurisdictionName` key in the future release.

Kind regards,
Jure

**Comment by sdwornik** [comment]
+1
