### ISSUE TITLE
"Position ID in the frame"

### ISSUE THREAD

**Issue by iswathi** [BlinkID/blinkid-ios#119]
How to remove the text "Position ID in the frame" on camera view in swift.  I have given the following lines : 
        let removeText : PPIDCardOverlayViewController = PPIDCardOverlayViewController()
        removeText.idCardSubview.tooltipLabel.isHidden = true
This throws an exception "Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value"

**Comment by juraskrlec** [comment]
Hi @iswathi 
this tooltip is part of PPIdCardOverlaySubview. You will need to create custom overlay view controller as a subclass of PPIDCardOverlayViewController and in viewDidLoad method set your text: 

self.idCardSubview.tooltipLabel.text = @"Example".

After that, scanningViewController is initialised like this:

    OverlayViewController *ovc = [[OverlayViewController alloc] init];    

    /** Create new scanning view controller */
    UIViewController<PPScanningViewController> *scanningViewController =
        [PPViewControllerFactory cameraViewControllerWithDelegate:self overlayViewController:ovc coordinator:coordinator error:nil];

Best,
Jura

**Comment by madhuchprimekeeper** [comment]
Hi jura
We are using blinkOcr version 2.3.0 and my code in SWIF i want remove "Position ID in the frame" on camera view and  I have given the following lines in my code:

let removeText : PPIDCardOverlayViewController = PPIDCardOverlayViewController()
removeText.idCardSubview.tooltipLabel.isHidden = true

This throws an exception "Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value"

Please help me to fix this issue as early as possible.

**Comment by juraskrlec** [comment]
Hi @madhuchprimekeeper 

as I said in previous post, you need to create your own view controller which is subclass of  PPIDCardOverlayViewController. 

`class CustomOverlayController : PPIDCardOverlayViewController `

in viewDidLoad method you can access toolTip as: `self.idCardSubview.tooltipLabel`. You need to initialise that CustomOverlayController and send it to PPViewControllerFactory.

Best,
Jura

**Comment by madhuchprimekeeper** [comment]
Hi Jura


Thanks for your help i fixed my bug.

________________________________
