### ISSUE TITLE
(Question) It's posible to use the PPSanningDelegate outside the active view?

### ISSUE THREAD

**Issue by spunj** [BlinkID/blinkid-ios#120]
So pretty much what the question says, im triying to do something like this:

`let scanningViewController = PPViewControllerFactory.cameraViewController(with: dummyController, coordinator: coordinator!, error: nil)`

where "dummyController" is an UIViewController that is not the active one.
When I do this, i get the scanning process started but the delegates never fire.
So is this even possible? Am I doing something wrong?
Thanks in advance.

**Comment by Pickles112358** [comment]
Hi @spunj 

Is it possible that your dummyController is nil or initialized? Our PPScanningDelegate can be any object including UIViewController that is not an active one. Could you share the source code of your implementation?

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
