### ISSUE TITLE
License key validation as public method

### ISSUE THREAD

**Issue by grzegorzmakowski** [BlinkID/blinkid-ios#121]
Hello,
I notice from log that you have private method to check license key. Is there some possibility to make this method public? Because for now I make workaround (I am creating coordinator and invoke method processImage on some small image. When license is ok we get notified with method didFinishDetectionWithResult that image is to small, when license key is invalid I get notified by delegate with method invalidLicenseKeyWithError :) ) The reason why we need this is that we want know about wrong license key BEFORE start scanning on real image/document. When I am not checking license key like above PPScanningViewController is opening but we get alertView with some information. We want to prevent this situation when license key will expire on production and skip scanning flow.
I know that you add warning for time limited license keys in last version but we would like more public method to check license :)

**Comment by DoDoENT** [comment]
Hello!

Unfortunately with current API this is not possible. The reason for this is that license validation is done lazy at the time of instantiation of specific recognizer (to validate that specific recognizer is allowed by license key), which is done lazily at the time first image is being processed.

The new API that we are currently developing will not have this issue.

**Comment by grzegorzmakowski** [comment]
ok, thanks for response, can you tell when new API will be available, maybe in new version 2.14.0 or later? (how many month or versions) :)

**Comment by Shafichariri** [comment]
Is this API available now? [I couldn't find it]

**Comment by coldmachine** [comment]
I can't find it either. Would be helpful if such method existed.

**Comment by DoDoENT** [comment]
You can use `MBMicroblinkSDK.sharedInstance().setLicenseKey('key')` as documented [here](https://github.com/BlinkID/blinkid-ios#4-license-key) and [here](http://blinkid.github.io/blinkid-ios/Classes/MBMicroblinkSDK.html#/c:objc(cs)MBMicroblinkSDK(im)setLicenseKey:).

The method will throw an exception in case of using invalid license key.
