### ISSUE TITLE
Unable to submit with embedded framework

### ISSUE THREAD

**Issue by benaneesh** [BlinkID/blinkid-ios#123]
Followed the [Integration without CocoaPods](https://github.com/BlinkID/blinkid-ios/wiki/Getting-started#integration-without-cocoapods) steps, and the framework works as intended in the app. But when we try to submit to the AppStore, this error is thrown:

![image](https://user-images.githubusercontent.com/1724896/32923665-a31dec2e-caed-11e7-9f36-e6ee10afdaf2.png)

**Comment by juraskrlec** [comment]
Hi @benaneesh 

Here in [Transition guide](https://github.com/BlinkID/blinkid-ios/wiki/Transition-guide#290), it says: Microblink.framework is a dynamic framework which contains slices for all architectures - device and simulator. If you intend to extract .ipa file for ad hoc distribution, you'll need to preprocess the framework to remove simulator architectures. So follow please instructions in [Transition guide](https://github.com/BlinkID/blinkid-ios/wiki/Transition-guide#290). 

Best, 
Jura
