### ISSUE TITLE
Can I get the ID card image? Not the result, just ID card image!!!

### ISSUE THREAD

**Issue by MobileDev112075** [BlinkID/blinkid-ios#125]
Hi

Can I get the ID card image? Not the result, just ID card image!!!

Help me, please

**Comment by juraskrlec** [comment]
Hi @MobileDev112075 

Yes you can, images are returned in `didOutputMetadata ` of PPScanningDelegate. On BlinkID Recognizer Settings, there is an option `displayFullDocumentImage`. Set that to `true` and you will get image. If you want to get image with Document Detector and adjusting yourself parameters you can follow this [tutorial](https://github.com/BlinkID/blinkid-ios/wiki/Using-Detector-recognizer)

Best
Jura

**Comment by MobileDev112075** [comment]
Hi @juraskrlec 

Thanks for your kind explanation, but I can't follow your guidance. Could you share some code for this part?

Best
Michael

**Comment by MobileDev112075** [comment]
Hi @juraskrlec 

error: memory read failed for 0x0
This is what I see when the camera starts detection.
What should I do now?
Help me, please.

Thanks
Michael

**Comment by juraskrlec** [comment]
Hi @MobileDev112075 

Here is example for PPGermanIDFrontRecognizer (Swift 4, that is straight up from our BlinkID-Sample-Swift; also do not forget to put your license key):

Frist create Coordinator:
`func coordinatorWithError(error: NSErrorPointer) -> PPCameraCoordinator? {

        /** 0. Check if scanning is supported */

        if (PPCameraCoordinator.isScanningUnsupported(for: PPCameraType.back, error: error)) {
            return nil;
        }


        /** 1. Initialize the Scanning settings */

         // Initialize the scanner settings object. This initialize settings with all default values.
        let settings: PPSettings = PPSettings()


        /** 2. Setup the license key */

        // Visit www.microblink.com to get the license key for your app
        settings.licenseSettings.licenseKey = "licenseKey"


        /**
        * 3. Set up what is being scanned. See detailed guides for specific use cases.
        * Remove undesired recognizers (added below) for optimal performance.
        */

        do {
            let germanIDFrontSettings = PPGermanIDFrontRecognizerSettings()
            
            germanIDFrontSettings.displayFullDocumentImage = true
            
            settings.scanSettings.add(germanIDFrontSettings)
        }

        // DISABLE this if you don't need to store images to improve performance!
        settings.metadataSettings.dewarpedImage = true

        /** 4. Initialize the Scanning Coordinator object */

        let coordinator: PPCameraCoordinator = PPCameraCoordinator(settings: settings, delegate: nil)

        return coordinator
    }`

Second, on button scan tap do something like this:
`    @IBAction func didTapScan(_ sender: AnyObject) {

        /** Instantiate the scanning coordinator */
        let error: NSErrorPointer = nil
        let coordinator = self.coordinatorWithError(error: error)

        /** If scanning isn't supported, present an error */
        if coordinator == nil {
            let messageString: String = (error!.pointee?.localizedDescription) ?? ""
            UIAlertView(title: "Warning", message: messageString, delegate: nil, cancelButtonTitle: "Ok").show()
            return
        }

        /** Allocate and present the scanning view controller */
        let scanningViewController: UIViewController & PPScanningViewController = PPViewControllerFactory.cameraViewController(with: self, coordinator: coordinator!, error: nil)

        scanningViewController.autorotate = true
        scanningViewController.supportedOrientations = UIInterfaceOrientationMask.all

        /** You can use other presentation methods as well */
        self.present(scanningViewController, animated: true, completion: nil)
    }`

After that implement PPScanningDelegate:
`   func scanningViewControllerDidClose(_ scanningViewController: UIViewController & PPScanningViewController) {
        // As scanning view controller is presented full screen and modally, dismiss it
        self.dismiss(animated: true, completion: nil)
    }
    
    func scanningViewController(_ scanningViewController: (UIViewController & PPScanningViewController)?, didOutputResults results: [PPRecognizerResult]) {

        guard results.count > 0 else {
            return
        }

        guard let scanningViewController = scanningViewController else {
            return
        }

        /**
         * Here you process scanning results. Scanning results are given in the array of PPRecognizerResult objects.
         * Each member of results array will represent one result for a single processed image
         * Usually there will be only one result. Multiple results are possible when there are 2 or more detected objects on a single image (i.e. pdf417 and QR code side by side)
         */

        // first, pause scanning until we process all the results
        scanningViewController.pauseScanning()

        var message = ""
        var title = ""

        // Collect data from the result
        for result in results {

            title = "Scan result"
            message = result.description
            
            if (result is PPGermanIDFrontRecognizerResult) {
                // do something with result
            }
        }

        // present the alert view with scanned results
        
        let alertController: UIAlertController = UIAlertController.init(title: title, message: message, preferredStyle: UIAlertControllerStyle.alert)
        
        let okAction: UIAlertAction = UIAlertAction.init(title: "OK", style: UIAlertActionStyle.default,
                                                         handler: { (action) -> Void in
                                                            self.dismiss(animated: true, completion: nil)
        })

        alertController.addAction(okAction)
        scanningViewController.present(alertController, animated: true, completion: nil)
    }

    func scanningViewController(_ scanningViewController: (UIViewController & PPScanningViewController)?, didOutputMetadata metadata: PPMetadata) {
        
        if (metadata is PPImageMetadata) {

            let result: PPImageMetadata = metadata as! PPImageMetadata

            let image: UIImage = result.image()

            print("result \(image)")

            if (result.name == PPMyKadRecognizerSettings.full_DOCUMENT_IMAGE()) {
                print("This image is EUDL full document");
            } 
        }
    }
`
Best,
Jura

**Comment by MobileDev112075** [comment]
Hi, @juraskrlec 

Thanks for your kind explanation. Can I get the image of ID card in this way?
I just get scanning results now. Am I doing right?

Regards
Michael

**Comment by juraskrlec** [comment]
Hi @MobileDev112075 

yes you can. Previous post's code has `didOutputMetadata ` implementation. You are getting image there.

Best regards,
Jura

**Comment by MobileDev112075** [comment]
Hi @juraskrlec 

Thanks again. Unfortunately, it still doesn't work.
if (metadata is PPImageMetadata) {}
This if statement does not work. Did I do something wrong?
Help me, please.

Regards
Michael

**Comment by MobileDev112075** [comment]
Can I stop the scanning once the ID card is detected?

**Comment by juraskrlec** [comment]
Hi @MobileDev112075 

yes you can, on scanningViewController there is a method pauseScanning

Best, 
Jura

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
