### ISSUE TITLE
Image quality with UsdlCombinedRecognizer

### ISSUE THREAD

**Issue by kryzhikh** [BlinkID/blinkid-ios#127]
Hi guys!

I'm using UsdlCombinedRecognizer. It scans the license front side and then switches to back side scanning (the barcode). The scanning itself works awesome, but the image quality of the front side in most times is rather low. It calls scanningViewController(_, didOutputMetadata) just once and I can't make it redo the front side scanning in this scan session, or choose the sample when the frameQuality is enough. That'd be cool if we had some setting like 'minimumFrameQuality' so that it will return image metadata only when the frame quality >= minimum. Or maybe there is something else how I can influence the image quality?

**Comment by ninjudd** [comment]
Is there a workaround for this? It seems that the scanning happens too early sometimes, before the user has finished moving their license to the center of the camera frame.

**Comment by kryzhikh** [comment]
I ended up using 2 recognizers - Detector recognizer with id1Card specification for the front side and usdl recognizer for the back side to scan the barcode. With detector recognizer you're able to filter low quality samples with PPImageMetadata frameQuality() method

**Comment by Pickles112358** [comment]
HI @kryzhikh and @ninjudd 

Can you please check which version you are using? v2.13.0. Improved the quality of images returned by PPUsdlCombinedRecognizer. Your solution should also work as it allows frame quality check, however be aware that frame quality drops on images with poor lightning so we suggest testing it in poorer conditions.

**Comment by kryzhikh** [comment]
Hi @Pickles112358 
We're using 2.14.0 and PPUsdlCombinedRecognizer still gives low image quality. Basically, as far as I can see, it just takes a photo as soon as it gets the DL edges and that's it. In most cases the image is not well focused (blurry)

**Comment by culoi** [comment]
Hello @kryzhikh 

You can check out this property: numStableDetectionsThreshold 
It sets the number of subsequent close detections must occur before treating document detection as stable. The default is 1. Larger number guarantees more robust document detection at price of slower performance.
https://github.com/BlinkID/blinkid-ios/wiki/Using-Detector-recognizer#initializing-ppdetectorsettings

Regards

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
