### ISSUE TITLE
app is crashing when scan button tapped 

### ISSUE THREAD

**Issue by puvvadakalyani** [BlinkID/blinkid-ios#129]
Hi Guys, 
my application is crashing when i tap on scan button. please find the below screenshot of code snippet and error.
**Error: Could not cast value of type 'BlinkID.ViewController' to 'PPScanningDelegate'.**
![screen shot 2017-12-13 at 4 18 08 pm](https://user-images.githubusercontent.com/34508516/33936207-cc627234-e024-11e7-841a-9812316cfdfb.png)
Can any one help on that error?

**Comment by culoi** [comment]
@puvvadakalyani 

PPScanningDelegate is a protocol where self is ViewController. You cannot convert protocol to viewController. 

You need to initialize view controller (your scanningViewController) that conforms to PPScanningViewController like this:
``` let scanningViewController: UIViewController & PPScanningViewController = PPViewControllerFactory.cameraViewController(with: self, coordinator: coordinator!, error: nil)```

Regards,

Ivan

**Comment by puvvadakalyani** [comment]
even if i write the code like this

let scanningViewController: UIViewController & PPScanningViewController = PPViewControllerFactory.cameraViewController(with: self, coordinator: coordinator!, error: nil)

I am getting an error like this

![screen shot 2017-12-13 at 4 55 23 pm](https://user-images.githubusercontent.com/34508516/33936836-f624bf3a-e026-11e7-9137-8bf353ab563c.png)


Actually first I wrote like below which was taken from github doc. but this one also shows an error

![screen shot 2017-12-13 at 5 01 45 pm](https://user-images.githubusercontent.com/34508516/33936960-790d6b90-e027-11e7-8537-f45080d52340.png)

 /** Allocate and present the scanning view controller */
    let scanningViewController: UIViewController = PPViewControllerFactory.cameraViewControllerWithDelegate(self, coordinator: coordinator!, error: nil)
![screen shot 2017-12-13 at 5 03 10 pm](https://user-images.githubusercontent.com/34508516/33936994-a25c4bce-e027-11e7-9811-a8830a64f030.png)

**Comment by puvvadakalyani** [comment]
Issue was resolved. I didn't declare the PPScanDelegate.
