### ISSUE TITLE
Dewrap signature

### ISSUE THREAD

**Issue by riki-dexter** [BlinkID/blinkid-ios#130]
Hi, i'm trying to scan MRTD passport. 
I'm using `PPMrtdCombinedRecognizerSettings` to get both full document photo and face photo.
Now i want to dewrap also signature below the face photo.
Is it possible? 

Thank you.

**Comment by cularj** [comment]
Hi @riki-dexter,

we do not support signature image extraction in `PPMrtdCombinedRecognizerSettings`. But you could try extracting it from the approximate signature position on the full document photo. This assumes that all passports that you intend to scan with the app have the signature at the same position.

Kind regards,
Jure

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
