### ISSUE TITLE
App can't find Microblink.bundle when install using CocoaPods

### ISSUE THREAD

**Issue by Magnat12** [BlinkID/blinkid-ios#133]
I occasionally get crash about no bundle included.
`*** Terminating app due to uncaught exception 'Cannot find Microblink.bundle in your main bundle', reason: 'Please make sure you have Microblink.bundle in the copy resources build phase of your app.'`

CocoaPods script seems is fine (check screenshot)
![screen shot 2018-01-10 at 1 18 09 am](https://user-images.githubusercontent.com/1451649/34748248-5141df46-f5a4-11e7-8143-b3fc057bf752.png)

**Comment by culoi** [comment]
Hi @Magnat12 

Can you please confirm that you have Git-lfs installed? You can run in terminal:

```git-lfs version```

Did you follow this steps: https://github.com/BlinkID/blinkid-ios#installation-with-cocoapods

Can you share the size of the MicroBlink.bundle and MicroBlink.framwork? 

Regards

**Comment by Magnat12** [comment]
`git-lfs/2.3.4 (GitHub; darwin amd64; go 1.9.1)`
File sizes is 5.6mb for bundle and 95.4mb for framework

I did follow installation guides and even found fix for issue when you use Cocoapods (see last comment from this ticket https://github.com/BlinkID/blinkid-ios/issues/26#issuecomment-356431558 ) But I still occasionally get crash with no bundle included :-(

**Comment by culoi** [comment]
Hello @Magnat12 

Did you try to replace MicroBlink.framework, clean and then run the project? This should solve the issue.

When asked, choose "Create groups", instead of the "Create folder references" option.

Regards

**Comment by ivl** [comment]
The same issue for me. Installation via CocoaPods is not working.

**Comment by culoi** [comment]
Hello @ivl 

Please make sure that MicroBlink.bundle is included in your project (together with MicroBlink.framework which also should be added to embedded binaries section in General settings). Clean and run project then should eliminate any crash.

Please let me know how it works.

Regards

**Comment by ivl** [comment]
@culoi I resolved this problem by resetting cache with pods. Thanks to @Magnat12
