### ISSUE TITLE
System tray full of errors 

### ISSUE THREAD

**Issue by ivl** [BlinkID/blinkid-ios#134]
You are using time-limited license key!
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIView frame]
PID: 11004, TID: 4736776, Thread name: (none), Queue name: net.photopay.frame.processing, QoS: 0
Backtrace:
4   MicroBlink                          0x00000001049372c0 GS1_register + 1274004
5   libdispatch.dylib                   0x000000010713528c _dispatch_client_callout + 16
6   libdispatch.dylib                   0x0000000107143f80 _dispatch_queue_serial_drain + 696
7   libdispatch.dylib                   0x00000001071387ec _dispatch_queue_invoke + 332
8   libdispatch.dylib                   0x0000000107144f6c _dispatch_root_queue_drain_deferred_wlh + 428
9   libdispatch.dylib                   0x000000010714c020 _dispatch_workloop_worker_thread + 652
10  libsystem_pthread.dylib             0x0000000183fb2f1c _pthread_wqthread + 932
11  libsystem_pthread.dylib             0x0000000183fb2b6c start_wqthread + 4
2018-01-22 13:52:38.068309+0200 Klear[11004:4736776] [reports] Main Thread Checker: UI API called on a background thread: -[UIView frame]
PID: 11004, TID: 4736776, Thread name: (none), Queue name: net.photopay.frame.processing, QoS: 0
Backtrace:
4   MicroBlink                          0x00000001049372c0 GS1_register + 1274004
5   libdispatch.dylib                   0x000000010713528c _dispatch_client_callout + 16
6   libdispatch.dylib                   0x0000000107143f80 _dispatch_queue_serial_drain + 696
7   libdispatch.dylib                   0x00000001071387ec _dispatch_queue_invoke + 332
8   libdispatch.dylib                   0x0000000107144f6c _dispatch_root_queue_drain_deferred_wlh + 428
9   libdispatch.dylib                   0x000000010714c020 _dispatch_workloop_worker_thread + 652
10  libsystem_pthread.dylib             0x0000000183fb2f1c _pthread_wqthread + 932
11  libsystem_pthread.dylib             0x0000000183fb2b6c start_wqthread + 4
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication statusBarOrientation]
PID: 11004, TID: 4736776, Thread name: (none), Queue name: net.photopay.frame.processing, QoS: 0
Backtrace:
4   MicroBlink                          0x0000000104937340 GS1_register + 1274132
5   libdispatch.dylib                   0x000000010713528c _dispatch_client_callout + 16
6   libdispatch.dylib                   0x0000000107143f80 _dispatch_queue_serial_drain + 696
7   libdispatch.dylib                   0x00000001071387ec _dispatch_queue_invoke + 332
8   libdispatch.dylib                   0x0000000107144f6c _dispatch_root_queue_drain_deferred_wlh + 428
9   libdispatch.dylib                   0x000000010714c020 _dispatch_workloop_worker_thread + 652
10  libsystem_pthread.dylib             0x0000000183fb2f1c _pthread_wqthread + 932
11  libsystem_pthread.dylib             0x0000000183fb2b6c start_wqthread + 4
2018-01-22 13:52:38.133223+0200 Klear[11004:4736776] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication statusBarOrientation]
PID: 11004, TID: 4736776, Thread name: (none), Queue name: net.photopay.frame.processing, QoS: 0
Backtrace:
4   MicroBlink                          0x0000000104937340 GS1_register + 1274132
5   libdispatch.dylib                   0x000000010713528c _dispatch_client_callout + 16
6   libdispatch.dylib                   0x0000000107143f80 _dispatch_queue_serial_drain + 696
7   libdispatch.dylib                   0x00000001071387ec _dispatch_queue_invoke + 332
8   libdispatch.dylib                   0x0000000107144f6c _dispatch_root_queue_drain_deferred_wlh + 428
9   libdispatch.dylib                   0x000000010714c020 _dispatch_workloop_worker_thread + 652
10  libsystem_pthread.dylib             0x0000000183fb2f1c _pthread_wqthread + 932
11  libsystem_pthread.dylib             0x0000000183fb2b6c start_wqthread + 4
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIView center]
PID: 11004, TID: 4736776, Thread name: (none), Queue name: net.photopay.frame.processing, QoS: 0
Backtrace:
4   MicroBlink                          0x00000001049145d4 GS1_register + 1131432
5   libdispatch.dylib                   0x000000010713528c _dispatch_client_callout + 16
6   libdispatch.dylib                   0x0000000107143f80 _dispatch_queue_serial_drain + 696
7   libdispatch.dylib                   0x00000001071387ec _dispatch_queue_invoke + 332
8   libdispatch.dylib                   0x0000000107144f6c _dispatch_root_queue_drain_deferred_wlh + 428
9   libdispatch.dylib                   0x000000010714c020 _dispatch_workloop_worker_thread + 652
10  libsystem_pthread.dylib             0x0000000183fb2f1c _pthread_wqthread + 932
11  libsystem_pthread.dylib             0x0000000183fb2b6c start_wqthread + 4
2018-01-22 13:52:38.177867+0200 Klear[11004:4736776] [reports] Main Thread Checker: UI API called on a background thread: -[UIView center]
PID: 11004, TID: 4736776, Thread name: (none), Queue name: net.photopay.frame.processing, QoS: 0
Backtrace:
4   MicroBlink                          0x00000001049145d4 GS1_register + 1131432
5   libdispatch.dylib                   0x000000010713528c _dispatch_client_callout + 16
6   libdispatch.dylib                   0x0000000107143f80 _dispatch_queue_serial_drain + 696
7   libdispatch.dylib                   0x00000001071387ec _dispatch_queue_invoke + 332
8   libdispatch.dylib                   0x0000000107144f6c _dispatch_root_queue_drain_deferred_wlh + 428
9   libdispatch.dylib                   0x000000010714c020 _dispatch_workloop_worker_thread + 652
10  libsystem_pthread.dylib             0x0000000183fb2f1c _pthread_wqthread + 932
11  libsystem_pthread.dylib             0x0000000183fb2b6c start_wqthread + 4
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIView transform]
PID: 11004, TID: 4736776, Thread name: (none), Queue name: net.photopay.frame.processing, QoS: 0
Backtrace:
4   MicroBlink                          0x0000000104914600 GS1_register + 1131476
5   libdispatch.dylib                   0x000000010713528c _dispatch_client_callout + 16
6   libdispatch.dylib                   0x0000000107143f80 _dispatch_queue_serial_drain + 696
7   libdispatch.dylib                   0x00000001071387ec _dispatch_queue_invoke + 332
8   libdispatch.dylib                   0x0000000107144f6c _dispatch_root_queue_drain_deferred_wlh + 428
9   libdispatch.dylib                   0x000000010714c020 _dispatch_workloop_worker_thread + 652
10  libsystem_pthread.dylib             0x0000000183fb2f1c _pthread_wqthread + 932
11  libsystem_pthread.dylib             0x0000000183fb2b6c start_wqthread + 4
2018-01-22 13:52:38.221727+0200 Klear[11004:4736776] [reports] Main Thread Checker: UI API called on a background thread: -[UIView transform]
PID: 11004, TID: 4736776, Thread name: (none), Queue name: net.photopay.frame.processing, QoS: 0
Backtrace:
4   MicroBlink                          0x0000000104914600 GS1_register + 1131476
5   libdispatch.dylib                   0x000000010713528c _dispatch_client_callout + 16
6   libdispatch.dylib                   0x0000000107143f80 _dispatch_queue_serial_drain + 696
7   libdispatch.dylib                   0x00000001071387ec _dispatch_queue_invoke + 332
8   libdispatch.dylib                   0x0000000107144f6c _dispatch_root_queue_drain_deferred_wlh + 428
9   libdispatch.dylib                   0x000000010714c020 _dispatch_workloop_worker_thread + 652
10  libsystem_pthread.dylib             0x0000000183fb2f1c _pthread_wqthread + 932
11  libsystem_pthread.dylib             0x0000000183fb2b6c start_wqthread + 4
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIView bounds]
PID: 11004, TID: 4736776, Thread name: (none), Queue name: net.photopay.frame.processing, QoS: 0
Backtrace:
4   MicroBlink                          0x0000000104914660 GS1_register + 1131572
5   libdispatch.dylib                   0x000000010713528c _dispatch_client_callout + 16
6   libdispatch.dylib                   0x0000000107143f80 _dispatch_queue_serial_drain + 696
7   libdispatch.dylib                   0x00000001071387ec _dispatch_queue_invoke + 332
8   libdispatch.dylib                   0x0000000107144f6c _dispatch_root_queue_drain_deferred_wlh + 428
9   libdispatch.dylib                   0x000000010714c020 _dispatch_workloop_worker_thread + 652
10  libsystem_pthread.dylib             0x0000000183fb2f1c _pthread_wqthread + 932
11  libsystem_pthread.dylib             0x0000000183fb2b6c start_wqthread + 4
2018-01-22 13:52:38.269525+0200 Klear[11004:4736776] [reports] Main Thread Checker: UI API called on a background thread: -[UIView bounds]
PID: 11004, TID: 4736776, Thread name: (none), Queue name: net.photopay.frame.processing, QoS: 0
Backtrace:
4   MicroBlink                          0x0000000104914660 GS1_register + 1131572
5   libdispatch.dylib                   0x000000010713528c _dispatch_client_callout + 16
6   libdispatch.dylib                   0x0000000107143f80 _dispatch_queue_serial_drain + 696
7   libdispatch.dylib                   0x00000001071387ec _dispatch_queue_invoke + 332
8   libdispatch.dylib                   0x0000000107144f6c _dispatch_root_queue_drain_deferred_wlh + 428
9   libdispatch.dylib                   0x000000010714c020 _dispatch_workloop_worker_thread + 652
10  libsystem_pthread.dylib             0x0000000183fb2f1c _pthread_wqthread + 932
11  libsystem_pthread.dylib             0x0000000183fb2b6c start_wqthread + 4

**Comment by culoi** [comment]
Hello @ivl 

Does it crash your app or you are able to perform a scan? 

This is simply a warning, our iOS dev team is currently working on removing it, but it shouldn't affect scanning in any way.

Regards

**Comment by ivl** [comment]
@culoi no. It works without problem But I don't want to see garbage in console

**Comment by mawshd** [comment]
I am getting my application crash when i scan my driver license multiple times....

**Comment by mawshd** [comment]
Even though i am presenting scaning controller in Dispatch main queue

DispatchQueue.main.async {
            self.present(scanningViewController, animated: true, completion: nil)
        }

**Comment by culoi** [comment]
This is solved in our new API version of the BlinkID. Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
