### ISSUE TITLE
I want to scan only signature in app . just like Mac os provide Preview in pdf and mail document . Can i do that using this library ? 

### ISSUE THREAD

**Issue by namanzetrixweb** [BlinkID/blinkid-ios#135]

**Comment by culoi** [comment]
Hello @namanzetrixweb 

To crop signature from the document, the solution is to use Templating API: https://github.com/BlinkID/blinkid-ios/wiki/Using-Templating-API and especially this part: https://github.com/BlinkID/blinkid-ios/wiki/Using-Templating-API#additional-tips

Can you please explain the "scan" part? Do you want to perform OCR on the signature or simply crop signature from the image of the document? 

Regards

**Comment by namanzetrixweb** [comment]
Actually  i want to scan signature using device inbuilt camera , just like
Preview in Macbooks . Preview provide facility to scan signature and you
can use that signature as digital signature to sign pdf or other documents
.
So i want to use that functionality in my application .
