### ISSUE TITLE
Support for UAE Emirates ID

### ISSUE THREAD

**Issue by snehasree** [BlinkID/blinkid-ios#140]
I am using MRTDCombinedRecognizerSettings to scan the front and back side of the emirates id.
But the scan is detecting only the back side of the emirates id. Can someone tell me what should I do to scan the front side of the emirates id, as I need to capture the face image also.

**Comment by culoi** [comment]
Hello,

You can use PPUnitedArabEmiratesIDFrontRecognizer and PPUnitedArabEmiratesIDBackRecognizer. We will add CombinedRecognizer in one of the future releases. We introduce this in the latest release of the BlinkID.

For the DocumentFace you can use [DocumentFaceRecognizer](http://cocoadocs.org/docsets/PPBlinkID/2.13.0/Classes/PPFaceDetectorSettings.html) to obtain face image. 

Regards

**Comment by snehasree** [comment]
Thank you. I am now able to scan face image and details using PPUnitedArabEmiratesIDFrontRecognizer and PPUnitedArabEmiratesIDBackRecognizer. 

In the BlinkID app downloaded from iTunes, as soon the front side of the Emirates ID is scanned the UI changes and asks user to scan the back. How can I achieve this functionality. Also, I need to use custom overlap view. I am doing this as mentioned below.
    /** Create subclass of PPOverlayViewController*/
   `PPOverlayViewController *overlayViewController =
    [[PPOverlayViewController alloc] initWithNibName:@"PPCameraOverlayViewController" bundle:nil];`
 
    /** Create new scanning view controller */
    UIViewController<PPScanningViewController> *scanningViewController =
    [PPViewControllerFactory cameraViewControllerWithDelegate:self overlayViewController:overlayViewController coordinator:coordinator error:nil];

My issue now is I need to use 2 different overlays for front and back side scanning. How do I implement that? Should I create 2 nib files or can I change the image on a single nib file itself?

**Comment by culoi** [comment]
Hi @snehasree 

You can first set the FrontRecognizer, after front side is successfully scanned you can do your UI changes and add the BackRecognizer.

As for overlay, you can use 2 different overlays, but we suggest that if it is possible, that you use 1 overlay and make changes on it after the front side was scanned successfully.

Regards

**Comment by snehasree** [comment]
Thanks @culoi 

As for using custom overlays, I am able to achieve it when creating overlay view controller as a separate view controller xib, but when I try to create the view controller as part of the main storyboard it is giving me the following error
[UIViewController setContainerViewController:]: unrecognized selector sent to instance 0x7ff835c05100'
Below is the code I am using.

 

   ```
 PPOverlayViewController *overlayViewController = (PPOverlayViewController *)[self.storyboard instantiateViewControllerWithIdentifier:@"ppCamOverlay"];
UIViewController<PPScanningViewController> *scanningViewController =
    [PPViewControllerFactory cameraViewControllerWithDelegate:self overlayViewController:overlayViewController coordinator:coordinator error:nil];
```

Does it not support a view controller created in storyboard?

**Comment by snehasree** [comment]
Thank you @culoi .
