### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by Magnat12** [BlinkID/blinkid-ios#142]
Is MicroBlink framework support bitcode? Can't find any signs of it using 
`otool -l MicroBlink | grep bitcode` or `otool -l MicroBlink | grep LLVM`

**Comment by culoi** [comment]
Hello @Magnat12 

All Microblink products are build with the Bitcode support.

Regards,

Ivan

**Comment by Magnat12** [comment]
@culoi Thanks!
