### ISSUE TITLE
Issue related to OpenGLRenderingContext.cpp

### ISSUE THREAD

**Issue by Radhika-Geek** [BlinkID/blinkid-ios#143]
I am sending frames to processImage : method. But If am going to background and coming back few times. It get crash and I get these logs -

[E] checkGLError [glUtils.cpp:50] 2018-02-26 10:37:35.410887+0530 
ERROR: glFramebufferTexture2D: GL error: GL_INVALID_VALUE: A numeric argument is out of range.
[E] bindFrameBuffer [OpenGLRenderingContext.cpp:79] 2018-02-26 10:37:35.412787+0530 
unable to bind framebuffer

**Comment by DoDoENT** [comment]
Hi!

Which version of BlinkID are you using? Can you reproduce that bug with any of our [sample apps](https://github.com/BlinkID/blinkid-ios/tree/master/Samples)? Are you using Direct API or BlinkID's native camera management?

**Comment by Radhika-Geek** [comment]
Hi,

I am using v2.16.0 and using Direct API. Converting frame to PPImage and sending to processImage : method.

Also getting result callback. But when going to background it gives this error log and crash sometimes.
Yes it is happening in DirectAPI-Sample.

**Comment by DoDoENT** [comment]
Hi!

Thank you for the information. Our developers will try to recreate the issue on our side and determine if there is a workaround you can apply on your side or if there will be a need for us to issue a bugfix update.

We will contact you when we gather more information about the issue.

**Comment by Radhika-Geek** [comment]
Thanks.

*Thanks,*

*Radhika Sharma*
*iOS Developer*
radhika@idmetrics.com


www.idmetrics.com

**Comment by cularj** [comment]
Hi @Radhika-Geek,

we tried reproducing this but we couldn't, could you send us the code you added to the sample(if you did) and steps to reproduce it.

Kind regards,
Jure

**Comment by Radhika-Geek** [comment]
I have changed just changed recognizer to PPHongKongIDFrontRecognizerSettings to check for Hongkong ID data.

Rest if I continously go to background and comeback to foreground. Crash happens.

**Comment by Radhika-Geek** [comment]
Is there any method that terminates process at Microblink end even if any request has been made. 
I think problem happens, if I sent an image to Microblink even after going to background  it returns callback.

**Comment by cularj** [comment]
@Radhika-Geek 

We are still trying to reproduce this on DirectAPI-sample app with Hong Kong Front recognizer.
Could you make a video and recreate the steps with the DirectAPI-sample app, also what device are you using.

Kind regards,
Jure

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
