### ISSUE TITLE
Support for UAE Visa

### ISSUE THREAD

**Issue by snehasree** [BlinkID/blinkid-ios#145]
Does BlinkID support scanning of UAE Visa?

**Comment by culoi** [comment]
Hello @snehasree 

With our MRTDRecognizer we support all the documents that have an MRZ line according to ICAO Document 9303 standard. 

Most Visas in the world have MRZ line, however, there are some samples that don't have one.

Can you please contact us with more information and sample (if you are able to provide one) at support@microblink.com. We will evaluate the document and let you know if we are able to support it.

Regards
