### ISSUE TITLE
+[PPCameraCoordinator isScanningUnsupportedForCameraType:error:] API Design issues

### ISSUE THREAD

**Issue by BergQuester** [BlinkID/blinkid-ios#146]
This API has several design issues:

## Returns YES if the given type is unsupported

The double-negative between the return type and the method name is quite awkward. Moreover, it can cause confusion, especially when language convention would be to return NO for unsupported types. For example Apple's [+[UIImagePickerController isSourceTypeAvailable:]](https://developer.apple.com/documentation/uikit/uiimagepickercontroller/1619144-issourcetypeavailable?language=objc) API returns NO when the source type is not available.

## Takes an NSError out parameter

In the language convention, NSErrors are usually not used when there is a lack of support for a feature, but for when an _unexpected_ problem is encountered. As asking if a feature is supported by definition expects there to be the possibility that the feature is not supported. Again, Apple's [+[UIImagePickerController isSourceTypeAvailable:]](https://developer.apple.com/documentation/uikit/uiimagepickercontroller/1619144-issourcetypeavailable?language=objc) does not take an error parameter. The reason for the lack of support ought to be supplied via another route.

## Does not adhere to language conventions for error handling

If using NSError is for some reason absolutely necessary here, then there are still issues with the implementation.

### Does not adhere to return value semantics for a method that takes an NSError

This is effectively the same problem as the first problem, but for a different reason. Convention states that the NSError parameter should only be accessed if the return value of the method evaluates to NO. From Apple's guide on [Using and Creating Error Objects](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ErrorHandlingCocoa/CreateCustomizeNSError/CreateCustomizeNSError.html):

> Important: Success or failure is indicated by the return value of the method. Although Cocoa methods that indirectly return error objects in the Cocoa error domain are guaranteed to return such objects if the method indicates failure by directly returning nil or NO, **you should always check that the return value is nil or NO before attempting to do anything with the NSError object.**

Emphasis mine.

### The method has Swift error throwing explicitly disabled with NS_SWIFT_NOTHROW

Swift convention is to use methods that are declared as `throws` to handle errors. However this method has it explicitly disabled. This leads to some awkward and ugly `NSErrorPointer` handling that is not common in Swift. I suspect that the reason this has been disabled is because the return value semantics are backward which confuses the compiler into doing the wrong thing.

## Request:

Please adjust this method to adhere to common conventions such as return value semantics and giving lack of support reasons via another route.

If that cannot be done, please fix the error handling behavior of the method.

**Comment by culoi** [comment]
This is solved in the new API version of the BlinkID. Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
