### ISSUE TITLE
 [iOS] - Failed to load resource malaysian_state_dictionary.

### ISSUE THREAD

**Issue by thalesbm2** [BlinkID/blinkid-ios#148]
Hi guys,

Previous I had the app running against the blinkID 2.13 SDK, but when I updated to blinkID 2.16, I started to get the error below when I tried to scan a Malaysian ID (front).

Failed to load resource malaysian_state_dictionary. The program will now crash! libc++abi.dylib: terminating

Do you have any idea?

Thanks,
Thales

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
