### ISSUE TITLE
Add ability to configure output document image DPI for different recognizer settings

### ISSUE THREAD

**Issue by Magnat12** [BlinkID/blinkid-ios#149]
Hi, I faced with problem that I need to get full document image with good quality.
But only `PPMrtdRecognizerSettings` have ability to setup `fullDocumentImageDPI` and configure result document image quality. 
I didn't find any similar functionality for other recognizer settings (like `PPGermanIDFrontRecognizerSettings` or `PPEudlRecognizerSettings`).

For example if I use direct processing API with image 2000x1600, I did get about 800x500 full document  image for `PPGermanIDFrontRecognizerSettings`, comparing with 1800x1500 for `PPMrtdRecognizerSettings` with `fullDocumentImageDPI` set to `400`

Is it possible somehow improve result image quality?

**Comment by dCubelic** [comment]
Hi,

In new SDK (4.2.0) we have this functionality added to all (non-combined) recognizers.

If you are interested on implementing it, check out the documentation for BlinkID.

Best regards,
Dominik
