### ISSUE TITLE
Customized Framework Causes Linker Errors When Archiving

### ISSUE THREAD

**Issue by bleedsy** [BlinkID/blinkid-ios#152]
I created a custom dynamic framework from v2.16.1 per the [instructions ](https://github.com/BlinkID/blinkid-ios/wiki/Creating-customized-build) with the following features:
```
 set( FEATURE_DEFAULT_OPTION                 OFF CACHE BOOL "" ) # disable all recognizers
 set( FEATURE_MRTD                           ON  CACHE BOOL "" ) # enable MRTD recognizer
 set( FEATURE_USDL                           ON  CACHE BOOL "" )
 set( FEATURE_DETECTOR                       ON  CACHE BOOL "" )
```

I am able to successfully build the app but run into linker errors when trying to archive.

<img width="1774" alt="screen shot 2018-04-02 at 5 06 17 pm" src="https://user-images.githubusercontent.com/6255958/38216232-3000aef4-3698-11e8-981b-c0f66003420a.png">

**Comment by culoi** [comment]
Hello @bleedsy

I didn't manage to recreate the issue exactly, but I notice when I include recognizers that are not built with enabled-features.cmake, I got a similar error (which is expected).

I included features from your post, simply run ./create-custom-build.sh script, select dynamic build and include framework and bundle in the project. 
On purpose I include USDLCombinedRecognizer (instead USDL) and got this error: 
![screen shot 2018-04-03 at 11 12 25](https://user-images.githubusercontent.com/24894049/38243025-96ff6d18-3736-11e8-8526-bf50ce48048a.png)

But once I put correct USDLRecognizer, I manage to build the app without the issues.

Can you please explain in a bit more details how did you build framework? Did you use the script from a terminal or you build it from the project?

You also have an interesting warning in the screenshot. Are you linking simulator build in device app? 

Regards

**Comment by bleedsy** [comment]
Hi @culoi 

Building for device and simulator works but archiving does not. Did you try to build for the generic device or archive?

The steps I took to create the dynamic library were:
1. ran `./create-custom-build.sh script`
2. selected dynamic

I used the `all` library. This is the output when I ran the `file` command:

```
Release/all/MicroBlink.framework/MicroBlink: Mach-O universal binary with 2 architectures: [x86_64: Mach-O 64-bit dynamically linked shared library x86_64] [arm64]
Release/all/MicroBlink.framework/MicroBlink (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
Release/all/MicroBlink.framework/MicroBlink (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

`armv7` is missing. If I create a static library, armv7 is supported. Can you share your output?

Thanks

**Comment by bleedsy** [comment]
Ah got it. Makes sense. This fixed it. Thank you for your help!
