### ISSUE TITLE
Add support for Swift 4.1

### ISSUE THREAD

**Issue by DrewKiino** [BlinkID/blinkid-ios#156]
Just recently upgraded my XCode to 9.3 (which comes with Swift 4) and have been getting this error when trying to upload to the App Store

<img width="745" alt="screen shot 2018-04-10 at 5 51 40 pm" src="https://user-images.githubusercontent.com/13005359/38590711-d8bc913e-3ce7-11e8-838c-edaa5f27ae7f.png">

I have tried cleaning, deleting derived data, trying different variations of `enable_bitcode` between `Pods` and `Project`, and I've consistently gotten this error message for this framework.

**Comment by Pickles112358** [comment]
To me this looks like dylib you are trying to upload contains simulator architectures. Removing those architectures from dylib should solve the problem.
Easiest way to do this is:

1. Open your terminal and position yourself in MicroBlink.framework folder (which contains dylib named MicroBlink):
https://github.com/BlinkID/blinkid-ios/tree/master/MicroBlink.framework

2. Run these two commands:
lipo -remove x86_64 MicroBlink -output MicroBlink
lipo -remove i386 MicroBlink -output MicroBlink

This should remove simulator builds from the dylib and will solve your bitcode-related errors.

**Comment by farkasseb** [comment]
I have the same problem and the framework doesn't contain any simulator architecture slices. We are trying to upload an app build with Xcode 9.3, CocoaPods 1.5.0 and MicroBlink 2.17.0

`lipo -info MicroBlink`
> Architectures in the fat file: MicroBlink are: armv7 arm64

Any ideas?

**Comment by Pickles112358** [comment]
We confirm that this indeed is an error. We will try to deploy a hotfix by the end of the day.

**Comment by Pickles112358** [comment]
This has now been fixed and released. Closing

**Comment by farkasseb** [comment]
Thank you very much, we will verify it soon!
