### ISSUE TITLE
"Getting started" example code does not work with 1.3.0

### ISSUE THREAD

**Issue by lukaskukacka** [BlinkID/blinkid-ios#16]
Hello BlinkID,
the [Getting started with BlinkID SDK](https://github.com/BlinkID/blinkid-ios/wiki/Getting-started) page contains an example code which cannot be compiled with library version *1.3.0*.

Example code contains this check:
```
if ([PPCoordinator isScanningUnsupported:error]) {
    return nil;
}
```
but compilation fails with `No known class method for selector 'isScanningUnsupported:`. In *1.3.0* the correct code for this check is:
```
if ([PPCoordinator isScanningUnsupportedForCameraType:PPCameraTypeFront error:error]) {
    return nil;
}
```

**Comment by Cerovec** [comment]
You are right. We'll fix this ASAP.

Both Obj-C and Swift versions have the same issue.

Thanks!

**Comment by Cerovec** [comment]
Lukas,
just to verify - we would use camera type PPCameraTypeBack in our documentation, because it's a more common use case to scan with back facing camera. Is this OK with you?
Thanks!

**Comment by Cerovec** [comment]
Wiki is updated - https://github.com/BlinkID/blinkid-ios/wiki/Getting-started

Please take a look and close if this solves your issue.

**Comment by lukaskukacka** [comment]
@Cerovec Looks fine for me. Thanks. Of course `PPCameraTypeBack` is correct since it is a default value of `settings.cameraSettings`, sorry my mistake :-)

---

Thinking of that, to prevent inconsistency of check vs settings causing potential bugs, I would in my code probably inverse the order like this instead:

```
PPSettings *settings = [[PPSettings alloc] init];
    
if ([PPCoordinator isScanningUnsupportedForCameraType:settings.cameraSettings.cameraType error:error]) {
    return nil;
}
```
This way, the check is always made to settings which which will actually be used.
