### ISSUE TITLE
2.17.2 cannot be compiled at all in test samples

### ISSUE THREAD

**Issue by ambuDevs** [BlinkID/blinkid-ios#162]
Hi,

I have an urgent request. The upload to TestFlight is not possible with master version as bitcode is missing. The feature version 2.17.2 that should fix the code cannot be compiled (also the sample projects are not working.)

ignoring file ../../MicroBlink.framework/MicroBlink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): ../../MicroBlink.framework/MicroBlink

Thanks for a quick fix,
Ivonne

**Comment by Pickles112358** [comment]
Hi @ambuDevs 

This was a problem with out 2.17.2 version and we have released v2.17.3 last week to fix this issue. Please try to update to v2.17.3 and let us know if this is fixed.

**Comment by culoi** [comment]
Closing the issue. Please reopen if you have additional question or contact us directly at support@microblink.com
