### ISSUE TITLE
I can't run sample code

### ISSUE THREAD

**Issue by mobile3000** [BlinkID/blinkid-ios#164]
I have run after download source code from GitHub.
But It's not building.
I get the following error.
http://prntscr.com/jhklq9

**Comment by culoi** [comment]
Hi @mobile3000 

Did you use Git-lfs during the clone of the SDK or you just use download button? 

With download button you only get source without required frameworks, as Git doesn't fully support Git LFS.

Please try to you clone this git repository. You need to install Git Large File Storage by running these commands:
```
brew install git-lfs
git lfs install
```
To clone, run the following shell command:

```git clone git@github.com:BlinkID/blinkid-ios.git```

Please let me know how it works for you.

Best regards

**Comment by mobile3000** [comment]
Thanks for your reply.
But your command is not working in terminal.
http://prntscr.com/jhl51e

**Comment by cularj** [comment]
Hi @mobile3000

I suggest that you install [homebrew](https://brew.sh) or you can install [git-lfs directly](https://git-lfs.github.com).

Kind regards,
Jure

**Comment by mobile3000** [comment]
And when I used the command you sent, I get the error.
git clone git@github.com:BlinkID/blinkid-ios.git

http://prntscr.com/jhmilv

**Comment by cularj** [comment]
Follow [this guide](https://github.com/BlinkID/blinkid-ios#installation-with-cocoapods) to install our framework with cocoapods.
If the problem still persists, I suggest cleaning pod cache, this usually helps with git-lfs issues.

As for git clone issue use https instead:
`git clone https://github.com/BlinkID/blinkid-ios.git`

**Comment by culoi** [comment]
Closing the issue. Please reopen if you have additional question or contact us directly at support@microblink.com
