### ISSUE TITLE
Wiki getting started with swift sample code:  [AnyObject]! -> [PPRecognizerResult]!

### ISSUE THREAD

**Issue by hshah8831** [BlinkID/blinkid-ios#17]
In the wiki for getting started with swift the sample code uses this -:
func scanningViewController(scanningViewController: UIViewController!, didOutputResults results: [AnyObject]!)

while copying this gives a compilation error saying all the required function of the PPScanDelegate protocol are not being implemented.

However, changing results type from [AnyObject]! to [PPRecognizerResult]! resolves the issue and the sample works fine. Like below.

func scanningViewController(scanningViewController: UIViewController!, didOutputResults results: [PPRecognizerResult]!)

I think the wiki needs this small change.

**Comment by Cerovec** [comment]
Thanks for the issue report.
It has been resolved - take a look here: https://github.com/BlinkID/blinkid-ios/wiki/Getting-started-in-Swift
If everything is fine now with this, please close the issue.

**Comment by hshah8831** [comment]
It looks good, only thing left is you will have to add an optional unwrap (!) after [PPRecognizerResult].
as follows-: 
func scanningViewController(scanningViewController: UIViewController!, didOutputResults results: [PPRecognizerResult]!)
