### ISSUE TITLE
Unable to initialize OCR Parser with Regex

### ISSUE THREAD

**Issue by cpowers** [BlinkID/blinkid-ios#173]
* Xcode version:  9
  * BlinkID SDK version: 2.13
  * What are you trying to scan? Custom ID cards

Consistently receive the following message in the log when trying to use a PPRegexOcrParserFactory for OCR scanning with the Templating API.

 I try and initialize as follows: 

```
PPRegexOcrParserFactory *subscriberIdParser = [[PPRegexOcrParserFactory alloc] initWithRegex:@"[0-9]{12}"];
```

Then in the logs I get the following message and the parser is not used for the template API.

```
[E] createFromRegexPattern [EpsNFA.hpp:862] 2018-06-14 11:33:25.186615-0500 App[48456:16056028] Invalid character in interval specification!
```

How can I get the RegexOcrParser to work correctly?

**Comment by MSkrilj** [comment]
Hi,
We are unable to reproduce this issue. This is a valid regex and it works for us both in native code and in iOS applications. Could you check the encoding on the file containing this code?

You could also try to upgrade to the latest version of the SDK and see if it helps.

**Comment by cpowers** [comment]
I upgraded the SDK and that has resolved the issue.
