### ISSUE TITLE
Licence Key Invalid

### ISSUE THREAD

**Issue by JayeshMardiya** [BlinkID/blinkid-ios#180]
* Xcode version: 9.4.1
  * BlinkID SDK version:4.0.0
  * What are you trying to scan? It will crash before scanning

#### Console log:

```
// 2018-07-10 20:15:14.218550+0530 LicenceScanDemo[8983:4512832] Resource bundle is nil!
2018-07-10 20:15:14.241581+0530 LicenceScanDemo[8983:4512832] *** Terminating app due to uncaught exception 'MBInvalidLicenseKeyException', reason: 'Your license key is invalid! Please check if you have all wanted rights.'
*** First throw call stack:
(0x18210ad8c 0x1812c45ec 0x100ce91c8 0x1006a5bd8 0x1006a540c 0x1006a6108 0x18be7664c 0x18bf97870 0x18be7c700 0x18bfb21a8 0x18bef99e0 0x18beee890 0x18beed1d0 0x18c6ced1c 0x18c6d12c8 0x18c6ca368 0x1820b3404 0x1820b2c2c 0x1820b079c 0x181fd0da8 0x183fb5020 0x18bfed758 0x1006a915c 0x181a61fc0)
libc++abi.dylib: terminating with uncaught exception of type NSException

MBRawParser is nil
```

**Comment by DoDoENT** [comment]
> ```Terminating app due to uncaught exception 'MBInvalidLicenseKeyException', reason: 'Your license key is invalid! Please check if you have all wanted rights.'```

Please register at [Microblink Developer Dashboard](https://microblink.com/login) and create a free trial license key for your app's bundle ID.

**Comment by JayeshMardiya** [comment]
I already created with apps.jaypatel@gmail.com
    	
    	

    	Get Outlook for iOS
    
  




On Tue, Jul 10, 2018 at 8:48 PM +0530, "DoDo" <notifications@github.com> wrote:













Terminating app due to uncaught exception 'MBInvalidLicenseKeyException', reason: 'Your license key is invalid! Please check if you have all wanted rights.'



Please register at Microblink Developer Dashboard and create a free trial license key for your app's bundle ID.

**Comment by JayeshMardiya** [comment]
![screen shot 2018-07-11 at 11 11 32 am](https://user-images.githubusercontent.com/16998798/42552711-489544dc-84fb-11e8-96ce-5e0a983eb3ef.png)

Here is my code, I am using cocoapods, Please help me!

**Comment by JayeshMardiya** [comment]
Can anyone help me for this?

**Comment by culoi** [comment]
Hello Jayesh,

Can you please share the line of the code where you setting up the license key/license key file?

Regards

**Comment by JayeshMardiya** [comment]
How can we set licence key?

**Comment by culoi** [comment]
Hello,

You can set the license key on the following way:

MBMicroblinkSDK.sharedInstance().setLicenseResource("license", withExtension: "mblic", inSubdirectory: "License", for: Bundle.main)
    
in viewDidLoad.

Besideds setting LicenseKey file there are couple other ways:

/** Set the Base64 license */
settings.licenseSettings.base64License = @“your_base64_license_here”;


 /**OR*/ 

/** Set the License from the file*/
settings.licenseSettings.licenseFilePath = @“path_to_your_.mblic_file”;


 /**OR*/ 

/** Load the License as byte array*/
settings.licenseSettings.licenseBuffer = { 0x01, 0x02, etc };

You can also check our sample app in BlinkID SDK folder Samples: https://github.com/BlinkID/blinkid-ios/blob/master/Samples/BlinkID-sample-Swift/BlinkID-sample-Swift/ViewController.swift

Regards

**Comment by JayeshMardiya** [comment]
Ohh Yes,

I forgot to add this line in viewDidLoad()

MBMicroblinkSDK.sharedInstance().setLicenseKey("LICENSE KEY")

Thank a lot

**Comment by JayeshMardiya** [comment]
Licence not scanning

**Comment by culoi** [comment]
Hello,

It means exactly what it says, that you are using demo license key that is time limited. This warning is present to prevent users going live with demo license key. With production license key, this warning isnt present.

Regarding scanning of the Australian license, we currently support Victoria DL. Which state DL are you trying to scsn?

Regards

**Comment by JayeshMardiya** [comment]
Only support Victoria DL?

**Comment by JayeshMardiya** [comment]
What about other DL from AUS?

**Comment by culoi** [comment]
DL’s from other Australia states are currently not supported. If there is a requirement to support them, please contact our Sales team: sales@microblink.com with more information about your use-case.

Regards

**Comment by jcular** [comment]
Issue solved
