### ISSUE TITLE
Pod not installing

### ISSUE THREAD

**Issue by avadhbambhroliya** [BlinkID/blinkid-ios#183]
![screen shot 2018-07-18 at 3 00 56 pm](https://user-images.githubusercontent.com/30489217/42872857-9d1cc822-8a9b-11e8-8038-b98cd46c8d5c.png)

**Comment by cularj** [comment]
Hi @avadhbambhroliya,

it seems that you don't have git-lfs installed please follow the [instructions](
https://github.com/BlinkID/blinkid-ios#1-initial-integration-steps).

Kind regards,
Jure

**Comment by avadhbambhroliya** [comment]
@cularj not working. can i install this manually?

**Comment by jcular** [comment]
Closed due to inactivity.
