### ISSUE TITLE
Catch MBInvalidLicenseKeyException

### ISSUE THREAD

**Issue by xrayman** [BlinkID/blinkid-ios#184]
* Xcode version: 9.4.1, Swift 4.1
  * BlinkID SDK version: 4.0.0
  * What are you trying to scan? Doesn't matter, app crashes before scan

If I set invalid license or don't set any license at all an app will crash on trying to create any kind of MBRecognizer with MBInvalidLicenseKeyException. Is there any option to check license for validity beforehand in order to prevent such crashes? Or catch the exception without crashing the app.
Do...catch is not working because constructors for MBRecognizer are not marked with 'throws'.

**Comment by xrayman** [comment]
So, seems like I've got confused when the crash appears. Looks like it appears when I'm trying to set an invalid key. But still the question is how to catch that crash?

**Comment by xrayman** [comment]
Well, I've figured out how to manage this issue. I'm able to catch the exception using obj-c exception handling. 
Add these files to project and include ExceptionCatcher.h into your bridging header. After that you will be able to set any key and handle invalid ones in the swift code.
Something like:
```
if ExceptionCatcher.performBlockCatchingExceptions({
    MBMicroblinkSDK.sharedInstance().setLicenseKey(licenseKey)
}) != nil {
    print("seems like license is invalid")
} else {
    print("license is ok")
}
```

ExceptionCatcher.h
```
#import <Foundation/Foundation.h>

@interface ExceptionCatcher: NSObject

+(NSException*)performBlockCatchingExceptions:(void (^)(void))block;

@end
```

ExceptionCatcher.m
```
#import "ExceptionCatcher.h"

@implementation ExceptionCatcher

+(NSException*)performBlockCatchingExceptions:(void (^)(void))block {
    @try {
        block();
        return nil;
    } @catch (NSException *exception) {
        NSLog(@"%@", exception.reason);
        return exception;
    } @finally {}
}

@end
```

**Comment by delyar** [comment]
@xrayman  I have the exact problem as yours. but your solution did not work for me.
It will come to the line print("seems like license is invalid") and then crashes again.
 I could not catch the MBInvalidLicenseKeyException exception.
