### ISSUE TITLE
CombinedRecognizer from templating 

### ISSUE THREAD

**Issue by ahbou** [BlinkID/blinkid-ios#186]
Hello

I'm trying to scan both faces of an ID card and I would like to use the proper MBDocumentVerificationOverlayViewController.

In my understandings, that this Controller only works with CombinedRecognizer.

How can I build a CombinedRecognizer from my templating classes?

Thank you.

  * Xcode version: 9.4
  * BlinkID SDK version: 4.0
  * What are you trying to scan? ID Card

**Comment by jcular** [comment]
Hi @ahbou,

sorry for delayed response but no it's not possible to make a CombinedRecognizer from templating classes that would work like our CombinedRecognizers with MBDocumentVerificationOverlayViewController.

Kind regards,
Jure
