### ISSUE TITLE
Custom view animated dots

### ISSUE THREAD

**Issue by danielbotka** [BlinkID/blinkid-ios#187]
Hi,

How can I implement the animated dots, indicating the scan is happening in a `MBCustomOverlayViewController` (like in `MBDocumentVerificationOverlayViewController`)?

Thanks

**Comment by Pickles112358** [comment]
Hi @danielbotka ,

You need to do several things:
1. Add `MBDotsResultSubview` to your overlay as a subview. Be sure set constraints so it fills the whole screen.
2. Have your overlay implement `MBDetectionRecognizerRunnerViewControllerDelegate` and set itself as a delegate:
`self.metadataDelegates.detectionRecognizerRunnerViewControllerDelegate = self`
3. Catch the dot event and send desired dots to `MBDotsResultSubview` initialized in step 1:
```swift
- (void)recognizerRunnerViewController:(UIViewController<MBRecognizerRunnerViewController> *)recognizerRunnerViewController didFinishDetectionWithDisplayablePoints:(MBDisplayablePointsDetection *)displayablePoints {
    dispatch_async(dispatch_get_main_queue(), ^{
        [self.modernDotsSubview detectionFinishedWithDisplayablePoints:displayablePoints];
    });
}
```

Let me know if this helps!
Dino

**Comment by danielbotka** [comment]
Hi @Pickles112358,

It works wonderfully! Thanks for your help!

Daniel
