### ISSUE TITLE
Issue on displaying orc result as green character in own custom camera view controller.

### ISSUE THREAD

**Issue by Jovial-Ionnex** [BlinkID/blinkid-ios#189]
Dear Microblink,
As our company has decided to migrate to version 4.0, we found out that certain features was removed as per quote below.

```
let settings: PPSettings = PPSettings(resourceBundle: Bundle(path: path)!)
settings.uiSettings.showOcrResults = true
```

However, we found that this features have been replaced by the option below as a Overlay subview presenting status of OCR detection. OCR results are displayed as green characters over detected locations:
```
class MBOcrResultSubview : MBSubview, MBOcrLayoutSubview
```

which is mentioned at the link below:
http://blinkid.github.io/blinkid-ios/Classes.html#/c:objc(cs)MBOcrResultSubview

Even there is no sample on how to implement the code if we which to use MBOcrResultSubview with MBCustomOverlayViewController which  is an abstract class for all custom overlay views placed on top View Controller in case we wish to display the orc result as green character in own custom camera ui.

Best Regards,
Jovial

NB: Your example did not show how this is implemented nor your documentation did stated on how to perform this.

**Comment by miguelpenades** [comment]
Same doubt here!

**Comment by Jovial-Ionnex** [comment]
Dear Microblink,

We trying to implement MBOcrResultSubview on MBCustomOverlayViewController
as below:
```
var ocrView: MBOcrResultSubview!
ocrView = MBOcrResultSubview(frame: self.view.frame)
self.view.addSubview(ocrView)
self.metadataDelegates.ocrRecognizerRunnerViewControllerDelegate = self

func recognizerRunnerViewController(_ recognizerRunnerViewController: UIViewController, didObtainOcrResult ocrResult: MBOcrLayout, withResultName resultName: String) {
        self.ocrView.ocrLayoutObtained(ocrResult, withIdentifier: resultName)
    }
```
However, it is not working. It seems that didObtainOcrResult func is not calling? Kindly guide.
Thanks.

Best Regards,
Jovial

**Comment by jcular** [comment]
Hi @Jovial-Ionnex and @miguelpenades ,

you can't use this feature with a demo license, it seems that this note is missing in ios documentation, but you can check [here](https://github.com/blinkid/blinkid-android#-onocrresult-method-in-my-ocrcallback-is-never-invoked-and-all-result-objects-always-return-null-in-their-ocr-result-getters) in the android documentation.

Kind regards,
Jure

**Comment by Jovial-Ionnex** [comment]
Dear @jcular,

Assuming that it can only be used for production license, any chance that we can use the feature to know that the code that we implement is working? Or at the very least provide us with a limited trial license that can use all the features you provided so as to ensure the code implementation is correct?

Thank you.

Best Regards,

Jovial

**Comment by jcular** [comment]
Hey @Jovial-Ionnex,

please contact us at sales@microblink.com.

Kind regards,
Jure
