### ISSUE TITLE
BlinkID can NOT coexist with BlinkOCR

### ISSUE THREAD

**Issue by juliangsp** [BlinkID/blinkid-ios#19]
BlinkOCR SDK can NOT coexist in the same project/workspace with BlinkID SDK. I'm downloading both SDKs via Cocoapods. The **PPCoordinator** class on both SDKs are different and the BlinkOCR is recognized first in Xcode over the BlinkID.

**Comment by Cerovec** [comment]
The best solution is to **just use BlinkID**.

All the features of BlinkOCR are a part of BlinkID, including PPBlinkOcrRecognizer settings. You can use these features in the same way as in BlinkOCR.

As of today, this feature is only available in our feature branch [feature/blinkocr](https://github.com/BlinkID/blinkid-ios/tree/feature/blinkocr).

Please try if this works for you.

**Comment by juliangsp** [comment]
Thanks! I got it working as said. As a reference I used in the Podfile
`pod 'PPBlinkID', :git => 'https://github.com/blinkid/blinkid-ios', :branch => 'feature/blinkocr' `
 but I had to install first **git lfs**.
