### ISSUE TITLE
Breakpoint on camera permission in debug mode

### ISSUE THREAD

**Issue by danielbotka** [BlinkID/blinkid-ios#190]
Hi,

I have an issue, after I initiate my `MBCustomOverlayViewController` and it is the very first time when I try to use the camera, the ask for permission appears just fine. When I press the `OK` button the application stucks with an exception breakpoint and logs the following: `libc++abi.dylib: terminating with uncaught exception of type NSException`. It only happens when I have activated breakpoints and after pressing the continue it stucks with the following: `Thread 1: EXC_BREAKPOINT (code=1, subcode=0x1824ebdd0)`. It seems that there's some kind of assertion happening in the library and can't debug when trying to enable camera permission.

Do you have any ideas how to solve this?

Thanks,
Daniel

**Comment by jcular** [comment]
Hi @danielbotka,

does this happen when you try to run the app in simulator? Could you send us a sample project that recreates the issue? Does this only happen with MBCustomOverlayViewController?
What version of SDK are you using?

Kind regards,
Jure
