### ISSUE TITLE
I can't scan US Driver License.

### ISSUE THREAD

**Issue by FredLopes0203** [BlinkID/blinkid-ios#193]
Hi, I've tried to scan US Driver license using BlinkID sample project.
But nothing happened.

Xcode version: 9.0
BlinkID SDK version: 4.0.1
What are you trying to scan? USDL

**Comment by dCubelic** [comment]
Hi,

New BlinkID 4.1.0 version was released so try updating the SDK.

Also make sure you conform to correct OverlayViewControllerDelegate, whose viewControllerDidFinishScanning will get called when scanning succeeds.

If the problem still prevails, could you please provide us with more information like the iPhone version and the image of drivers license you are trying to scan.

Best regards,
Dominik

**Comment by FredLopes0203** [comment]
Hi, Thank you for your reply.
I've made it to work.
But I've faced another problem.
When I run it as debug, it worked properly but not working when i archive it as AD Hoc.
Would you please let me know what's the problem?
Thanks.

**Comment by dCubelic** [comment]
Hi,

I will need some more information. How exactly does it not work? Does the app crash on start, will the scanning not start, will the scanner not recognize the driver's license or something else?
If there is any, could you please provide us with some log output.

Regards,
Dominik

**Comment by FredLopes0203** [comment]
Hi, It's showing camera view, but not scanning the driver's license.

**Comment by FredLopes0203** [comment]
And additionally, how can i remove the sentence "Using time-limited license", "Position ID card in this Frame"?

**Comment by dCubelic** [comment]
Hi,

did you make sure you are using the current SDK version (4.1.0), and that you made ad hoc archive using the latest version.
Are you using MBUsdlRecognizer, or MBUsdlCombinedRecognizer()?

To hide "Position ID card in this Frame" text you can set showTooltip on settings instance to false, like this:

`        let settings = MBDocumentOverlaySettings()
        settings.showTooltip = false `

"Using time-limited license" warning is present to prevent users going live with demo license key. With production license key, this warning isn't present. But if you really need to remove it you can do so with:
`MBMicroblinkSDK.sharedInstance().showLicenseKeyTimeLimitedWarning = false`

**Comment by jcular** [comment]
Closing issue as inactive, if the problem persists reopen issue.

**Comment by ajboxjr** [comment]
Hello,
Where can I find MBDocumentOverlaySettings in react-native? I would like to remove the overlay lessen confusion while scanning vertical ID's.
