### ISSUE TITLE
Random crash when open the scanner

### ISSUE THREAD

**Issue by Ashtontam** [BlinkID/blinkid-ios#195]
Xcode version: 9.4.1
BlinkID SDK version: 4.1.0
What are you trying to scan? : Malaysia iKad
------------------------------------------------------------------------------------------------------
I was experiencing random crash when open the Malaysia iKad scanner for multiple times. Below is the exception that captured:

invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.

Assertion failure in -[MBCameraCoordinator setScanningRegion:], /opt/jenkins-ios/Executor0/blinkid-ios-framework/core-ios/CommonFramework/Coordinator/MBCameraCoordinator.mm:226
libc++abi.dylib: terminate_handler unexpectedly threw an exception

Any prompt helps will be appreciated as we going to go live for the app soon. Thanks.

**Comment by dCubelic** [comment]
Hi,

I couldn't reproduce your error. Could you please share iPhone version you are using and the code snippet where you initialize the scanning so I could look into the problem some more.

Regards,
Dominik

**Comment by Ashtontam** [comment]
Hi Dominik,

Thank for your quick response, the crash is triggered randomly when I open the iKad scanner, close the scanner and open back the scanner quickly for multiple times. Below is the code snippet I used to call the method:
------------------------------------------------------------------------------------------------------
func openIKadFrontScanner(completion: ((IKad) -> Void)?){
        self.reset()
        self.ikadCompletion = completion
        self.ikadRecognizer = MBIkadRecognizer()
        self.ikadRecognizer?.returnFullDocumentImage = true
        
        let settings = MBDocumentOverlaySettings()
        settings.showTooltip = false
        
        let recognizerCollection = MBRecognizerCollection(recognizers: [self.ikadRecognizer!])
        let documentOverlayViewController = MBDocumentOverlayViewController(settings: settings, recognizerCollection: recognizerCollection, delegate: self)
        
        runRecognizerController(overlayVC: documentOverlayViewController)
    }

func runRecognizerController(overlayVC: MBOverlayViewController){
        
        /** Create recognizer view controller with wanted overlay view controller */
        let recognizerRunnerViewController = MBViewControllerFactory.recognizerRunnerViewController(withOverlayViewController: overlayVC) as! MBRecognizerRunnerViewController
        
        recognizerRunnerViewController.autorotate = true
        recognizerRunnerViewController.supportedOrientations = UIInterfaceOrientationMask(rawValue: UIInterfaceOrientationMask.allButUpsideDown.rawValue)
        
        /** Present the recognizer runner view controller. You can use other presentation methods as well (instead of presentViewController) */
        controller.present(recognizerRunnerViewController as! UIViewController, animated: true, completion: {})
}

------------------------------------------------------------------------------------------------------
I'm using iPhone 6s+ with iOS version 11.4.1. Note that i'm using a presented view to present the scanner controller, not sure this will trigger the crash.

**Comment by jcular** [comment]
Hi @Ashtontam,

we are unable to reproduce this behaviour. Could you send us one of our sample projects with changes that can reproduce this issue?

Kind regards,
Jure
