### ISSUE TITLE
Blink Latest SDK issue when using via pods

### ISSUE THREAD

**Issue by Harsh061** [BlinkID/blinkid-ios#198]
#### Environment

  * Xcode version: 9.4
  * BlinkID SDK version: 4.2.0
  * I am trying to scan UAE Driving License 

### Problem
When I am using BlinkID SDK without pods it works fine. But when I am using BlinkID SDK by pods I am getting error.

### Steps to reproduce
1. I am using pods: 
```
 'PPBlinkID', '~> 4.2.0'
```
Then after implementing all methods and building on simulator I am getting error.

![screen shot 2018-09-04 at 4 56 17 pm](https://user-images.githubusercontent.com/8598792/45029865-aae42a80-b067-11e8-9d37-1cf254213d32.png)
![screen shot 2018-09-04 at 4 56 29 pm](https://user-images.githubusercontent.com/8598792/45029867-aae42a80-b067-11e8-97b0-818b97fc6819.png)

**Comment by danielbotka** [comment]
Hey, we had the same issue, I believe it's related to git-lfs. Try the following in a new directory:

```
pod cache clean --all
brew install git-lfs
git lfs install
git clone <Your Repo>
pod install
```

Hopefully it will solve your issues.

**Comment by jcular** [comment]
This is git-lfs issue, @danielbotka thx for your help. 
Closing issue as solved
