### ISSUE TITLE
Error message flood in debug console while convert MBimage to empty UIImage

### ISSUE THREAD

**Issue by Jovial-Ionnex** [BlinkID/blinkid-ios#199]
Dear MicroBlink,

Our company trying to integrating MicroBlink4.0 with our framework.
`
CGDataProviderCreateDirect: Invalid size = 0
`
`
CGImageCreate: invalid image size: 0 x 0.
`
However, we get the error above flood in debug console when implementing the code below:

`
func recognizerRunnerViewController(_ recognizerRunnerViewController: UIViewController, didOutputDebugImage image: MBImage) {
`
`
                scanDelegate?.scanDebugMetaResults!(image: image.image)
`
`
    }
`

As we trying to convert MBImage to an UIImage where the UIImage is nil.
** Kindly advise how to check the MBImage return is empty before convert it to an UIImage(which is an empty size)

Thanks,
Jovial

**Comment by jcular** [comment]
Hi @Jovial-Ionnex,

we're currently investigating this, in the meantime, may I ask what are you using debug images for, this is not something that should be used in production?

Kind regards,
Jure
