### ISSUE TITLE
 Framework microblink version 4.2.0 architecture not being linked (arm64)

### ISSUE THREAD

**Issue by Jovial-Ionnex** [BlinkID/blinkid-ios#200]
Dear MicroBlink,
`
which is not the architecture being linked (arm64)
`
I hit the issue as picture below when i try to run your sample project with version 4.2.0 which is due to the error above:
<img width="1280" alt="screen shot 2018-09-14 at 5 38 25 pm" src="https://user-images.githubusercontent.com/27202375/45542900-c3153000-b845-11e8-9373-ef4cdb16dd2e.png">

**Kindly advice how to solve this issue.

Thanks,
Jovial

**Comment by culoi** [comment]
Hello @Jovial-Ionnex ,

Please share the method that you used to clone the repo from the Github? 

This error usually happens when a user didn't use clone via git-lfs. 

Regards

**Comment by Jovial-Ionnex** [comment]
Hi culoi,

It solves my problem.

Thanks,
Jovial
