### ISSUE TITLE
Option parser is required to output templating results is unavailable.

### ISSUE THREAD

**Issue by Apple-Zeroa** [BlinkID/blinkid-ios#204]
Dear MicroBlink,

Below are code available in Microblink version 2.18
`
let parser = PPRegexOcrParserFactory(regex: TemplateUtil.SingaporeICRegex)!
        parser.setOptions(options)
        parser.isRequired = true
`

However, option parser.isRequired is removed in MicroBlink version 4.0
This causes the MBRecognizerResultState return in 'didFinishScanningWith method' is Uncertain state. 

So, we fail to get return results when the condition below when some fields in the custom template is not available(as one ID card may have different templates like Singapore work permit PASS):

```
if state == MBRecognizerResultState.valid{
}
```

Kindly advice how to get stable results if some of the fields in custom template may not required.

Thanks,
Zeroa

**Comment by juraskrlec** [comment]
Hi @Apple-Zeroa 

feature is implemented (property is called 'required') and it will be available in next release. Thank you for your time reporting this.

Best regards,
Jura
