### ISSUE TITLE
accessing the image object inside the MBImage causes huge memory leaks

### ISSUE THREAD

**Issue by hasanalbukhari** [BlinkID/blinkid-ios#205]
I am using Xcode Version 9.4.1.

Run your direct api sample app. and modify the implementation as the following:

```
func captureOutput(_ output: AVCaptureOutput, didOutput sampleBuffer: CMSampleBuffer, from connection: AVCaptureConnection) {
        let image = MBImage(cmSampleBuffer: sampleBuffer)
        image.orientation = MBProcessingOrientation.left
        
        image.image // <---- here I am accessing the ui image inside the mbimage.
        if !isPauseRecognition {
            recognizerRunner?.processImage(image)
        }
    }
```

run the app then from the navigators pane show the debug navigator and click on memory. notice the device free memory decreases like hell in few sec then app crashes.

**Comment by jcular** [comment]
Hi @hasanalbukhari,

thx for reporting this, we'll try to squeeze the fix in the next release.

Kind regards,
Jure
