### ISSUE TITLE
Framework version 2.18.2 and 4.x crashes on Xcode 9.4.1 and 10 with out of bounds array

### ISSUE THREAD

**Issue by markshiz** [BlinkID/blinkid-ios#206]
### Describe your environment

  * Xcode version: 10
  * BlinkID SDK version: 2.18.2
  * What are you trying to scan? Anything

### Describe the problem

```swift
let settings = PPSettings()
settings.licenseSettings.licenseKey = '<LICENSE KEY>'

// Doesn't matter if you set up something to scan or not, but as an example        
let qrScanSettings = PPBarcodeRecognizerSettings()
qrScanSettings.scanCode39 = scanTypesToAccept.contains(.code39)
qrScanSettings.scanCode128 = scanTypesToAccept.contains(.code128)
qrScanSettings.scanQR = scanTypesToAccept.contains(.qr)
settings.scanSettings.add(qrScanSettings)

// Program crashes on this line
let coord = PPCameraCoordinator(settings: settings)
```

#### Steps to reproduce:

1. Compile and run the above code on Xcode 10
2. Watch the app crash

*Note*: This code compiles, runs and works in Xcode 9.4.2 using the same framework version

*Console output*
```
2018-09-26 20:51:22.365503-0500 AppName[2040:1062087] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(0x181506d8c 0x1806c05ec 0x18149f750 0x1813cf7f0 0x10c418a68 0x10ed31eb0 0x10c419318 0x1018ddb0c 0x1018dd70c 0x101d957c8 0x101d96fd8 0x101c8c490 0x101c8c568 0x18b27564c 0x18b396870 0x18b27b700 0x18b3b11a8 0x18b2f89e0 0x18b2ed890 0x105a54508 0x101ea59e4 0x101ea5c84 0x18b2ec1d0 0x18bacdd1c 0x18bad02c8 0x18bac9368 0x1814af404 0x1814aec2c 0x1814ac79c 0x1813ccda8 0x1833b2020 0x18b3ec758 0x10123925c 0x180e5dfc0)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

#### Expected results:
1. The framework shouldn't crash my app
2. The above code should run and be able to used to initialize a `PPViewControllerFactory`.

**Comment by jcular** [comment]
Hi @markshiz,

Thx for the report.

I just tested v2.18.2 using our sample app(BlinkID-sample-Swift) with the same settings and everything works. 
This code doesn't cause the crash, please provide a sample that can reproduce the crash.

Kind regards,
Jure

**Comment by jcular** [comment]
@markshiz 
Is this device specific crash, doest this happen only on iPad Air? 
What iOS version are you using on the iPad? 
I just tested that version using iOS 12 and everything runs ok, no crash.

**Comment by markshiz** [comment]
Well, I've now also noticed that the same code crashes on the demo app on `master` running Xcode 9.4.2.  The iPad I have is running iOS 11.4.1.  Model `MNV222LL/A`.

**Comment by markshiz** [comment]
@jcular I have tried setting the license through a file and through base64, both end in the same result.  

I don't think the Xcode version is implicated in this case, as I have reproduced these problems with Xcode 9.4.2 on `master` and `v2.18.2` tags.

**Comment by jcular** [comment]
Hi @markshiz,

Could you send us a zip of the project that recreates it, also can you use this [table](https://igotoffer.com/apple/ipad-model-numbers/) to tell us the exact model of iPad you are using.

Kind regards,
Jure

**Comment by markshiz** [comment]
Here's a link on Amazon: https://www.amazon.com/Apple-iPad-Air-32GB-9-7-Inch/dp/B01M0ASPFK

Do you have an e-mail address to send this project to?

**Comment by jcular** [comment]
Yes you can send by opening a ticket at [zendesk](https://microblink.zendesk.com/hc/en-us/requests/new) , just add a note that this is related to this issue.

**Comment by markshiz** [comment]
That form doesn't allow attachments over 7 MB.

**Comment by markshiz** [comment]
In any case, I am using the code in this repo.  Check out the `v2.18.2` tag, and run the "BlinkID-sample-Swift" example app on an iPad Wifi Air 32 GB in landscape mode.  

I am using a demo license key that I will provide to you through ZenDesk.

**Comment by markshiz** [comment]
Alternatively, if you could provide dysm files for your libraries, then I could provide you a symbolicated trace of my crash.

**Comment by jcular** [comment]
We can't provide you with dysm files. It's important to us that we can reproduce this.

I just ran `BlinkID-sample-swift` app `v2.18.2` on **iPad Air 2** that has **iOS 12**(We don't have an iPad Air 2 with iOS 11.4.1) in landscape, using your license key without an issue. App was built with **Xcode 10**.
Can you send us a stack trace?

This looks more and more like a bizarre issue that might be related to one specific device. 
Correct me if I'm wrong but this happens only on one device and that's the **iPad Air 2 with Wifi only** and model that is written on the back of the device is **A1566**, right? 
No other device has any issue like this?

**Comment by markshiz** [comment]
If you scroll up in this thread you can see the stack trace two other times, but for the sake of completeness here is the (unsymbolicated) trace for the third time.  Again, I can't symbolicate your crash without your dsym files. 

```
2018-09-28 09:52:42.509826-0500 BlinkID-sample-Swift[2468:1269479] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(0x181506d8c 0x1806c05ec 0x18149f750 0x1813cf7f0 0x100b05474 0x101c91eb0 0x100b05cfc 0x101c91eb0 0x100b224a8 0x1004ded90 0x18b121e64 0x18b121a50 0x18b112ce4 0x18b111b18 0x18b19f62c 0x18b115274 0x18b0e25e0 0x18b712b1c 0x18b0e1dd0 0x18b0e1c6c 0x18b0e0afc 0x18bd7684c 0x18b0e01ec 0x18bb5bac8 0x18bca9bf8 0x18b0dfc0c 0x18b0df5a8 0x18b0dc5e0 0x18b0dc330 0x183d08470 0x183d10d6c 0x101c9119c 0x101c9d7cc 0x183d3c878 0x183d3c51c 0x183d3cab8 0x1814af404 0x1814aec2c 0x1814ac79c 0x1813ccda8 0x1833b2020 0x18b3ec758 0x1004e3670 0x180e5dfc0)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Yes, the crash is taking place on  iPad Air 2 --not just one, multiple iPads, one with iOS 12, one with iOS 11.4.2.  Please read this thread for more information.  I've supplied model numbers, Amazon links, etc.

Also, as I've also detailed in this thread, this sample app compiles and runs on an iPhone X, but doesn't recognize barcodes at all.  I know there's a lot of excuses for why that might be the case, but hopefully we can agree that it would be productive for all concerned if you worked on improving the reliability of your library in these basic use cases.  

If you require more information (that I haven't supplied to you already) to fix this problem, then please let me know what it is.

**Comment by jcular** [comment]
Hi @markshiz,

we tried to reproduce this using the same device, but different model of iPad Air 2. Only difference is that we have iPad Air 2 with 16GB. We can't reproduce this issue, do you have any idea or advice how we could reproduce this issue?

Kind regards,
Jure

**Comment by markshiz** [comment]
Your sample Swift app also crashes on the original iPad Air 64 GB [`ME991LL/B`](https://www.amazon.com/Apple-iPad-ME991LL-Tablet-plane/dp/B0108IHCMC) when compiled with Xcode 10.  I don't believe this is a "device specific issue", as you say.

**Comment by markshiz** [comment]
Yes, you are correct, the `preferredLanguages` array is empty on my devices, despite me having selected a preferred locale in the Settings app.  This seems like an iOS bug, but in any case, seems like you should have a work around when these cases surface.  

Is there any way you could release a 2.18.x release with this fix?  We are currently a paying customer and are looking for the cleanest migration path to Xcode 10 for right now as we are in a time crunch.

**Comment by jcular** [comment]
I understand but we don't plan on making any updates for version 2.18.x.

I found a quick workaround, let us know if this works for you. I couldn't find if this is something that belongs to the private API so Apple should be ok with this too:
```
// Add this before initialising PPCameraCoordinator.
if Locale.preferredLanguages.isEmpty {
    UserDefaults.standard.set(["en"], forKey: "AppleLanguages")
}
```

I hope this will work for you but I suggest that you switch to new API. You can contact us if you need any help with the migration. 

Kind regards,
Jure

**Comment by markshiz** [comment]
Hello Jure, thank you for the work around code above.  Indeed, this does seem to modify the `preferredLanguages`.  Thank you for your help.
