### ISSUE TITLE
Example code for scanning license plates

### ISSUE THREAD

**Issue by dindin4** [BlinkID/blinkid-ios#207]
Can anyone provide an example of how you extract license plate information? I have already tried using the MBLicensePlatesParser but it doesn't seem to work. There is no documentation or examples which explain this so would be good to see something. This is what I have at the moment.
  
        let settings = MBDocumentOverlaySettings()
        lpParser = MBLicensePlatesParser()
        parserGroupProcessor = MBParserGroupProcessor(parsers: [lpParser])
        blinkInputRecognizer = MBBlinkInputRecognizer(processors: [parserGroupProcessor!])

        let recognizerList = [self.blinkInputRecognizer!]
        let recognizerCollection : MBRecognizerCollection = MBRecognizerCollection(recognizers: recognizerList)
        
        /** Create your overlay view controller */
        let documentOverlayViewController : MBDocumentOverlayViewController = MBDocumentOverlayViewController(settings: settings, recognizerCollection: recognizerCollection, delegate: self)
        
        /** Create recognizer view controller with wanted overlay view controller */
        let recognizerRunnerViewController : UIViewController = MBViewControllerFactory.recognizerRunnerViewController(withOverlayViewController: documentOverlayViewController)
        
        /** Present the recognizer runner view controller. You can use other presentation methods as well (instead of presentViewController) */
        present(recognizerRunnerViewController, animated: true, completion: nil) `

    func documentOverlayViewControllerDidFinishScanning(_ documentOverlayViewController: MBDocumentOverlayViewController, state: MBRecognizerResultState) {
        
        // this is done on background thread
        // check for valid state
        if state == MBRecognizerResultState.valid {
            
            // first, pause scanning until we process all the results
            documentOverlayViewController.recognizerRunnerViewController?.pauseScanning()
            
            DispatchQueue.main.async(execute: {() -> Void in
                // All UI interaction needs to be done on main thread
                print("OCR results are: \(self.rawParser!.result.rawText)")
                print("OCR License plate result: \(self.lpParser.result.licensePlate ?? "")")
                documentOverlayViewController.recognizerRunnerViewController?.resumeScanningAndResetState(true)
            })
        }
    }

**Comment by jcular** [comment]
Hi @dindin4,

this looks ok, but the license plate parser is primarily designed for german license plates, so that might be the issue.
What license plates are you trying to scan?

Kind regards,
Jure
