### ISSUE TITLE
Error when installing PPBlinkID Pod

### ISSUE THREAD

**Issue by ApplantaDev** [BlinkID/blinkid-ios#210]
**I get the following error when trying to install the PPBlinkID Pod. Any solution for this issue?**

[!] Error installing PPBlinkID
[!] /opt/local/bin/git clone https://github.com/BlinkID/blinkid-ios.git /var/folders/pr/wq45mb0x75q32h47rhmxdrhw0000gn/T/d20181016-12936-3enov8 --template= --single-branch --depth 1 --branch v4.1.0

Cloning into '/var/folders/pr/wq45mb0x75q32h47rhmxdrhw0000gn/T/d20181016-12936-3enov8'...
Note: checking out '0777aaf04d050b80afbdb9210b5fb4b96675639e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

error: git-lfs smudge -- 'MicroBlink.framework/MicroBlink' died of signal 11
error: external filter git-lfs smudge -- %f failed 139
error: external filter git-lfs smudge -- %f failed
fatal: MicroBlink.framework/MicroBlink: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by jcular** [comment]
Hi @ApplantaDev,

I suggest that you try this:
```
pod cache clean --all
pod install
```

Kind regards,
Jure

**Comment by SikanderZeb** [comment]
@jcular didn't help.

**Comment by jcular** [comment]
Hi @SikanderZeb,

sorry for a late reply, could you try this:
```
git lfs install --skip-smudge

pod install

git lfs install --force
```

If that fails, try this again but clean pod cache before.
You can also try installing the framework manually, follow our instructions [here](
https://github.com/BlinkID/blinkid-ios#integration-without-cocoapods).

Kind regards,
Jure

**Comment by enricohessel** [comment]
I have a similar/same issue

`Enricos-MacBook-Pro:uze-drive rikco$ pod cache clean --all
Enricos-MacBook-Pro:uze-drive rikco$ pod install
Analyzing dependencies
Downloading dependencies
Installing PPBlinkID (4.4.0)

[!] Error installing PPBlinkID
[!] /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git clone https://github.com/BlinkID/blinkid-ios.git /var/folders/54/sycl18797ls58jr8mtky7sp00000gn/T/d20181127-56957-s82d8d --template= --single-branch --depth 1 --branch v4.4.0

Cloning into '/var/folders/54/sycl18797ls58jr8mtky7sp00000gn/T/d20181127-56957-s82d8d'...
Note: checking out '473c705c49db2a3c60136fd8b915018eae4683a8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

git-lfs smudge --skip -- 'MicroBlink.framework/MicroBlink': git-lfs: command not found
error: external filter git-lfs smudge --skip -- %f failed -1
error: external filter git-lfs smudge --skip -- %f failed
fatal: MicroBlink.framework/MicroBlink: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'`

**Comment by jcular** [comment]
Hi @enricohessel,

do you have git-lfs installed?
"git-lfs smudge --skip -- 'MicroBlink.framework/MicroBlink': **git-lfs: command not found**"
You need to have git-lfs installed to add our framework using cocoapods.

Kind regards,
Jure

**Comment by enricohessel** [comment]
Yes, at least I thought I have but see by yourself

<img width="941" alt="bildschirmfoto 2018-11-27 um 09 48 04" src="https://user-images.githubusercontent.com/12894210/49069637-06b6ed80-f22a-11e8-947a-63ea0b947856.png">

**Comment by jcular** [comment]
@enricohessel 
What happens when you run `git lfs --version`, do you get any output.

**Comment by enricohessel** [comment]
@jcular 
$ git lfs --version
git-lfs/2.6.0 (GitHub; darwin amd64; go 1.11.2)

**Comment by jcular** [comment]
@enricohessel 
did you run `git lfs install` after installation?

**Comment by enricohessel** [comment]
Yes, like in the screenshot above  `git lfs install` and `git-lfs install` both result in `Git LFS initialized`

**Comment by jcular** [comment]
Sorry I didn't notice you already ran the command.
This is really strange, what bothers me is that cocoapods says `git-lfs command not found` but you have it installed, maybe restarting terminal or mac might help?

**Comment by enricohessel** [comment]
I already did :-/ yes its strange for me to, don´t know if it´s a cocapods bug on mojave..

**Comment by jcular** [comment]
Have you tried cloning our repo?
Does the same thing happen if you try that?

**Comment by enricohessel** [comment]
Any news here? Does anybody has the same issue? Unfortunately it is still not working with cocoapods.

**Comment by jcular** [comment]
Hi @enricohessel,
you can try to install BlinkID v4.6.0 using cocaopods, since v4.6.0 we're no longer using git-lfs.
Kind regards,
Jure

**Comment by enricohessel** [comment]
Thx! worked!
