### ISSUE TITLE
failed to transfer anther View controller after obtained data from ID .

### ISSUE THREAD

**Issue by AbdoElabd** [BlinkID/blinkid-ios#214]
### [READ] Step 1: Are you in the right place?

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with BlinkID tag.
  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Microblink support](https://help.microblink.com/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: _____
  * BlinkID SDK version: _____
  * What are you trying to scan? _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by jcular** [comment]
Please provide more info.

Kind regards,
Jure

**Comment by AbdoElabd** [comment]
i needed to add
*let* fullResultViewController = FullResultViewController()

documentVerificationOverlayViewController.present(fullResultViewController,
animated: *true*)

insteaded

let alertController: UIAlertController = UIAlertController.init(title:
title, message: message, preferredStyle: UIAlertControllerStyle.alert)

            let okAction: UIAlertAction = UIAlertAction.init(title:
"OK", style: UIAlertActionStyle.default,
                                                             handler:
{ (action) -> Void in

self.dismiss(animated: true, completion: nil)
            })
            alertController.addAction(okAction)

documentVerificationOverlayViewController.present(alertController,
animated: true, completion: nil)



to transfer data another viewController to show data to client such as
image that attached.
*Regards,*
*Abdelrahman Elabd*


*T.*    + (20) 01060615066
*E.    **e <hend.omar@its.ws>ngabdoelabd@gmail.com <ngabdoelabd@gmail.com>*

**Comment by jcular** [comment]
Hi,

our SDK doesn't contain view controller to present results, you have to implement that yourself, we provide framework to scan documents and extract data. Here we use the alert view controller in a sample app. `MBMRTDCombinedRecognizer` contains `MBMRTDCombinedRecognizerResult`, once the scanning is successful you can extract the data from `MBMRTDCombinedRecognizerResult` contained inside `MBMRTDCombinedRecognizer `.

Kind regards,
Jure

**Comment by AQElementary** [comment]
@jcular can you please tell me why the demo example of swift is not running with me i dont know why its give me strange errors ?
