### ISSUE TITLE
Remove Git LFS as an installation requirement

### ISSUE THREAD

**Issue by davidperrenoud** [BlinkID/blinkid-ios#215]
Could you provide an installation option that doesn't require Git LFS? The absence of `MicroBlink.framework/MicroBlink` can produce some confusing error messages when building on computers or continuous integration tools where Git LFS is not available.

For example something like this in `PPBlinkID.podspec`:
```ruby
s.source = { 
  :http => 'https://github.com/BlinkID/blinkid-ios/releases/download/v4.3.0/blinkid-ios_v4.3.0.tar.gz',
  :sha1 => 'e132a52ca79041aeb1e7249be7bce4cecd7d8adc'
}
```

**Comment by juraskrlec** [comment]
Hi @davidperrenoud 

unfortunately, due to MicroBlink size and git limit, we can't provide an installation option that doesn't require Git LFS.

Best regards,
Jura

**Comment by davidperrenoud** [comment]
Even with something like the HTTP example I provided?

**Comment by yaakovgamliel** [comment]
To my understanding @davidperrenoud is asking for an option a not to completely remove the need for LFS

**Comment by davidperrenoud** [comment]
Actually, I do think using HTTPS in the podspec would be a better option overall than depending on Git LFS when doing `pod install`.

The file itself can stay on Git (using Git LFS), as GitHub will automatically provide the Git LFS files when generating the .tar.gz file. What will change is that the application developers don't need to have Git LFS installed.

**Comment by jcular** [comment]
Hi @davidperrenoud,

I agree, we'll switch to using HTTPS in podspec with the the next version, hopefully without any issues.

Kind regards,
Jure
