### ISSUE TITLE
Random Crash after document recognition and open up new recognition controller

### ISSUE THREAD

**Issue by enricohessel** [BlinkID/blinkid-ios#220]
* Xcode version: Version 10.1 (10B61)
  * BlinkID SDK version: 4.3.0
  * What are you trying to scan? german ID front + back and german/EU Drivers license front back

After a successful scan, I open up a new setup scanning viewcontroller with documentsOverlayVC an scan related recognizers.
Randomly the app crashes after a new scanner was opend.

If i´m not wrong, its always the same symbols

#0	0x00000001013739d8 in ___lldb_unnamed_symbol19806$$MicroBlink ()
#1	0x0000000101370fa4 in ___lldb_unnamed_symbol19706$$MicroBlink ()
#2	0x000000010117bd9c in ___lldb_unnamed_symbol11897$$MicroBlink ()
#3	0x0000000103fa3840 in _dispatch_call_block_and_release ()
#4	0x0000000103fa4de4 in _dispatch_client_callout ()
#5	0x0000000103face88 in _dispatch_lane_serial_drain ()
#6	0x0000000103fadb7c in _dispatch_lane_invoke ()
#7	0x0000000103fb7c18 in _dispatch_workloop_worker_thread ()
#8	0x00000001920ca0f0 in _pthread_wqthread ()
#9	0x00000001920ccd00 in start_wqthread ()
Enqueued from com.microblink.frame.analysis (Thread 10) Queue : com.microblink.frame.analysis (serial)
#0	0x0000000103fa9c24 in dispatch_async ()
#1	0x000000010117e1e0 in ___lldb_unnamed_symbol11998$$MicroBlink ()
#2	0x0000000103fb3848 in _dispatch_lane_barrier_sync_invoke_and_complete ()
#3	0x000000010117b870 in ___lldb_unnamed_symbol11893$$MicroBlink ()
#4	0x000000019857bce8 in __47-[AVCaptureVideoDataOutput _updateRemoteQueue:]_block_invoke ()
#5	0x0000000195aa3dfc in __FigRemoteOperationReceiverCreateMessageReceiver_block_invoke ()
#6	0x0000000195ac14cc in __FigRemoteQueueReceiverSetHandler_block_invoke.2 ()
#7	0x0000000103fa4de4 in _dispatch_client_callout ()
#8	0x0000000103fa81e0 in _dispatch_continuation_pop ()
#9	0x0000000103fbacac in _dispatch_source_invoke ()

**Comment by jcular** [comment]
Hi @enricohessel,

Could you provide more info, it would help a lot in recreating this issue if you could provide modified sample app from this repository that can cause  the crash?
Do you dismiss the first recognizer runner view controller that was used to scan the document, or you just present another recognizer runner view controller on top of the existing one?

Kind regards,
Jure

**Comment by enricohessel** [comment]
@jcular 

I have a private func which initialized a new MBDocumentOverlayViewController with new recognizer(s) and return recognizerRunneViewController   = MBViewControllerFactory.recognizerRunnerViewController(withOverlayViewController: overlayViewController)

This recognizerRunneViewController got pushed onto a navigationviewcontroller as setViewControllers:[recognizerRunneViewController] (only one viewcontroller) so that I get a transition to a new controller (because of UX).

I guess I have to reset something on the recognizerRunneViewController (I already stopped the scan process and pause the camera)

**Comment by jcular** [comment]
Hi @enricohessel,

do you create a new recognizer runner collection too, or do you reuse it?
Could you send us one of our sample apps that we can use to reproduce this.

If I understand correctly, you do the following:

 * create recognizer runner view controller
 * add it to the current hierarchy by calling show on current navigationViewController
 * when this recognizer runner finishes scanning with result you create another recognizer runner view controller 
 * on the navigationViewController you set it using `setViewControllers [recognizerRunneViewController]`
 * crash?
Is that correct?

Kind regards,
Jure

**Comment by enricohessel** [comment]
I changed the way I scan the documents and now I only use a single controller to scan 4 documents. So unfortunately I can not answer your question anymore, sorry.
