### ISSUE TITLE
HelpImageView should fit VerificationSubview

### ISSUE THREAD

**Issue by enricohessel** [BlinkID/blinkid-ios#222]
I would like to use a full size image on the helpImageView but there is some bottom size missing. Maybe some error with the constraints?

![img_0002](https://user-images.githubusercontent.com/12894210/49089568-1e0ece80-f25c-11e8-93cc-84c061482d7d.PNG)

`for view in self.view.subviews {
            if view is MBDocumentVerificationSubview {
                let aView: MBDocumentVerificationSubview = view as! MBDocumentVerificationSubview
                aView.helpLabel.text            = "TEST"
                //aView.helpImageView.image       = StyleKit.imageOfCvScanDone(imageSize: aView.frame.size)
                aView.helpImageView.contentMode = .center
                NSLog("ImageView: %@", aView.helpImageView)
                NSLog("View:      %@", aView)
                aView.animateHelp()
            }
        }`

**Comment by jcular** [comment]
Hi @enricohessel,

it's not an error, the intended UI is a text label with a message and an image below it. 
UIImageView has bottom constraint to the bottom container view, UIImageView is not centred vertically in the container view, this was our intent. 

Kind regards,
Jure

**Comment by enricohessel** [comment]
Would be great if the developer gets more freedom for customization because its already a pretty good base. (more public access to the ui-elements)

Thx for your support!
