### ISSUE TITLE
ignoring file /Users/abdelrahmanelabd/Desktop/DEMOOFNATIVE/Pods/PPBlinkID/MicroBlink.framework/MicroBlink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64)Pods/PPBlinkID/MicroBlink.framework/MicroBlink

### ISSUE THREAD

**Issue by AbdoElabd** [BlinkID/blinkid-ios#223]
### [READ] Step 1: Are you in the right place?

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with BlinkID tag.
  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Microblink support](https://help.microblink.com/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: _____
  * BlinkID SDK version: _____
  * What are you trying to scan? _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by AbdoElabd** [comment]
I uses pod install

**Comment by fatinWasta** [comment]
+1 , Happening with me too, no solution yet.
I think this is happening cause of opening project in Xcode 10? In Xcode 9 it used to work fine.. What Xcode are you using though..? @AbdoElabd

**Comment by jcular** [comment]
Hi @AbdoElabd, @fatinWasta,

have you installed git-lfs?
This looks like a git-lfs related issue.
If you haven't you can install it with
```
brew install git-lfs
git-lfs install
```
after that, you'll need to clean pod cache
`pod cache clean --all`
and install again.
`pod install`
Let me know if this helps.

And please when reporting issues fill out the form, don't write the whole issue in the title.

Kind regards,
Jure

**Comment by fatinWasta** [comment]
Yo man, it worked, seems git-lfs was not installed in my Mac. 
Thanks lot. 👍🏻

**Comment by serkangunes** [comment]
I am still getting same error even after following the instructions @jcular sent. :(

**Comment by jcular** [comment]
@serkangunes how did you install our framework, manually or using cocoapods?

**Comment by serkangunes** [comment]
Using cocoapods

**Comment by serkangunes** [comment]
I have installed the git-lfs using brew then added pod definition into the pod file.
I have done `pod install` it has successfully installed the pods. 
I started getting this error.
However I realised that I forgot to run `git-lfs install`
so done that. And run `pod cache clean --all
pod install`
However I can't get it running I am still getting the same error.

**Comment by serkangunes** [comment]
Apologies after deleting the pods directory and trying again this time it worked.

**Comment by jcular** [comment]
Hi @serkangunes,

thanks for sharing what finally made it work for you, this will be helpful for others with the same issue if other suggestions fail.

Kind regards,
Jure

**Comment by maaalex** [comment]
Thank you all, as there is no conclusive post - here's what to do ;)
1. install git-lfs
2. **delete pods folder**
3. pod cache clean
4. pod install
