### ISSUE TITLE
Florida state DL not scanning

### ISSUE THREAD

**Issue by yaakovgamliel** [BlinkID/blinkid-ios#224]
Hi,
I have been having issues scanning drivers licenses in Florida, I see that the barcode has some printing issues, is there any way to try scanning the front of the license instead in this cases.

**Comment by jcular** [comment]
Hi @yaakovgamliel,

we currently don't support OCR of the front side of the Florida DL, but we are working on that. Currently we read the data from the barcode on the back. You can use MBDocumentFaceRecognizer to extract the face image and the document image but that's it. Unfortunately if the barcode is badly printed there's not much we can do. If you have this barcode you can try closing in on the barcode, scanning the barcode in landscape or something similar. Might be that the barcode is just dense and the camera just needs to be closer.

Kind regards,
Jure
