### ISSUE TITLE
Date of birth is incorrectly returned by MBUsdlRecognizerResult

### ISSUE THREAD

**Issue by kgut** [BlinkID/blinkid-ios#229]
XCode version 10.1 (10B61)
BlinkID version  4.6.0
Device: Multiple models and iOS versions

Language: Polish/English
Region: Poland

When processing  AAMVA string using direct API I'm getting wrong date of birth.
According to AAMVA standard Date for Birth (DBB)field has format MMDDYYYY which is default format for US.
There are two possible outcomes of processing aamva
1. DBB03071975 is decoded to 07031975. This is wrong because day and month values are exchanged  
2. DBB12161983 is decoded to 12161983. This is correct.

Because recogniser returns date in two different formats it cannot be reliably used for data processing.

```
let aava = "USER_DETAILS.....DBB03071975...."
let recognizer = MBUsdlRecognizer()
let runner = MBRecognizerRunner(recognizerCollection: MBRecognizerCollection(recognizers: [recognizer]))
runner.processString(aamva)
if recognizer.result.resultState == .valid {
print(recognizer.result.getField(.DateOfBirth)) // Prints 07031975 instead of  03071975
}
```

**Comment by dCubelic** [comment]
Hi,

I tried reproducing your error but I did not manage to.
Parsing "...DBB03071975..." returned "03071975" as .DateOfBirth value, and parsing "...DBB12161983..." returned "12161983".

Could you maybe send me the whole strings you are trying to parse, so I could maybe reproduce your error?

Best regards,
Dominik

**Comment by Cerovec** [comment]
Hi @kgut,

Can we ask you to double-check if this is still an issue with v5.3?

Thanks,
Jurica.

**Comment by Cerovec** [comment]
Hi @kgut,

We'll close this issue in the meantime and if this is still an issue, please reopen it.

Thanks,
Jurica.
