### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by Vitalii-Gozhenko** [BlinkID/blinkid-ios#230]
Is there plans to add an installation option using Swift Package Manager?

**Comment by jcular** [comment]
Hi Magnat12,

currently, we don't have a plan to add it to Swift Package Manager, but it's available through cocoapods. I'll have to see with the rest of the team if adding it to Swift Package Manager is an option.

Kind regards,
Jure

**Comment by TCvetkovic** [comment]
Hi,

We have added support for Swift Package Manager in [BlinkID v5.9.0](https://github.com/BlinkID/blinkid-ios/releases/tag/v5.9.0).
