### ISSUE TITLE
'MicroBlink/MicroBlink.h' file not found inside the Library?

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [BlinkID/blinkid-ios#232]
Hi,

I have integrate the blinkid-iOS pod inside my App it's working fine, No error are there. But Now I want to integrate the blinkid-iOS inside my Custom Library. I have integrate same step as given for library.

I got the issue : 'MicroBlink/MicroBlink.h' file not found inside the library file.

![screen shot 2019-02-15 at 5 08 23 pm](https://user-images.githubusercontent.com/17870723/52854434-65fb0e80-3144-11e9-92f8-37df83c32ff3.png)

Please help me. How to add the blinkID library inside My Current library. 

Thanks.

**Comment by jcular** [comment]
Hi @kiritnim,

please check how BlinkID is integrated inside BlinkID-ui, you can see how the project is setup.
If you plan to manage it using cocaopods podspec you can see in our project how we added BlinkID as a dependency in podspec.

Kind regards,
Jure

**Comment by kiritnim** [comment]
> Hi @kiritnim,
> 
> please check how BlinkID is integrated inside BlinkID-ui, you can see how the project is setup.
> If you plan to manage it using cocaopods podspec you can see in our project how we added BlinkID as a dependency in podspec.
> 
> [BlinkID-ui-ios](https://github.com/BlinkID/blinkid-ui-ios)
> 
> Kind regards,
> Jure

But I want to integrate blinkID pod or BlinkID SDK inside my Custom Library.

**Comment by jcular** [comment]
> > Hi @kiritnim,
> > please check how BlinkID is integrated inside BlinkID-ui, you can see how the project is setup.
> > If you plan to manage it using cocaopods podspec you can see in our project how we added BlinkID as a dependency in podspec.
> > [BlinkID-ui-ios](https://github.com/BlinkID/blinkid-ui-ios)
> > Kind regards,
> > Jure
> 
> But I want to integrate blinkID pod or BlinkID SDK inside my Custom Library.

Blinkid-ui-ios is a dynamic framework that has blinkid framework integrated, you can check out the source of blinkid-ui-ios and see how the project is setup, and based on its settings setup your own project. You can use that as a "template" to setup your own custom library.

**Comment by kiritnim** [comment]
> > > Hi @kiritnim,
> > > please check how BlinkID is integrated inside BlinkID-ui, you can see how the project is setup.
> > > If you plan to manage it using cocaopods podspec you can see in our project how we added BlinkID as a dependency in podspec.
> > > [BlinkID-ui-ios](https://github.com/BlinkID/blinkid-ui-ios)
> > > Kind regards,
> > > Jure
> > 
> > 
> > But I want to integrate blinkID pod or BlinkID SDK inside my Custom Library.
> 
> Blinkid-ui-ios is a dynamic framework that has blinkid framework integrated, you can check out the source of blinkid-ui-ios and see how the project is setup, and based on its settings setup your own project. You can use that as a "template" to setup your own custom library.

The Blinkid-ui-ios  framework setup insidemy project it's working fine. But when I setup it inside my library it's give error.

**Comment by jcular** [comment]
Are you trying to set up a static or dynamic framework?

**Comment by kiritnim** [comment]
> Are you trying to set up a static or dynamic framework?

Yes. I try to add the library and added successfully. In auto suggestion is also available, but after run the below error getting,

![screen shot 2019-02-18 at 1 38 29 pm](https://user-images.githubusercontent.com/17870723/52936462-320d2c80-3382-11e9-9f72-90161fe1e5ba.png)

**Comment by jcular** [comment]
If you are adding blinkid with cocapods, after running `pod install` and opening YourLibrary.xcworkspace it should work out of the box.

**Comment by kiritnim** [comment]
> If you are adding blinkid with cocapods, after running `pod install` and opening YourLibrary.xcworkspace it should work out of the box.

Hi,

I create one project name as one.xcodeProj,

Now inside the project, I added the custom library name as two.xcodeProj, Now I want to add blinkID custom library project.

I also try to installed pod but there is same issue.

**Comment by jcular** [comment]
What's your framework search path?
Make sure that your framework search is correct.

**Comment by kiritnim** [comment]
> What's your framework search path?
> Make sure that your framework search path in build settings is correct.

FrameWork path : drag and drop the Microblink.framework

**Comment by jcular** [comment]
Can you share a minimal xcode project that can demonstrate your issue?
That way we can see what's wrong with the setup.
