### ISSUE TITLE
MBUsdlCombinedRecognizer documentDataMatch always returns true

### ISSUE THREAD

**Issue by narendra-r** [BlinkID/blinkid-ios#233]
### [READ] Step 1: Are you in the right place?

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with BlinkID tag.
  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Microblink support](https://help.microblink.com/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1 (10B61)
  * BlinkID SDK version: '4.6.0'
  * What are you trying to scan? USDL Combined

### [REQUIRED] Step 3: Describe the problem
MBUsdlCombinedRecognizerResult documentDataMatch property always returns true on scan completion. 

#### Steps to reproduce:

Scan different person's USDL back document on completion of front scan of USDL, then in results we always getting documentDataMatch property as true.

#### Relevant Code:
```
//setup recognizer
let usdlRecognizer = MBUsdlCombinedRecognizer()
usdlRecognizer.returnFullDocumentImage = true
usdlRecognizer.scanUncertain = false

// delegate
func documentVerificationOverlayViewControllerDidFinishScanning(_ documentVerificationOverlayViewController: MBDocumentVerificationOverlayViewController, state: MBRecognizerResultState) {
        // this is done on background thread
        // check for valid state
        if state == MBRecognizerResultState.valid {
            // first, pause scanning until we process all the results
            documentVerificationOverlayViewController.recognizerRunnerViewController?.pauseScanning()
            
            DispatchQueue.main.async(execute: {() -> Void in
                documentVerificationOverlayViewController.dismiss(animated: false, completion: {
                    
                })
                
                self.parseResult(recognizer: self.recognizer)
                // Supporting only USDL combine here now
                if let recognizer = self.recognizer as? MBUsdlCombinedRecognizer, recognizer.result.documentDataMatch == true {
                 // *********** Its always coming here even with mismatched cards ****************
                   print("both sides of cards matched.. success")
                } else {
                        showAlert(title: "Error", message: "Data not matched", vc: self, okAction: {
                            
                        })
                }
            })
        }
    }
```

**Comment by jcular** [comment]
Hi @narendra-r,

that's because the `MBUSDLCombinedRecognizer` scans only the face and document image on the front. It doesn't read the fields, all other fields are read from the pdf417 barcode on the backside, so it can't compare front and back side results.

Kind regards,
Jure

**Comment by narendra-r** [comment]
Hi Jure,  many thanks for your response.  I have been reading your documentation.  Specifically: [http://blinkid.github.io/blinkid-ios/Protocols/MBCombinedRecognizerResult.html#/c:objc(pl)MBCombinedRecognizerResult(py)documentDataMatch](http://blinkid.github.io/blinkid-ios/Protocols/MBCombinedRecognizerResult.html#/c:objc(pl)MBCombinedRecognizerResult(py)documentDataMatch). 

As you will see, this document clearly suggests that BlinkID supports data comparison of USA Drivers license front and back.  This has now become an important expectation for my client.  Can you please look at this again and let me know whether if it is supported - or if it will be fixed?  Thanks again for your help!

**Comment by jcular** [comment]
Unfortunately we don't currently support data matching on front and back side of usdl using USDL combined recognizer.
