### ISSUE TITLE
Can we change the Glare detection Percentage from 10% to any other number?

### ISSUE THREAD

**Issue by prasoonpuri12** [BlinkID/blinkid-ios#239]
I am using your Microblink 4.8.0 version for iOS and I am facing difficulty in Scanning the softcopy of the document when I put my application in debugging mode it was giving me "Skipping processing of this group, determined glare as more than 10%", can I manipulate this value somehow by any means?

**Comment by jcular** [comment]
Hi @prasoonpuri12,

you can turn glare detection on/off on the recognizer by setting [detectGlare](http://blinkid.github.io/blinkid-ios/Protocols/MBGlareDetection.html#/c:objc(pl)MBGlareDetection(py)detectGlare) property.

Kind regards,
Jure
