### ISSUE TITLE
MBDetectionDots are also coming at the Header Part of the screen!!!!

### ISSUE THREAD

**Issue by prasoonpuri12** [BlinkID/blinkid-ios#240]
I am using your Microblink 4.8.0 for my application in iOS application and I had made custom Overlay screen for the Camera Overlay , on which I had confirmed your delegate "MBDetectionRecognizerRunnerViewControllerDelegate" and implemented method "- (void)recognizerRunnerViewController:(nonnull UIViewController<MBRecognizerRunnerViewController> *)recognizerRunnerViewController didFinishDetectionWithDisplayablePoints:(MBDisplayablePointsDetection *)displayablePoints" and also declared the property and passed the Frame Size as 
@property(nonatomic,strong)MBDotsResultSubview* dotSubview;

"  _dotSubview = [[MBDotsResultSubview alloc] initWithFrame:self.view.frame];
    [self.view addSubview:_dotSubview];"

So when I am scanning the passport, OCR dots are coming Over the MRZ but along with that it is also getting visible at the header part. How can I control that I had passed different values to the frame but unfortunately it is not getting rectified.

I also checked your Sample app from the App Store .."BlinkID"  , It is also behaving in the same way. So any thoughts on that?

**Comment by juraskrlec** [comment]
Hi @prasoonpuri12 

you should set [Scanning Region](http://blinkid.github.io/blinkid-ios//Classes/MBCustomOverlayViewController.html#/c:objc(cs)MBCustomOverlayViewController(py)scanningRegion)

Best regards.
Jura
