### ISSUE TITLE
Missing dSYMs

### ISSUE THREAD

**Issue by yaakovgamliel** [BlinkID/blinkid-ios#243]
Hi,
I'm using Bugsnags services and their console reports that the symbols for the Microblink SDk are missing, they provide methods for uploading the symbols but I can't find the location for  the Microblink ones.
https://docs.bugsnag.com/platforms/ios/symbolication-guide/

**Comment by yaakovgamliel** [comment]
Hi,
The app is crashing all over the place we need to be able to upload the symbols file in order to handle this, if there is not such file for the SDK please replay, we are a paying customer please instruct if we should use another support channel

**Comment by culoi** [comment]
Hello @yaakovgamliel
