### ISSUE TITLE
Getting MBUnitedArabEmiratesIdBackRecognizerResult.fullDocumentImage?.image nil sometime.

### ISSUE THREAD

**Issue by yo2bh** [BlinkID/blinkid-ios#244]
### Step 1: Are you in the right place?

  * I am using Microblink SDK iOS version 4.4.0. When I launch the application and scan the UAE ID. The MBUnitedArabEmiraresIdBackRecognizerResult.fullDocumentImage?.image gives nil.
  *  This behavior does not continue, sometimes it gives the value of the image but sometimes fails to give the image value.

### Step 2: Describe your environment

  * Xcode version: 10.1
  * BlinkID SDK version: 4.4.0
  * What are you trying to scan? Emirates ID

### Step 3: Describe the problem
* The MBUnitedArabEmiraresIdBackRecognizerResult.fullDocumentImage?.image gives nil.
* This behavior does not continue, sometimes it gives the value of the image but sometimes fails to give the image value.

#### Steps to reproduce:

1. Launch application scans the front emirates Id image.
2. Scan the back page of Emirates Id

Sometimes the back image object is nil. To get the image back I have reset the camera and start scanning again the back page, but it will take time to scan the image.

#### Relevant Code:

```
  func recognizerRunnerViewController(_ recognizerRunnerViewController: UIViewController & MBRecognizerRunnerViewController, didFinishScanningWith state: MBRecognizerResultState) {
    
    DispatchQueue.main.async {[weak self] in
      if state == .valid {
        recognizerRunnerViewController.pauseScanning()
        recognizerRunnerViewController.playScanSuccessSound()
        if self?.currentEmiratesIdSide == .frontSide, self?.emiratesIdFrontSide.result.resultState == .valid {
          let frontSideRecognizerResult = self?.emiratesIdFrontSide.result
          self?.scanAreaCentralLabel.text = ScanEmiratesIdStrings.info.backSidePlaceholder
          self?.frontSideModel = ScanEmiratesIdParser.getEmiratesIdFrontSideData(frontSideRecognizerResult!)
          self?.switchToScanningBackSide()
        }
        if self?.currentEmiratesIdSide == .backSide, self?.emiratesIdBackSide.result.resultState == .valid {
          let backSideRecognizerResult = self?.emiratesIdBackSide.result
          // Sometime I got the back page image object nil
          if backSideRecognizerResult?.fullDocumentImage?.image == nil {
            recognizerRunnerViewController.resumeScanningAndResetState(true)
            return
          }
          self?.backSideModel = ScanEmiratesIdParser.getEmiratesIdBackSideData(backSideRecognizerResult!)
          // Navigate to the next view controller.
        }
      }
      recognizerRunnerViewController.resumeScanningAndResetState(true)
    }
  }

  func switchToScanningBackSide() {
    currentEmiratesIdSide = .backSide
    emiratesIdBackSide = MBUnitedArabEmiratesIdBackRecognizer()
    emiratesIdBackSide.returnFullDocumentImage = true
    let recognizerList = [emiratesIdBackSide] as [MBRecognizer]
    let recognizerCollection: MBRecognizerCollection = MBRecognizerCollection(recognizers: recognizerList)
    self.reconfigureRecognizers(recognizerCollection)
  }
```
How we can resolved this issue? Please guide. Thanks in advance :)

**Comment by juraskrlec** [comment]
Hi @yo2bh 

Are you still not getting sometimes back image?

Best regards,
Jura

**Comment by Cerovec** [comment]
Hi @yo2bh,

We're closing this as this is inactive, but let us know if you want to reopen the issue.

Best,
Jurica.
