### ISSUE TITLE
USDL no field for Issuing Jurisdiction Name, Issuer Identification Number and Document Discriminator

### ISSUE THREAD

**Issue by MOhsain** [BlinkID/blinkid-ios#245]
In Android..
i'm using this code for scanning Canada Driver License but i can not get full data from USDL

UsdlRecognizer usdl = new UsdlRecognizer();
                scanAction(new DocumentUISettings(prepareRecognizerBundle(usdl)));

Please Reply.....

**Comment by juraskrlec** [comment]
Hi @MOhsain,

for Android, please go to https://github.com/BlinkID/blinkid-android

Best regards,
Jura
