### ISSUE TITLE
MBMicroblinkInitialization.h

### ISSUE THREAD

**Issue by VitaliyGozhenko** [BlinkID/blinkid-ios#249]
### [READ] Step 1: Are you in the right place?

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with BlinkID tag.
  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Microblink support](https://help.microblink.com/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * BlinkID SDK version: 4.10
  * What are you trying to scan?

### [REQUIRED] Step 3: Describe the problem

You have difference in one capital letter between import directive and actual file name.
Xcode gives warning about Non-portable path to file '"MBMicroblinkInitialization.h"'; specified path differs in case from file name on disk

it is happens because you have import directive:
`#import "MBMicroblinkInitialization.h"`
but actual file name MBMicroBlinkInitialization.h (capital letter B)
If you have case-sensitive file system on your laptop, you will get build error in such case.

File system in iOS is case sensitive, can you

or update #import "MBMicroblinkInitialization.h" -> #import "MBMicroBlinkInitialization.h"
or rename file from MBMicroBlinkInitialization.h -> MBMicroblinkInitialization.h
.h

**Comment by juraskrlec** [comment]
Hi @VitaliyGozhenko 

I see now, in our SDK is ok, it's because of Github. It is case insensitive, so we'll fix that. Thank you for reporting this.

Best,
Jura

**Comment by VitaliyGozhenko** [comment]
Still the same issue in the 4.11 release...

**Comment by vg-identance** [comment]
Any updates?

**Comment by iSapozhnik** [comment]
@juraskrlec Hey! Are there any chances that this issue mught be fixed in the nearest future?

**Comment by juraskrlec** [comment]
It will be fixed in the next release now that we are planning very soon

**Comment by juraskrlec** [comment]
Closing this issue, it's fixed in [v5.0.0](https://github.com/BlinkID/blinkid-ios/releases/tag/v5.0.0)
