### ISSUE TITLE
Invalid architecture since v1.4

### ISSUE THREAD

**Issue by Natelegreat1** [BlinkID/blinkid-ios#25]
I am trying to use BlinkID since v1.3 and I've had the same issue with v1.4, 2.0 and now 2.1.
I have adapted my code to reflect the updated API as shown in the *Getting Started With Swift*

I'm not sure if it's related to #21... 

I have tried removing and reinstalling the pod.
I have tried `pod 'PPBlinkID', :git => 'https://github.com/blinkid/blinkid-ios', :branch => 'master'` and installing 'git-lfs'

I cannot get rid of these errors.

Any ideas?

<img width="1280" alt="screen shot 2016-06-27 at 22 21 34" src="https://cloud.githubusercontent.com/assets/2666640/16401958/c8f9e752-3cb6-11e6-996d-7133b66dec8b.png">

**Comment by Pickles112358** [comment]
Hello,

This is probably related to Git LFS. You can confirm this by checking the size of /MicroBlink.framework/Microblink file locally (on GitHub located here: https://github.com/BlinkID/blinkid-ios/blob/master/MicroBlink.framework/MicroBlink). If the size of file is alot smaller than 100MB then, Git LFS did not recieve the file correctly.

To fix this error you should completely remove our Pod and reinstall it again while Git LFS is installed.
Podfile for BlinkID should look something like this:

platform :ios, '7.0'
pod 'PPBlinkID', '~> 2.1.0'

Kind regards,
Dino

**Comment by Natelegreat1** [comment]
After clearing DerivedData (for the hundredth time) and changing my pod file to    
`pod 'PPBlinkID', '~> 2.1.0'`, I was able to compile successfully. Thank you so much!
