### ISSUE TITLE
ColombiaIdBackRecognizer is not working

### ISSUE THREAD

**Issue by andresmtz98** [BlinkID/blinkid-ios#250]
Related to [Android issue](https://github.com/BlinkID/blinkid-android/issues/130) but in iOS (i don't know if on Android still occurs).

**Comment by culoi** [comment]
Hello @andresmtz98,

Since the issue on Android issue was open (Oct 2018), we introduce many improvements in our SDK.

Please contact us at support@microblink.com with more information.

Regards

**Comment by andresmtz98** [comment]
Thank u man, i'll contact to the support.
