### ISSUE TITLE
UIImage is returning empty when we try to convert from MBImage

### ISSUE THREAD

**Issue by phanikumar560** [BlinkID/blinkid-ios#252]
###
  * Xcode version: _____10.1
  * BlinkID SDK version: _____4.8
  * What are you trying to scan? _____emirates iD and passport

### [REQUIRED] Step 3: Describe the problem

When we are trying to get the the UIImage from the results fetched through MBUnitedArabEmiratesIdFrontRecognizerResult  &&
MBMrzResult  We are getting UIImage as empty.Attached the code and outputs.
Issue in Objective -C.

#### Relevant Code:

- (void)recognizerRunnerViewController:(nonnull UIViewController<MBRecognizerRunnerViewController> *)recognizerRunnerViewController didFinishScanningWithState:(MBRecognizerResultState)state {

 if ([recognizer isKindOfClass:[MBUnitedArabEmiratesIdFrontRecognizer class]]) {
                        NSLog(@"Entered into MBUnitedArabEmiratesIdFrontRecognizer");
                        MBUnitedArabEmiratesIdFrontRecognizer *mbUnitedArabEmiratesIdFrontRecognizer = (MBUnitedArabEmiratesIdFrontRecognizer *)recognizer;
                         self.eidBackDetails = [[NSMutableDictionary alloc] init];
                         
                         self.encodeFullDocumentImage=YES;
                         self.returnFullDocumentImage=YES;
                         
                          NSLog(@"front result::%@",mbUnitedArabEmiratesIdFrontRecognizer.result);
                        
                         MBImage *mbImage=mbUnitedArabEmiratesIdFrontRecognizer.result.fullDocumentImage;
                          NSData *Imagedata=mbUnitedArabEmiratesIdFrontRecognizer.result.encodedFullDocumentImage;
                         NSLog(@"mbImage== %@",mbImage); 
                        NSLog(@"Imagedata==%@",Imagedata);
                         UIImage *imageUI=[[UIImage alloc]init];
                         imageUI=mbImage.image;
                        
                    
                         
                       
                         NSString* newStr = [UIImageJPEGRepresentation(imageUI,0.8) base64EncodedStringWithOptions:nil];
                         NSLog(@"newStr==%@",newStr);
                         
 
}
 /* Output
                         2019-06-25 20:27:11.266498+0400 BlinkInput-sample[4659:628107] mbImage== <MBCvMatImage: 0x28029ee10>
                         2019-06-25 20:27:11.266517+0400 BlinkInput-sample[4659:628107] Imagedata==<>
                         */

                        /* output
                          019-06-25 20:31:55.887161+0400 BlinkInput-sample[4681:629819] newStr==(null)
                         */

// TODO(you): code here to reproduce the problem
```

**Comment by phanikumar560** [comment]
Hi Team,
Could you please respond to this.We have been waiting more than 10 days We didn't receive any update on this. 
Please let us know if there is any quick way of replying to our issues.?

Thanks
Phani

**Comment by dCubelic** [comment]
Hi Phani,

sorry for the late response, most of our team is on vacation currently.

As for the issue, please make sure you set returnFullDocumtnImage to true on the recognizer instance before you initialize the scanning.

Here is swift snippet:

```
recognizer = MBUnitedArabEmiratesIdFrontRecognizer()
        recognizer?.returnFullDocumentImage = true
        
        let settings = MBDocumentOverlaySettings()
        let collection = MBRecognizerCollection(recognizers: [recognizer!])
        let overlay = MBDocumentOverlayViewController(settings: settings, recognizerCollection: collection, delegate: self)
        let vc = MBViewControllerFactory.recognizerRunnerViewController(withOverlayViewController: overlay)
        
        present(vc, animated: true, completion: nil)
```

After that, when DidFinishScanning delegate method is called, you can access the image using `recognizer?.result.fullDocumentImage?.image`

Hope this solves your problem.

Best regards,
Dominik

**Comment by phanikumar560** [comment]
Hi 
Could you please help me out in objective C?

Thanks
Phani

**Comment by dCubelic** [comment]
Hi,

here is the equivalent Objective C snippet:

```
recognizer = [[MBUnitedArabEmiratesIdFrontRecognizer alloc] init];
recognizer.returnFullDocumentImage = YES;
    
MBDocumentOverlaySettings *settings = [[MBDocumentOverlaySettings alloc] init];
MBRecognizerCollection *collection = [[MBRecognizerCollection alloc] initWithRecognizers:@[recognizer]];
MBDocumentOverlayViewController *overlay = [[MBDocumentOverlayViewController alloc] initWithSettings:settings recognizerCollection:collection delegate:self];
UIViewController *vc = [MBViewControllerFactory recognizerRunnerViewControllerWithOverlayViewController:overlay];
    
[self presentViewController:vc animated:true completion:nil];
```

And you can access the image using `recognizer.result.fullDocumentImage.image`

I hope you manage to get this running, I will mark this as closed.

Best regards,
Dominik
