### ISSUE TITLE
Remove X closing icon from MBBlinkIdOverlayViewController

### ISSUE THREAD

**Issue by denismullaraj** [BlinkID/blinkid-ios#256]
#208 
# [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * BlinkID SDK version: 4.11.0
  * What are you trying to scan? ID Documents

### [REQUIRED] Step 3: Describe the problem
I would like to reuse the UI and code behind MBBlinkIdOverlayViewController as my overlay screen, but I put it in a container view and on top of it I have my usual top navigation bar with screen title and the close/back icon on the top left. Hence, I would like to just use the MBBlinkIdOverlayViewController but without the close icon on the top left as I would like to reuse my own icon that is outside the overlay.

**Comment by culoi** [comment]
Hello @denismullaraj 

You can set displayTorchButton and displayCancleButton to false in order to hide them in BlinkIdOverlay.

         /** Create settings */
        let settings = MBBlinkIdOverlaySettings()
        //settings.autorotateOverlay = true
        //settings.supportedOrientations = UIInterfaceOrientationMask.landscape
        settings.displayTorchButton = false
        settings.displayCancelButton = false

Hope this helps, please let us know how it works for you.

Regards

**Comment by denismullaraj** [comment]
Yes worked great! Thank you!
