### ISSUE TITLE
I don't receive any error but only empty results when sometimes scanning doesn't work

### ISSUE THREAD

**Issue by denismullaraj** [BlinkID/blinkid-ios#257]
#208 
# [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * BlinkID SDK version: 4.11.0
  * What are you trying to scan? ID Document

### [REQUIRED] Step 3: Describe the problem
When I scan my Passport, using the demo code to show an alert with the results, sometimes I get empty results and sometimes I get the results. Once it also crashed on this line  if let `self.mrtdRecognizer?.result.fullDocumentImage?.image` but the overlay stayed locked in the success tick scenario, so it wasn't scanning anymore. 

I am using `MBBlinkIdOverlayViewController` and in the documentation it is stated that there is error handling for free and that it should show some errors, but for me it just showed no title and no message. Shouldn't it show any error by itself as stated in the documentation?

**Comment by culoi** [comment]
Hi @denismullaraj 

If you are scanning only passport, I would suggest using the [PassportRecognizer](https://github.com/BlinkID/blinkid-ios#-passport-recognizer) as this is recognizer specifically made to scan passports and you are able to get faceImage and fullDocumentImage. 

Are you scanning the real passport or sample/scan from the computer screen? 

If you were able to crash the app, can you share the log output so we can check it out and see why did the crash happend? 

Regards

**Comment by denismullaraj** [comment]
@culoi I will keep it in mind. I am not scanning only passport but also ID Cards. Why scanning results in empty result sometime and not in an error? Should I show the error or it should have been done automatically by the MBBlinkIdOverlayViewController?

**Comment by culoi** [comment]
HI @denismullaraj 

We only have an error for license key validation. If you are returning an empty result, you will get different resultsState.

For example, a successful state (where you get all information and image) is valid, uncertain is when you get some results on timeout, and empty when there is no result at all: 

http://blinkid.github.io/blinkid-ios/Enums/MBRecognizerResultState.html

**Comment by denismullaraj** [comment]
Thank you for confirming the actual API behavior.
