### ISSUE TITLE
dateOfBirth.date is one day behind, why?

### ISSUE THREAD

**Issue by denismullaraj** [BlinkID/blinkid-ios#258]
#208 
# [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * BlinkID SDK version: 4.11.0
  * What are you trying to scan? ID Document

### [REQUIRED] Step 3: Describe the problem
I am using `MBBlinkIdOverlayViewController` and after getting the results I am trying to print them to see if they are correct. In my ID Document `date of birth` is 17/06/1992 but in the console log printing `result.dateOfBirth.date` it shows `1992-06-16 22:00:00 +0000` (so one day before). Why is that? I just need a NSDate. Country code is ALB (Albania).

**Comment by culoi** [comment]
Hi @denismullaraj 

Same question asked here: #192 

Please check it out. 

Regards

**Comment by culoi** [comment]
You can always return [original string](http://blinkid.github.io/blinkid-ios/Classes/MBDateResult.html#/c:objc(cs)MBDateResult(py)originalDateString) for the date or format your own string with day, month and year result. For example, you can return dateOfBirth:

message = "Date: \(self.passportRecognizer!.result.mrzResult.dateOfBirth.day).\(self.passportRecognizer!.result.mrzResult.dateOfBirth.month).\(self.passportRecognizer!.result.mrzResult.dateOfBirth.year)"

**Comment by denismullaraj** [comment]
Thank you for confirming the behavior :)
