### ISSUE TITLE
One scanner for passport (front only) and id card (front and retro)?

### ISSUE THREAD

**Issue by denismullaraj** [BlinkID/blinkid-ios#260]
#208 
# [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * BlinkID SDK version: 4.11.0
  * What are you trying to scan? Passports and/or ID Cards

### [REQUIRED] Step 3: Describe the problem
I am using the `MBBlinkIdOverlayViewController` as an overlay viewcontroller and registering for two recognizers: `MBMrtdRecognizer` (to get passports front only image and data) and `MBMrtdCombinedRecognizer` (to get id card front/retro image, face image and data). 

In `blinkIdOverlayViewControllerDidFinishScanning(..)` method it always come as a result the combined recognizer result, so it asks me to flip my document, eventhough I am scanning the passport. 

How would I set it up, to be able to scan either passport (to get data and the front full document image) or id card (to get data, front full document image, back full document image and face image)? For now it always ask me to flip the card, so to scan both front and retro, but that doesn't meet my expectations if I am scanning a passport that has only front side. (Albanian passport and Albanian ID Cards in this case).

ID Card has mrz code on the back side, Passport has the mrz code on the front side.

**Comment by culoi** [comment]
Hi @denismullaraj 

I suggest that you use 2 buttons, one for the passport and one for the ID card.

Reason for that is that both recognizers are looking for the face image and if the MrtdCombined recognizer starts first, it will always prompt scan the backside notification. 

I also recommend that you use PassportRecognizer for scanning the Passport document. 

Hope this helps.

**Comment by denismullaraj** [comment]
Hi @culoi , thank you for the response. I noticed that, in fact I am having an issue having both recognizers MrtdCombined and Passport in one, because more often the overlay asks me to flip the card meanwhile I am scanning a passport, so I saw that both recognizers together is not working. But if that is not working, why the API allows that? **Is there any way to make them work together and let them auto-work for passport (front mrz code) and id cards (retro mrz code)?**

**Comment by culoi** [comment]
Hi @denismullaraj 

> Is there any way to make them work together and let them auto-work for passport (front mrz code) and id cards (retro mrz code)?

Yes, as I mentioned earlier, solution is to use 2 buttons or set the flow where you ask user which document is scanning. If answer is Passport, you activate the passport recognizer and DocumentOverlay and if answer is ID card, you activat MrtdCombined and DocumentVerificationOverlay. 

Also, it is possible to use MrtdCombinedRecognizer together with DocumentVerificationOverlay and scan the passport. When you postion the passport, you will get image of the front of the passport + image of the face and instant switch to back side (where MrtdRecognizer is active) and get result from the MRZ line. 

Did you try to scan the passport on this way? 

Regards

**Comment by denismullaraj** [comment]
Hi @culoi That worked great. I am using a BlinkIdOverlay as we liked it a bit more. Thank you for the great support!
