### ISSUE TITLE
could not find auto-linked framework mircoblink 

### ISSUE THREAD

**Issue by arishanapalli** [BlinkID/blinkid-ios#262]
just downloaded and try to run the application.

got following error.

ld: warning: ignoring file ../..//Microblink.framework/Microblink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): ../..//Microblink.framework/Microblink
ld: warning: Could not find auto-linked framework 'MicroBlink'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MBViewControllerFactory", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_MBRecognizerCollection", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_MBRecognizer", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_MBDocumentOverlaySettings", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_MBEudlRecognizer", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_MBUsdlRecognizer", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_MBMrtdRecognizer", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_MBDocumentOverlayViewController", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_MBMicroblinkSDK", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cabarique** [comment]
any luck fixing this issue? this is also happening to me

**Comment by culoi** [comment]
Hello @arishanapalli and @cabarique 

Please check our article about this issue on our Knowledge Center: https://help.microblink.com/hc/en-us/articles/360007671300-Resource-image-not-found

We will change this in one of our future releases, but as this is a breaking API change as Swift is case sensitive, we have to carefully plan it. 

Hope this topic helps.

Regards

**Comment by arishanapalli** [comment]
The xcode Swift_Version target is maximum 4.2 
I deleted framework & bundle of Microblink and added it again!  
Microblink.framework & Microblink.bundle  added to target project and compiled same error.

`ld: warning: ignoring file /Users/UserName/Downloads/blinkid-ios-master/Samples/BlinkID-sample-Swift/BlinkID-sample-Swift/License/Microblink.framework/Microblink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Users/UserName/Downloads/blinkid-ios-master/Samples/BlinkID-sample-Swift/BlinkID-sample-Swift/License/Microblink.framework/Microblink
`

**Comment by culoi** [comment]
Hello @arishanapalli 

Which version of the Xcode are you using? 

Did you add our Microblink.framework as described here: https://github.com/BlinkID/blinkid-ios#integration-without-cocoapods

and set it as Embed & Sign ? 

Regards

**Comment by bdjessup** [comment]
I am also getting this exact same error.

**Comment by rbarbish** [comment]
Same error

**Comment by mparadina** [comment]
Hello @rbarbish and @bdjessup 

Did you try building only our BlinkID Sample from the GitHub repository?
You can find it here: https://github.com/BlinkID/blinkid-ios/releases

If this is successful, then the issue could be within the settings of your project.
If possible, we could arrange a call and figure out how to solve this issue as soon as possible. 

Regards,
Milan

**Comment by Cerovec** [comment]
Hi @arishanapalli, @cabarique, @arishanapalli, @bdjessup.

Do you still face the same issue with v5.3?

Please let us know so that we can continue investigating.

Thanks,
Jurica.

**Comment by Cerovec** [comment]
Hi @arishanapalli, @cabarique, @arishanapalli, @bdjessup.

We'll close this issue in the meantime and if this is still an issue, please reopen it.

Thanks,
Jurica.
