### ISSUE TITLE
MBDocumentFaceRecognizer

### ISSUE THREAD

**Issue by dusanCZH** [BlinkID/blinkid-ios#264]
I am using MBDocumentFaceRecognizer to try and scan front side of and ID.

I expect for the recognizer to fire a valid didFinishScanningWith event only if it has detected a document with a face on it.

When i test it with a back side of a document (no face in it) i expect nothing to happen but i do get an event. Also i get document and face image with size 0x0.

**This is how I am initializing the recognizer:**
```
 let documentFaceRecognizer = MBDocumentFaceRecognizer()
 documentFaceRecognizer.returnFullDocumentImage = true
 documentFaceRecognizer.returnFaceImage = true
```

**Log  i am getting:**
```
2019-09-26 11:01:54.234693+0200 BlinkScan[625:338553] [Unknown process name] CGImageCreate: invalid image size: 0 x 0.
2019-09-26 11:01:54.333068+0200 BlinkScan[625:338553] [Unknown process name] CGDataProviderCreateDirect: Invalid size = 0
2019-09-26 11:01:54.333118+0200 BlinkScan[625:338553] [Unknown process name] CGImageCreate: invalid image size: 0 x 0.
2019-09-26 11:01:56.558264+0200 BlinkScan[625:338553] [Unknown process name] CGDataProviderCreateDirect: Invalid size = 0
```

Any advice on what I may be doing wrong. When i test your blink ID app from app store it works as expected.

**Comment by culoi** [comment]
Hello @dusanCZH ,

Can you please contact us at support@microblink.com with more information about the document that you are trying to scan? 

Regards

**Comment by dusanCZH** [comment]
Ive provided you the document on support mail.
BRG,
Dusan

**Comment by culoi** [comment]
Thank you @dusanCZH,

Let's continue over the email.

Regards

**Comment by dusanCZH** [comment]
Ive managed to have a workaround by verifying the scanned face document image is not null.
```
func handleScanningFront() -> Bool{
        for recognizer in recognizerCollection.recognizerList {
            if let documentRecognizer = recognizer as? MBDocumentFaceRecognizer{
                if let documentFaceResult = documentRecognizer.baseResult as? MBDocumentFaceRecognizerResult{
                    if let documentImage = documentFaceResult.fullDocumentImage?.image{
                            self.documentImage = documentImage
                            return true
                        }
                    }
                }
            }
        return false
    }
```
