### ISSUE TITLE
Breaking changes v5

### ISSUE THREAD

**Issue by davidperrenoud** [BlinkID/blinkid-ios#269]
As I understand from the release notes of BlinkID v5.0.0, all of the API changes are breaking:

> - removed all country specific recognizers
> - `MBBlinkIdRecognizer` and `MBBlinkIdCombinedRecognizer` are recognizers that classify and extract data from all country specific recognizers available in 4.x.x versions
> - available recognizers are:
>     - `BlinkIdRecognizer`
>     - `BlinkIdCombinedRecognizer`
>     - `MBPassportRecognizer`
>     - `MBVisaRecognizer`
>     - `MBDocumentFaceRecognizer`
>     - `MBMrtdRecognizer`
>     - `MBMrtdCombinedRecognizer`
>     - `MBUsdlRecognizer`
>     - `MBUsdlCombinedRecognizer`
> - parsers and detectors are removed from this version onward
> - Templating API is no longer supported
> - `field by field` scanning feature is no longer supported
> - Swift Module has been renamed from `MicroBlink` to `Microblink`
>     - this will cause Swift project to crash at compile time so please do `import Microblink` from now on

Could you state what the upgrade path for each of these changes is?

As a side note, was there a valid reason for renaming the Swift Module?

**Comment by juraskrlec** [comment]
Hi @davidperrenoud

This release is really important for us, it is our first product powered entirely by machine learning. I suggest to read our [blog](https://microblink.com/blog/blinkid-v5-goodbye-templates) to see where are we going with our future releases and why is this huge step forward.

> removed all country specific recognizers

That means that you no longer have to init specific recogniser for specific country. `MBBlinkIdRecognizer` and `MBBlinkIdCombinedRecognizer` detect, clasiffy and extract result for all [supported countries](https://github.com/BlinkID/blinkid-ios/blob/master/documentation/BlinkIDRecognizer.md).
Please, try out our Sample.

> parsers and detectors are removed from this version onward
> Templating API is no longer supported
> field by field scanning feature is no longer supported

We want to focus on best machine learning based product for data extraction.

> Swift Module has been renamed from MicroBlink to Microblink

Our framework is named `Microblink`. All our products and our name has been renamed to `Microblink`. This is our Major release, so it was convenient to rename Swift Module with this release.

If you have any more questions, just ask, we would be happy for your feedback.
Happy coding!

**Comment by yaakovgamliel** [comment]
I think documentation specially on SDK migrations needs to be improved, every major release has been a painful process

**Comment by Cerovec** [comment]
HI @yaakovgamliel,

Let me pick up the conversation.

Please let us know if you have some specific issues with the documentation or with the API.

Which recognizers were you previously using and for which you don't know the upgrade path?

Thanks,
Jurica.

**Comment by Cerovec** [comment]
Hi @yaakovgamliel, @davidperrenoud, and @jowie,

Thanks for your comments. Version 5 is now a stable API with more than 3 releases done without any breaking changes. We'll now close this issue, but If you're still stuck with upgrading to v5, please let us know how specifically we can help you.

Thanks,
Jurica.
