### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by abinop** [BlinkID/blinkid-ios#27]
I am trying to use BlinkID from the Podfile for a Swift project

`
use_frameworks!
pod 'PPBlinkID', '~> 2.1.0'
`

but I am constantly getting the error

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PPRecognizerResult", referenced from:

```

I have tried cleaning the DerivedData folder but still the same error. Any idea?

**Comment by Pickles112358** [comment]
Could you please check the size of your locally stored MicroBlink.framework/MicroBlink file?

**Comment by abinop** [comment]
@Pickles112358 134 bytes

**Comment by Pickles112358** [comment]
This means that Git LFS has not been able to fetch MicroBlink file correctly.
You can install Git LFS with:
```shell
brew install git-lfs
git lfs install
```
**Don't forget to close and reopen terminal after installation**
After Git LFS has been installed, you should reinstall our framework. Best way to do so is to completely remove our Pod, then reinstall it again.

Kind regards,
Dino

**Comment by abinop** [comment]
I followed these steps but the file is still 134 bytes and the problem persists. What else can I check?

**Comment by abinop** [comment]
Thanks for all this. The same problem occurs with the downloaded samples. So I notice there that I get

`ld: warning: ignoring file ../../MicroBlink.framework/MicroBlink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): ../../MicroBlink.framework/MicroBlink`

**Comment by Pickles112358** [comment]
Have you used the download link i sent you?
This one: https://github.com/BlinkID/blinkid-ios/releases/download/v2.1.0/BlinkID-ios_v2.1.0.zip

Once you unzip it the samples should work out of the box. I have just tried running BlinkID-sample from it and it doesn't output any errors

**Comment by abinop** [comment]
For me not even the BlinkID-sample works as I get the error

`ignoring file ../../MicroBlink.framework/MicroBlink, file was built for unsupported file format`

**Comment by nickkuh** [comment]
I'm experiencing the same problem

**Comment by Pickles112358** [comment]
Can you confirm that you downloaded the [zip file](https://github.com/BlinkID/blinkid-ios/releases/download/v2.1.0/BlinkID-ios_v2.1.0.zip) from above?
And that samples in the Zip file do not work?

**Comment by abinop** [comment]
Yes, I confirm that the BlinkID-sample from that [zip](https://github.com/BlinkID/blinkid-ios/releases/download/v2.1.0/BlinkID-ios_v2.1.0.zip) , when run, produces the error I mentioned

**Comment by Cerovec** [comment]
Hi,

I can also vouch that downloading the SDK from the above link [here](https://github.com/BlinkID/blinkid-ios/releases/download/v2.1.0/BlinkID-ios_v2.1.0.zip), will give you correct MicroBlink framework.

I would advise that you remove all references to BlinkID from your filesystem, then download the zip once again, and try again.

**Comment by abinop** [comment]
After numerous tests, installations and uninstallations what stopped the errors was that I included the Accelerate.framework as it is included in the samples.

The reason for the samples not working must have been that I had different version of Blink in my filesystem, I removed and downloaded again as you mentioned.

Thanks!

**Comment by FGAD** [comment]
When I'm trying to integrate and facing the same issue. Undefined symbols for architecture x86_64
"Xcode 8.0 with swift 3.0"
 pod 'PPBlinkID'

**Comment by DoDoENT** [comment]
If [installing from Cocoapods](https://github.com/BlinkID/blinkid-ios#installation-with-cocoapods), make sure you have installed Git LFS and cloned also binaries that are hosted on LFS.
