### ISSUE TITLE
No such module 'MicroBlink' after upgrading BlinkID SDK version to 5.0.0

### ISSUE THREAD

**Issue by kedardesai** [BlinkID/blinkid-ios#270]
* Xcode version: 10.2.1
  * BlinkID SDK version: 5.0.0
  * What are you trying to scan? USDL

#### Steps to reproduce:

Previously I was using "pod 'PPBlinkID', '~> 4.11.0'" and MBBlinkIDUI to scan USDL and it was working fine. I just updated PPBlinkID to 5.0.0. And it asked to remove MBBlinkIDUI while pod update. So I removed it from podfile.

Now After updating the pod. I am simply trying to import MicroBlink which gives me error "No such module 'MicroBlink'".

Please help.

**Comment by juraskrlec** [comment]
Hi @kedardesai 

Swift Module has been renamed from `MicroBlink` to `Microblink`, so please use Microblink.
Check out [release notes for v5.0.0](https://github.com/BlinkID/blinkid-ios/releases/tag/v5.0.0) for all changes.

Best,
Jura

**Comment by kedardesai** [comment]
I fount out after I opened an issue.

Thanks.
