### ISSUE TITLE
Restricting scanning to a particular region is not working in iOS

### ISSUE THREAD

**Issue by jefinabduljaleel** [BlinkID/blinkid-ios#272]
I have made an app with UI that includes a resizing frame.The purpose of my application is to scan the texts, that comes within the resizing  frame.I have tried using the ScanningRegion property,but then the scanning functonality is not working.I am getting some error in the console:
Brenner quality size: pixels vector doesn't have any values!

    func SetupSDK(){
       
        self.rawOcrParser = MBRawParser()
        
        /** Use DeepOCR engine */
        let deepOcrEngine : MBDeepOcrEngineOptions = MBDeepOcrEngineOptions()
        deepOcrEngine.deepOcrModel = MBDeepOcrModel.blinkInput;
        self.rawOcrParser?.ocrEngineOptions = deepOcrEngine
        
        self.parserGroupProcessor = MBParserGroupProcessor(parsers: [self.rawOcrParser!])
        self.blinkInputRecognizer = MBBlinkInputRecognizer(processors: [self.parserGroupProcessor!])
        
        /** Crate recognizer collection */
        let recognizerList : Array = [self.blinkInputRecognizer!]
        let recognizerCollection : MBRecognizerCollection = MBRecognizerCollection(recognizers: recognizerList)
        
        /** Create your overlay view controller */
        self.customOverlayVC = CustomOverlay.initFromStoryboardWith(self)
        self.customOverlayVC?.reconfigureRecognizers(recognizerCollection)
        
        /** Create recognizer view controller with wanted overlay view controller */
        let recognizerRunneViewController : UIViewController = MBViewControllerFactory.recognizerRunnerViewController(withOverlayViewController: self.customOverlayVC!)
        
                PreviewLayer.translatesAutoresizingMaskIntoConstraints = false
                addChild(recognizerRunneViewController)
                recognizerRunneViewController.view.translatesAutoresizingMaskIntoConstraints = false
                PreviewLayer.addSubview((recognizerRunneViewController.view))
                NSLayoutConstraint.activate([
                    (recognizerRunneViewController.view.leadingAnchor.constraint(equalTo: PreviewLayer.leadingAnchor)),
                    (recognizerRunneViewController.view.trailingAnchor.constraint(equalTo: PreviewLayer.trailingAnchor)),
                    (recognizerRunneViewController.view.topAnchor.constraint(equalTo: PreviewLayer.topAnchor)),
                    (recognizerRunneViewController.view.bottomAnchor.constraint(equalTo: PreviewLayer.bottomAnchor))
                    ])
                recognizerRunneViewController.didMove(toParent: self)
      
             DispatchQueue.main.async {
            
           self.SetAreaofInterest()
            }
    
    }
    
  
    func SetAreaofInterest() {
    
        self.customOverlayVC?.scanningRegion =  CGRect(x: 20, y: 20, width: 250, height: 150)
      
       
    }
   
    
}

extension ViewController: MBCustomOverlayDelegate {
    
    func customOverlayViewControllerDidFinishScannig(_ customOverlay: CustomOverlay, state: MBRecognizerResultState) {
        if (state == MBRecognizerResultState.valid) {
            DispatchQueue.main.async {
                print("The Recogonized text is",self.rawOcrParser?.result.rawText)
            }
        }
    }

**Comment by Cerovec** [comment]
Hi @jefinabduljaleel,

Sorry for the long delay, apologies for that :(

Setting the scanning region should happen *after* the camera loads. This means that it should happen in the CustomOverlay class, ideally in viewDidAppear.

Let us if this is still an issue for you and if this advice helps.

Thanks!
Jurica.

**Comment by Cerovec** [comment]
Hi @jefinabduljaleel,

Please let us know if you have this issue still active.

Thanks,
Jurica.

**Comment by jefinabduljaleel** [comment]
Hi Jurica,

Thanks for your email.I really appreciate your concern.Actually, i had
already tried implementing the method, mentioned  in your  previous
email.But, it did not work in my case.I had found an alternate solution for
the same.Once again, thanks for your help.

**Comment by Cerovec** [comment]
Hi @jefinabduljaleel,

Thanks for the update - and that's great news! Is there something else we can do for you? In the meantime, we're closing this issue, but please be free to reopen it if you think we can help you out.

Thanks,
Jurica.
