### ISSUE TITLE
Failed to verify bitcode in Microblink.framework

### ISSUE THREAD

**Issue by kedardesai** [BlinkID/blinkid-ios#274]
* Xcode version: 10.2.1
  * BlinkID SDK version: 5.0.1
  * What are you trying to scan? USDL

I am getting an error while creating an ipa file. The error says "Failed to verify bitcode in Microblink.framework". I have also attached screenshot for the same.

**Comment by kedardesai** [comment]
![Screenshot 2019-12-04 at 1 27 28 PM](https://user-images.githubusercontent.com/3702347/70124275-701dd780-169a-11ea-8ba4-9353108afbe5.png)

**Comment by Brankacro** [comment]
Hello,

Thank you for your question, below are the steps to follow:

1. You need to open the Xcode project(.xcworkspace file in platforms/ios),
2. Find your project target,
3. Select Build Phases and press little plus, then click on "add run script phase",
4. Open the newly created "Run Script" phase and add the script in the text area. 

https://github.com/BlinkID/blinkid-ios#unsupported-architectures-when-submitting-app-to-app-store

Please run the following and let us know how it works.
For any additional questions, feel free to contact us. You can always contact us directly at support@microblink.com

Best regards,

Branka

**Comment by Cerovec** [comment]
Hi @kedardesai,

Do you still have this issue open?

Thanks,
Jurica.
