### ISSUE TITLE
Converting MBUsdlCombinedRecognizerResult to JSON

### ISSUE THREAD

**Issue by kedardesai** [BlinkID/blinkid-ios#275]
I wanted to store entire scanned data to the server. For that purpose I want scanned result to be converted in JSON format. Right now, an object of MBUsdlCombinedRecognizerResult provides data() which gives me scanned result in bytes. But when I convert it in string and print, I get only few data. Also, this data is in some encrypted format (I can not access it as It is not formatted properly.)

Is there any property or method which converts entire scanned data including images in json format? Please help me with this issue.

**Comment by Brankacro** [comment]
Hello,

thank you for contacting us and for interest in our technologies.

Regarding your question, you need to make your JSON Coder/Encoder with our data. We do not have any method to convert it in JSON format.
If you are using Swift, you can extend our result with codable protocol and then you can make JSON of our result.
Here is the link https://developer.apple.com/documentation/foundation/jsonencoder

If there is anything that we can help you, please let us know.

Kind regards.

Branka

**Comment by Cerovec** [comment]
Hi @kedardesai,

We're currently closing this issue as this falls into the category of the implementation of the SDK. However, if you still face issues with this, please let us know and reopen the issue.

Thanks,
Jurica.
