### ISSUE TITLE
crash_ipad_landscapmode

### ISSUE THREAD

**Issue by Zennaxxtech** [BlinkID/blinkid-ios#277]
My application is only for ipad and its landscape mode when i scan license so scannerview give me hint for flip card but i dont flip card after 1-2 minutes application crashed.
please help me to solve it

**Comment by Brankacro** [comment]
Hello,
please tell us what SDK version are you using and what documents are you trying to scan?
Also, it would be very helpful if you could tell us what iPad are you using and if you could send us a complete log, so we could check it in detail.
Regards,
Branka

**Comment by Zennaxxtech** [comment]
Thanx Branka for reply,
i am using latest SDK of BlinkId - 5.0.2 and i am scanning driving license of US.I am scanning in iPad Air 2 of os version 13.2.3. 
This is error log

*** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [UIAlertController shouldAutorotate] is returning YES'
*** First throw call stack:
(0x1ad94780c 0x1ad66ffa4 0x1ad83cf84 0x1b13b15bc 0x1b13b1b04 0x1b13b2140 0x1b139e9a4 0x1b1e3c3dc 0x1b1e30568 0x1adc1f09c 0x1b1e3046c 0x1b1e3ed58 0x1b0ff790c 0x1b12bc7e4 0x1b12ba328 0x1b19b9e7c 0x1b19a982c 0x1b19d98dc 0x1ad8c4c2c 0x1ad8bfb18 0x1ad8c00e4 0x1ad8bf8a0 0x1b7817328 0x1b19b0740 0x100882b1c 0x1ad74a360)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Brankacro** [comment]
Hello @Zennaxxtech,
Thanks for the details.
You should specify which orientations does the CameraViewController support. This is done using autorotate and supportedOrientations properties of the CameraViewController.

Simply set it to:
autorotate = YES
supportedInterfaceOrientations = UIInterfaceOrientationMask.Landscape to support both landscape orientations

Hope this was helpful. Please, let us know how it works.
Kind regards,
Branka

**Comment by Cerovec** [comment]
Hi @Zennaxxtech,

Please let us know if this is still an open issue for you. The SDK should definitely work in all orientations, however if you need additional help, we can double-check.

Thanks,
Jurica.

**Comment by Cerovec** [comment]
Hi @Zennaxxtech,

We'll close this issue in the meantime and if this is still an issue, please reopen it.

Thanks,
Jurica.
