### ISSUE TITLE
Capturing the names of the users is inaccurate from emirates ID

### ISSUE THREAD

**Issue by phanikumar560** [BlinkID/blinkid-ios#279]
Facing issue with capturing the names of the users is in accurate from emirates ID.

  * BlinkID SDK version: 4.8
  * What are you trying to scan? emirates ID- UAE

Thanks
Phani

**Comment by Brankacro** [comment]
Hello, v.4.8 has a glare detector, so we would like to suggest you to update to version 5.1 and we will enable you the rights for Custom. In v5.1. we added a blur filter that discards blurred frames and prevents reading data from them.
Please contact us directly to support@microblink.com with more details, so we could enable you more rights for your issue.
Regards,
Branka

**Comment by phanikumar560** [comment]
Hi Team,
Any Solution/Fix is available in version 4.8 without upgrading to latest version.??

Thanks
Phani

**Comment by phanikumar560** [comment]
Hi Team,

If we change the property of glare detection to false in v4.8, will the issue get resolved without impacting other functionalities?
Thanks
Phani

**Comment by Brankacro** [comment]
Hello Phani,
Thank you for contacting us directly at support@microblink.com
As Ivan already replied to you directly, we are checking this with our Product dev team, but there are no reverse fixes in our SDK. 
This is why we always recommend our customers to use the latest version of the SDK once we publish them live.
V4.8 is released in March, so there were many fixes (most important was 4.10.0 where we removed Glare detection from the UAE ID documents).
We'll close the communication here, if it is ok for you, and continue it directly.
Best regards.
Branka

**Comment by Cerovec** [comment]
Hi @phanikumar560,

We definitely advise you to upgrade to our latest BlinkID v5.3 which contains bigger improvements in performance when scanning Emirates IDs.

In order to upgrade, you would need to use BlinkID Recognizer.

Please let us know if this is an option for you, and if not, we can see if we can provide an alternative solution.

Thanks,
Jurica.

**Comment by Cerovec** [comment]
Hi @phanikumar560,

We're reclassifying this as "enhancement" and still waiting for your feedback.

Thanks,
Jurica.

**Comment by Cerovec** [comment]
Hi @phanikumar560,

We're closing this issue at this moment because we've made progress with the performance of scanning Emirates IDs in the latest BlinkID versions, especially with v5.3.

If you still experience problems, or you need additional help, please reopen the issue. 

Thanks,
Jurica.
