### ISSUE TITLE
Section "direct processing api" missing in documentation

### ISSUE THREAD

**Issue by lucasecci0** [BlinkID/blinkid-ios#280]
Section pointing at https://github.com/BlinkID/blinkid-ios#direct-processing-api is missing in documentation at https://github.com/BlinkID/blinkid-ios

**Comment by culoi** [comment]
Hello @lucasecci0 ,

You are correct, DirectAPI was in the Readme.md file in the V4.11.0 of our BlinkID SDK. It was removed in v5.0.

Here is the link to the documentation in V4.11.0: https://github.com/BlinkID/blinkid-ios/tree/v4.11.0#-direct-processing-api

Hope this helps, if you have any questions, please let me know.

Regards

**Comment by Cerovec** [comment]
Hi @lucasecci0,

the documentation is updated and it now contains Direct Processing API section.

Please let us know if this solves your issue.

Thanks,
Jurica.

**Comment by Cerovec** [comment]
Hi,

I'm closing this as we consider it solved. Please reopen if something doesn't work.

Thanks,
Jurica.
