### ISSUE TITLE
US passports are not scanned

### ISSUE THREAD

**Issue by khambir** [BlinkID/blinkid-ios#281]
### Environment

  * Xcode version: 11.3 (11C29)
  * BlinkID SDK version: 5.0.0
  * What are you trying to scan? US passport

### The problem:

I try to scan US passports, but nothing happens. Thre is no result of scanning.
I can provide photos of passports if needed (only for the blink id team via a support email) for testing.

#### Steps to reproduce:

1. Open scanner. Devices that I have used: iPhone X, iPhone 7, iPad 2018.
2. Try to scan US passport with `MBPassportRecognizer` or `MBMrtdRecognizer` or `MBUsdlRecognizer` (I have tried all of them)
3. Nothing happens, no errors, no results

**Comment by mparadina** [comment]
Hi @khambir 

The issue could be with the document you have tried to scan.

Did you try to scan the document with our demo app?

Here is the link of the BlinkID and our Vision application:
BlinkID: https://apps.apple.com/us/app/blinkid/id1258136557
Vision: https://apps.apple.com/us/app/microblink-vision/id1464662310

Also, please contact us directly at support@microblink.com for more details.

Best regards,
Milan
