### ISSUE TITLE
MBBlinkCardRecognizer not found in SDK version 5.1.0

### ISSUE THREAD

**Issue by yaakovgamliel** [BlinkID/blinkid-ios#283]
We are in works to upgrade from `PPBlinkID` ***4.11.0*** to version ***5.1.0***, unfortunately we are not able to find `MBBlinkCardRecognizer` or its equivalent, could you please point us to a recognizer capable of scanning debit/credit cards.

**Comment by mparadina** [comment]
Hi @yaakovgamliel 

You will need to download the custom SDK from our developer Dashboard, which contains all of the recognizers.
We will need to enable you to download the SDK, so can you please contact us directly at support@microblink.com for more information.

Regards,
Milan
