### ISSUE TITLE
Want to present full screen rather than card view presentation in iOS 13 for Camera Overlay Scanning Screen

### ISSUE THREAD

**Issue by prasoonpuri12** [BlinkID/blinkid-ios#285]
* Xcode version: 11.3.1
  * BlinkID SDK version: 4.8.0
  * What are you trying to scan? Passport and UAE Emirates ID

Problem Description :
I am using the microblink sdk for iOS (Objective-C) with a cross platform technology Kony, it was working fine but since the latest update of iOS to 13.0, Apple changed the default  modal presentation style to Card View Presentation. I searched for the solution and found out we have to pass "vcObj.modalPresentationStyle = UIModalPresentationFullScreen" to the view controller to force it show itself in fullscreen but unfortunately I am not able to achieve it for the view overlay controller I am passing to the Microblink method :

[self presentViewController:[MBViewControllerFactory recognizerRunnerViewControllerWithOverlayViewController:customVC] animated:YES completion:nil];

Please provide any workaround for the same. Thank you.

Proposed Code:
[ViewController Object].modalPresentationStyle = UIModalPresentationFullScreen
MBViewControllerFactory recognizerRunnerViewControllerWithOverlayViewController:[ViewController Object] animated:YES completion:nil];

**Comment by juraskrlec** [comment]
Hi @prasoonpuri12 

you need to change `modalPresentationStyle` on recognizer VC which you are getting from `recognizerRunnerViewControllerWithOverlayViewController`. So like this:

`UIViewController<MBRecognizerRunnerViewController>*  scanningViewController = [MBViewControllerFactory recognizerRunnerViewControllerWithOverlayViewController: customVC];`
`scanningViewController.modalPresentationStyle = UIModalPresentationFullScreen;`
`[self presentViewController:scanningViewController animated:YES completion:nil];`

Best regards,
Jura

**Comment by prasoonpuri12** [comment]
Thank you for your prompt response. It worked fine!!!
