### ISSUE TITLE
MBUsdlCombinedRecognizer doesn't detect an ID card when wrapped in a MBSuccessFrameGrabberRecognizer

### ISSUE THREAD

**Issue by jakubdolejs** [BlinkID/blinkid-ios#288]
### Describe your environment

  * Xcode version: 11.3.1 (11C504)
  * BlinkID SDK version: 5.2.0
  * What are you trying to scan? Canadian (Ontario) driver's licence

### Describe the problem

 When using `MBUsdlCombinedRecognizer` wrapped in a `MBSuccessFrameGrabberRecognizer` none of the delegate methods are called and the scan never seemingly detects the driver's licence. The same setup works when scanning a UK driving licence with `MBBlinkIdCombinedRecognizer` wrapped in a `MBSuccessFrameGrabberRecognizer`.

Note that the exact same setup works with `UsdlCombinedRecognizer` wrapped inside a `SuccessFrameGrabberRecognizer` in the Android version of the Microblink SDK.

#### Steps to reproduce:

What happened? How can we make the problem occur? 

 1. Create an instance of `MBUsdlCombinedRecognizer`
 2. Create an instance of `MBSuccessFrameGrabberRecognizer` with the `MBUsdlCombinedRecognizer` instance as its constructor parameter
 3. Create an `MBRecognizerCollection` with an array containing the `MBSuccessFrameGrabberRecognizer`
 4. Create an `MBBlinkIdOverlayViewController` with the recognizer collection created in step 3.
 5. Pass the overlay view controller to the `MBViewControllerFactory.recognizerRunnerViewController` factory method to create a view controller.
 6. Present the view controller.

#### Relevant Code:

```swift
class MyViewController: UIViewController, MBBlinkIdOverlayViewControllerDelegate {
    var blinkIdRecognizer: MBSuccessFrameGrabberRecognizer?

    // This doesn't pick up a Canadian (Ontario) driver's licence
    // Also tested with high-res images of a Missouri and Texas driver's licence without luck
    func scanNorthAmericanID() {
        let recognizer = MBUsdlCombinedRecognizer()
        recognizer.encodeFullDocumentImage = true
        self.scanIDUsingRecognizer(recognizer)
    }

    // This successfully scans a UK driving licence
    func scanOtherID() {
        let recognizer = MBBlinkIdCombinedRecognizer()
        recognizer.encodeFullDocumentImage = true
        self.scanIDUsingRecognizer(recognizer)
    }

    func scanIDUsingRecognizer(_ recognizer: MBRecognizer) {
        self.blinkIdRecognizer = MBSuccessFrameGrabberRecognizer(recognizer: recognizer)
        let settings : MBBlinkIdOverlaySettings = MBBlinkIdOverlaySettings()
        settings.autorotateOverlay = true
        let recognizerCollection: MBRecognizerCollection = MBRecognizerCollection(recognizers: [self.blinkIdRecognizer!])
        let blinkIdOverlayViewController: MBBlinkIdOverlayViewController = MBBlinkIdOverlayViewController(settings: settings, recognizerCollection: recognizerCollection, delegate: self)
        let recognizerRunneViewController: UIViewController = MBViewControllerFactory.recognizerRunnerViewController(withOverlayViewController: blinkIdOverlayViewController)
        self.present(recognizerRunneViewController, animated: true, completion: nil)
    }

    // MARK: - Delegate methods

    func blinkIdOverlayViewControllerDidFinishScanning(_ blinkIdOverlayViewController: MBBlinkIdOverlayViewController, state: MBRecognizerResultState) {
        if state == .valid {
            blinkIdOverlayViewController.recognizerRunnerViewController?.pauseScanning()
            DispatchQueue.main.async {
                blinkIdOverlayViewController.dismiss(animated: true, completion: nil)
                if let result = (self.blinkIdRecognizer?.slaveRecognizer as? MBBlinkIdCombinedRecognizer)?.result, let jpeg = result.encodedFullDocumentFrontImage {
                    // redacted
                } else if let result = (self.blinkIdRecognizer?.slaveRecognizer as? MBUsdlCombinedRecognizer)?.result, let jpeg = result.encodedFullDocumentImage {
                    // redacted
                }
            }
        }
    }
    
    func blinkIdOverlayViewControllerDidTapClose(_ blinkIdOverlayViewController: MBBlinkIdOverlayViewController) {
        blinkIdOverlayViewController.recognizerRunnerViewController?.pauseScanning()
        blinkIdOverlayViewController.dismiss(animated: true, completion: nil)
    }
}
```

**Comment by culoi** [comment]
Hi Jakub,

Can you try to set recognizer and successFrame image on the following way: 
        
        self.blinkIdRecognizer = MBBlinkIdCombinedRecognizer()
        self.blinkIdRecognizer?.returnFullDocumentImage = true
        self.successFrameGrabber = MBSuccessFrameGrabberRecognizer(recognizer: blinkIdRecognizer!)

Then you can return the success frame as an image in the blinkIdRecognizer result. 

Here is the complete ViewController, it maybe helps you in the integration:

[ViewController.txt](https://github.com/BlinkID/blinkid-ios/files/4312590/ViewController.txt)

**Comment by jakubdolejs** [comment]
Thank you. I'll try that. What I ended up doing in the meantime, and it seems to work well, is setting the `returnFullDocumentImage` on `MBBlinkIdCombinedRecognizer` to `true` and not wrapping it in the `MBSuccessFrameGrabberRecognizer`.

**Comment by culoi** [comment]
Hi @jakubdolejs 

Ok, that works if you require to obtain only the image of the document. From the subject, I was under the impression that you are required to use the success frame as it is returning the best frame on which the recognition was done. 

Regards

**Comment by Cerovec** [comment]
HI @jakubdolejs,

Thanks for reporting this. It took us some more time to analyze this so thanks for your patience.

It seems like indeed we have an issue with `MBBlinkIdOverlayViewController` when it's being used with `MBSuccessFrameGrabberRecognizer`, and not directly with a certain combined recognizer (like `MBUsdlCombinedRecognizer` or `MBBlinkIDCombinedRecognizer`). What happens is that we don't show the message to the user to rotate the card. The scanning can actually be done (you can check this if you just rotate the card even if the message to rotate it wasn't shown), but the UI is stuck on the screen to scan the front side. 

This as an effect has that you cannot get a success frame image (the camera frame which resulted in a successful scan) when used with `MBBlinkIdOverlayViewController`.

Let us know if the workaround works for you in the meantime so we can prioritize fixing this accordingly.

Thanks,
Jurica.

**Comment by Cerovec** [comment]
HI @jakubdolejs,

Just to keep you in the loop, we're planning to fix this issue in v5.4 which will be released around the 1st of May.

We definitely suggest you upgrade to the latest version once it's released.

Thanks!
Jurica.

**Comment by Cerovec** [comment]
Hi @jakubdolejs,
Please check out version 5.4 - it's out.

https://github.com/BlinkID/blinkid-ios/releases/tag/v5.4.0

Thanks,
Jurica.

**Comment by Cerovec** [comment]
Hi @jakubdolejs,

We'll close this issue as we consider this solved. Please reopen it if you still face problems here.

Thanks,
Jurica.
