### ISSUE TITLE
Unable to get results for Custom UI

### ISSUE THREAD

**Issue by nimitjarvis** [BlinkID/blinkid-ios#289]
Hello,

1) I am not able to run the sample swift project in XCode 11.3 and 11.3.1. I did use Git Large File Storage command given in README.md file.
![Screenshot 2020-02-25 at 8 44 35 PM](https://user-images.githubusercontent.com/61141056/75260310-6aeea580-580f-11ea-82e5-60b9dfc59617.png)

I tried removing derived data and tried making related changes in build settings of the target of the project but nothing worked! 

2) I created a demo project from scratch using pod(pod 'PPBlinkID', '~> 5.2.0') with same files and codes as in sample swift project which I'm able to run in the device. It works well for default UI however, it does not give me the result for Custom UI. It does not go inside **if recognizer is MBBlinkIdRecognizer** condition!

Please help

Thanks

**Comment by AQElementary** [comment]
Same issue i am facing, i am unable to run the dummy project?

**Comment by culoi** [comment]
Hello @nimitjarvis and @AQElementary ,

Maybe there is an issue with Git lfs. Which version of git lfs are you using?

Did you try clean install and run the sample without any modifications? 

You can download release directly from the following link: https://github.com/BlinkID/blinkid-ios/releases/tag/v5.2.0

Regards

**Comment by Cerovec** [comment]
Hi @AQElementary  and @nimitjarvis,

Please let us know if this solved your issue. If not, we'd want to continue searching for other solutions. If yes, we'd like to close this issue. 

Thank you!
Jurica.

**Comment by nimitjarvis** [comment]
Hello,

I'm so sorry for the inconvenience but I have not got the chance yet to
check!
Please give me some more time and I'll surely respond!

Thanks a lot for the follow-up! I really appreciate it.
Hoping to update you soon.


Thanks and regards,
Nimit

**Comment by Cerovec** [comment]
Hi @nimitjarvis,

We're just checking in with your progress. Would you be interested in having a quick call to double-check where we are?

Thanks,
Jurica.

**Comment by nimitjarvis** [comment]
Hello,

Thanks for the follow-up!
Attaching the demo project that I have created using Pods with the help of
the GitHub example code. I am able to get results using the default UI.
However, custom UI does not respond back with the results.

Can you please have a look and let me know if there is something that needs
change.

Furthermore, I'm open for a call as well.


Thanks,
Nimit
 blink.zip
<https://drive.google.com/file/d/1vp8x_59hGkpMAIWLWvyPfXC2NaVRGuFP/view?usp=drive_web>

**Comment by Cerovec** [comment]
Hi @nimitjarvis,

Thanks for this, it makes sense now!

Please note that the Custom UI was only written as an example for you to base your implementation of the Custom UI on top of it! It wasn't intended to be the perfect UX for ID scanning.

***

The Custom UI before version 5.3 wasn't properly designed. It had two issues:

1) It didn't report the event to turn the card around when both sides of the ID should have been scanned (like in the case where `MBBlinkIdCombinedRecognizer` was used, which requires scanning both sides)
2) It didn't properly show the scanning results when `MBBlinkIdCombinedRecognizer` was used.

If you take your code and, in the class CustomOverlay.swift, add the case to handle `MBBlinkIdCombinedRecognizer` (to take care of the issue 2)

```objective-c
for recognizer in self.recognizerCollection.recognizerList {
    if ( recognizer.baseResult?.resultState == MBRecognizerResultState.valid ) {
        if recognizer is MBBlinkIdRecognizer {
            let blinkIdRecognizer = recognizer as? MBBlinkIdRecognizer
            title = "BlinkID"
            message = (blinkIdRecognizer?.result.description)!
        }
        // Add the following 4 lines of code here
        if recognizer is MBBlinkIdCombinedRecognizer {
            let blinkIdRecognizer = recognizer as? MBBlinkIdCombinedRecognizer
            title = "BlinkID Combined"
            message = (blinkIdRecognizer?.result.description)!
        }
    }
}
```

And then if you run the code and turn the card in between the scanning sessions, you will get something like in the video 1.

***

The sample was improved in version v5.3. Now we have a label on the bottom of the screen which shows you which side you need to scan, and we also correctly show the result. The video 2 was taken with our official sample from v5.3.

Video 1: https://drive.google.com/file/d/1hWC_NG03fbTsWs81F6VrXOMfz2yDy6hC/view?usp=sharing

Video 2: https://drive.google.com/file/d/1L8yIMAxtOTDEzVhxCBqy2NIH_Irr1BV3/view?usp=sharing

***

Please let us know how can we further help you.

Stay safe!
Jurica.

**Comment by Cerovec** [comment]
Hi @nimitjarvis,

Can you check if you can get the Custom UI working now?

Thanks,
Jurica.

**Comment by nimitjarvis** [comment]
It is working now...
Thanks a ton

Regards,
Nimit

**Comment by Cerovec** [comment]
Awesome! We're closing this ticket then.

Good luck!
Jurica.
