### ISSUE TITLE
Scanning a French National ID returns empty string for sex/gender

### ISSUE THREAD

**Issue by jowie** [BlinkID/blinkid-ios#290]
### [READ] Step 1: Are you in the right place?

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with BlinkID tag.
  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Microblink support](https://help.microblink.com/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.3.1 (11C504)
  * BlinkID SDK version: v5.2.0
  * What are you trying to scan? French National ID

#### Steps to reproduce:
- Create app which uses the `BlinkIdCombinedRecognizer`
- Scan the front of a French National ID (in this case, from a woman)
- Observe results
- EXP: "F" in the `sex` property of the `MBBlinkIdCombinedRecognizerResult`
- ACT: returns "" (empty string) in the `sex` property.

**Comment by jowie** [comment]
Image scanned (from Wikipedia):

<img src="https://upload.wikimedia.org/wikipedia/commons/2/23/French_Identity_card_1988_-_1994.jpg" />

**Comment by culoi** [comment]
Hello @jowie 

As from the France ID, we process the information from the [MRZ](https://help.microblink.com/hc/en-us/articles/360007487833-MRTD-FAQ) line, gender is returned from the mrzResult of the BlinkIdCombinedRecognizer.

You can obtain a full result with `self.blinkIdRecognizer!.result.description` or gender only with `self.blinkIdRecognizer!.result.mrzResult.gender`.

I'm attaching a code sample for both cases: 

` message = ("Returns only gender: \(self.blinkIdRecognizer!.result.mrzResult.gender) \n Return full ID info: \(self.blinkIdRecognizer!.result.description)")`

Hope this helps.

**Comment by jowie** [comment]
Perfect. Sorry, did not realise this!
