### ISSUE TITLE
Prompt the user to flip document while using MBUsdlCombinedRecognizer for US Driving License

### ISSUE THREAD

**Issue by iosfitness** [BlinkID/blinkid-ios#296]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * BlinkID SDK version: pod 'PPBlinkID', '~> 5.3.0'
  * What are you trying to scan? US Driving License (State:Utah)

### [REQUIRED] Step 2: Describe the problem

I am able to scan the front and backside of the license. However, I do not get any callback once the front has been scanned. I only come to know after I scan the backside. Due to this, I have no idea how to inform the user that the document has to be flipped now.

#### Steps to reproduce:

Start the App and scan for a US Driving license.

#### Relevant Code:

```
//For scan Driving Licence for Both side

var usdlCombinedRecognizer: MBUsdlCombinedRecognizer?
self.usdlCombinedRecognizer?.returnFullDocumentImage = true
self.usdlCombinedRecognizer?.scanUncertain = true
self.usdlCombinedRecognizer?.allowNullQuietZone = true
recognizers.append(self.usdlCombinedRecognizer!)

//To initialize Micorblink Custom Controller, which is subclass of MBCustomOverlayViewController (ref. sample example)

func getMicroblinkRecognizer(recognizerCollection: [MBRecognizer]) {
        let recognizerList = recognizerCollection
        let recognizerCollection : MBRecognizerCollection = MBRecognizerCollection(recognizers: recognizerList)
        let customOverlayViewController : PLCameraViewController = PLCameraViewController.initFromStoryboardWith()

        customOverlayViewController.guestService = self.guestService
        customOverlayViewController.reconfigureRecognizers(recognizerCollection)

        let recognizerRunneViewController: UIViewController = MBViewControllerFactory.recognizerRunnerViewController(withOverlayViewController: customOverlayViewController)
        self.navigationController?.pushViewController(recognizerRunneViewController, animated: true)
}

//Delegate

scanningRecognizerRunnerViewControllerDelegate
```

**Comment by Cerovec** [comment]
Hi @iosfitness,

Thanks for your message!

The callback which is called when the front side is scanned is a part of the Custom UI API. This means you can access it in your `PLCameraViewController` implementation.

Your `PLCameraViewController` needs to implement the `MBFirstSideFinishedRecognizerRunnerViewControllerDelegate` protocol. 

After that, you need to call `super.metadataDelegates.firstSideFinishedRecognizerRunnerViewControllerDelegate = self` somewhere in your `PLCameraViewController` implementation to start getting notified for these events.

Similar setup is achieved in our sample here where we implement the custom Overlay: https://github.com/BlinkID/blinkid-ios/blob/master/Samples/BlinkID-sample-Swift/BlinkID-sample-Swift/CustomOverlay.swift

If you already tried this, and cannot get it working, please send us the source of your `PLCameraViewController`.

Thanks,
Jurica.

**Comment by Cerovec** [comment]
Hi @iosfitness,

Do you have any updates on this?

Thank you,
Jurica.

**Comment by Cerovec** [comment]
Hi @iosfitness,

We will assume you managed to solve your problem and close this issue :)

If that's not the case, please reopen it and feel free to ask us anything.

Thanks,
Jurica.
