### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by znnz** [BlinkID/blinkid-ios#3]
Undefined symbols for architecture x86_64:
  "gpumv::scenes::CCWBADISceneFactory::createCCWBADIScene(Ref<mv::PixelConverter> const&, tagErrorStatus&)", referenced from:
      mv::JustDewarper::JustDewarper(Ref<mv::PixelConverter> const&, mv::RGBFactors const&) in BlinkIDFramework
  "gpumv::scenes::ACSCCWBADISceneFactory::createACSCCWBADIScene(Ref<mv::AdapContrastDewarpParams> const&, tagErrorStatus&)", referenced from:
      mv::CvtColorAdapContrastDewarper::CvtColorAdapContrastDewarper(Ref<mv::AdapContrastDewarpParams> const&, mv::RGBFactors const&) in BlinkIDFramework
  "gpumv::scenes::GCSCCWBADISceneFactory::createGCSCCWBADIScene(Ref<mv::PixelConverter> const&, tagErrorStatus&)", referenced from:
      mv::CvtColorGlobContrastDewarper::CvtColorGlobContrastDewarper(Ref<mv::PixelConverter> const&, unsigned char const*, mv::RGBFactors const&) in BlinkIDFramework
  "photopay::StringValidator::isStringValid(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&) const", referenced from:
      vtable for photopay::CountryCodeValidator in BlinkIDFramework
  "typeinfo for photopay::StringValidator", referenced from:
      typeinfo for photopay::CountryCodeValidator in BlinkIDFramework
  "_iconv", referenced from:
      pping::qrcode::DecodedBitStreamParser::append(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned char const*, unsigned long, char const*) in BlinkIDFramework
      pping::aztec::Decoder::getEncodedData(pping::Ref<pping::BitArray>, pping::ArrayRef<unsigned char>, pping::ArrayRef<pping::ArrayRef<unsigned char> >) in BlinkIDFramework
  "_iconv_close", referenced from:
      pping::qrcode::DecodedBitStreamParser::append(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned char const*, unsigned long, char const*) in BlinkIDFramework
      pping::aztec::Decoder::getEncodedData(pping::Ref<pping::BitArray>, pping::ArrayRef<unsigned char>, pping::ArrayRef<pping::ArrayRef<unsigned char> >) in BlinkIDFramework
  "_iconv_open", referenced from:
      pping::qrcode::DecodedBitStreamParser::append(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned char const*, unsigned long, char const*) in BlinkIDFramework
      pping::aztec::Decoder::getEncodedData(pping::Ref<pping::BitArray>, pping::ArrayRef<unsigned char>, pping::ArrayRef<pping::ArrayRef<unsigned char> >) in BlinkIDFramework
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

*******
Can't solve the linkage error. Help me out of this  Thanks

**Comment by Cerovec** [comment]
Hi,

this seems to be an issue when compiling for iOS simulator.

Thanks for reporting this, we're currently working on releasing the first official version of BlinkID on iOS, where this issue will of course be resolved. Also, in the next update the apps run on iOS simulator will be able to open camera screen, allowing you to more easiliy customize camera UI.

The update will come in a few weeks.

We're sure our update will be worth waiting :)

**Comment by Cerovec** [comment]
@znnz 

Although still not final, latest version in master branch has compile errors fixed.

**Comment by FGAD** [comment]
Facing the issue

file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64):

**Comment by DoDoENT** [comment]
Have you installed git LFS and clone the LFS binary as described in [documentation](https://github.com/BlinkID/blinkid-ios#installation-with-cocoapods)?

**Comment by FGAD** [comment]
Yes done. but still having the issue

**Comment by DoDoENT** [comment]
After installing the Git LFS, you either have to clone repository anew or fetch LFS data in existing clone with:

    git lfs update
    git lfs fetch
    git lfs checkout
