### ISSUE TITLE
OCR Guidance

### ISSUE THREAD

**Issue by matthewjcooper** [BlinkID/blinkid-ios#30]
Your OCR samples have the results dumped to the console over and over again while the camera catches results. During this time the camera is trying to autofocus and does so several times, giving anywhere from horrible results to decent. Is there an event or a setting to tell the ocr to only return results after the camera has focused and to tell it to stop auto focusing will capturing? Any guidance to capture the best result would be helpful.

thank you!

**Comment by Pickles112358** [comment]
Hello,

Only best camera frames will be processed so there is no way to tell our SDK to only process focused frames.
Please read our "Getting started" guide, it might help you discover full abilities of our SDK. One example might be regex parser, which will try to capture text that matches user-defined regex. You can also customize many OCR options in PPOcrEngineOptions class. And lastly, you can use our Templating API to create scanners for custom documents.

Kind regards,
Dino
