### ISSUE TITLE
Is there a way where we can get the image of the signature in Emirates ID?

### ISSUE THREAD

**Issue by phanikumar560** [BlinkID/blinkid-ios#311]
Hi Team,

Is there a way where we can get the image of the signature in Emirates ID. As we are in transition from v4.8 to v5.5 Could you please provide solution for both of the versions.?

We are using MBUnitedArabEmiratesIdBackRecognizer in v4.8

we are using MBBlinkIdCombinedRecognizer in v5.5

Could you please provide the code snippet which could help us in better way.

Thanks
Phani

**Comment by mparadina** [comment]
Hi @phanikumar560 

I'm afraid, that at the moment, we do not return the signature images from the Emirates ID.

Currently, we only return `fullDocumentImage` and `faceImage`​ with the `MBUnitedArabEmiratesIdFrontRecognizer`​, `fullDocumentImage`​ with the `MBUnitedArabEmiratesIdBackRecognizer`. 

We also return the same features with the BlinkID recognizers.


Do you have any additional inquiries?

Regards,
Milan

**Comment by phanikumar560** [comment]
Hi Team,

Is there any option for returning signature image in passport??

Thanks
Phani

**Comment by mparadina** [comment]
Hi @phanikumar560 

Unforuntly, no. We currently do not have the option for signature image returning for passports.

The images you can return are `fullDocumentImage` and  `faceImage`, both with `PassportRecognizer` and `MBBlinkIdRecognizer`

If you have any additional questions, feel free to ask.

Regards,
Milan

**Comment by mparadina** [comment]
Hi @phanikumar560 

Just wanted to make a follow-up here.

I version 5.8, we'added support for the `signatureImage` for the UAE ID and resident ID.
You can find the release here: https://github.com/BlinkID/blinkid-ios/releases/tag/v5.8.0

The process for obtaining the `signatureImage` is similar to getting the `fullDocumentImage`.
Example: `self.blinkIdRecognizer?.result.signatureImage?.image` for getting the UIImage of the signature.

Let me know if you have any additional questions.

Regards,
Milan

**Comment by mparadina** [comment]
Hi @phanikumar560 

As this issue is inactive, I am closing it.

If anything comes up, you can always reopen this issue, or create a new one.

Regards,
Milan
