### ISSUE TITLE
How to get image return from the scanning?

### ISSUE THREAD

**Issue by yltou** [BlinkID/blinkid-ios#32]
Hi,

Is it possible to only allow to capture the data if the whole passport was capture, so that the return result will be the passport image with the data.

Thanks

**Comment by Pickles112358** [comment]
Hello,

We would need additional info on the issue:
What do you mean when you say whole passport was captured?
If you are using our MRTD recognizer `PPMrtdRecognizerSettings` for scanning your passport you can:
Check whether result is passport by accessing this property:
https://github.com/BlinkID/blinkid-ios/blob/master/MicroBlink.framework/Headers/PPMrtdRecognizerResult.h#L34-L39

You can also fetch dewarped image of the document and the guide is available here under chapter "Retrieving dewarped images":
https://github.com/BlinkID/blinkid-ios/wiki/Using-BlinkID-recognizers

Kind regards,
Dino

**Comment by Cerovec** [comment]
Hello yltou,
please provide more details with the issue.
Kind regards,
Jurica.

**Comment by Rycicle** [comment]
The docs you linked to refer to this property of PPImageMetadata...

imageMetadata.imageType

But I can't access this property and can't see any reference to it anywhere? Has this changed by any chance? I'm wanting to get the fullDocumentImage from the delegate call... which I do! But I also get a few other images as well and was hoping to filter them somehow?

**Comment by Pickles112358** [comment]
This property is available in PPImageMetadata class:
https://github.com/BlinkID/blinkid-ios/blob/master/MicroBlink.framework/Headers/PPImageMetadata.h
