### ISSUE TITLE
Application crash after upgrading the microblink framework to version 5.7.1 from 4.9.1.

### ISSUE THREAD

**Issue by yo2bh** [BlinkID/blinkid-ios#322]
### Step 1: Are you in the right place?

  - For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with `BlinkID` and `Microblink` tags.

  - For issues or feature requests related to **the code in this repository**
    file a Github issue.

  - For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Microblink support](https://help.microblink.com/).

### Step 2: Describe your environment

  - Xcode version: Xcode 11.6
  - BlinkID SDK version: 5.7.1
  - What are you trying to scan: Emirates Id

### Step 3: Describe the problem

  - What happened? How can we make the problem occur and reproduce? This could be a description, log/console output, etc.

We're using Microblink version 4.9.1 in our application for scanning Emirates Id.
I am upgrading this version to the latest microblink version 5.7.1 and using the MBBlinkIdCombineRecoginzer.
but this will cause the application crashed while opening the custom camera view and getting below error on console.

### Step 4: Relevant code
I am using the sample app swift code for scanning the front and back emirates Id.

To configure the Custom overlay view.

```swift
  func configureCameraOverlayView(_ workFlowType: VerifyOTPWorkFlow) {
    blinkIdRecognizer = MBBlinkIdCombinedRecognizer()
//    emiratesIdFrontSide.faceImageDpi = 400
    blinkIdRecognizer.returnFullDocumentImage = true
    
    /** Crate recognizer collection */
    let recognizerList = [blinkIdRecognizer!]
    let recognizerCollection: MBRecognizerCollection = MBRecognizerCollection(recognizers: recognizerList)
    /** Create your overlay view controller */
    let customOverlayViewController: CameraOverlayViewController = CameraOverlayViewController.initFromStoryboardWith()
    
    customOverlayViewController.dismissCameraViewDelegate = self
    
    /** This has to be called for custom controller */
    customOverlayViewController.reconfigureRecognizers(recognizerCollection)
    
    /** Create recognizer view controller with wanted overlay view controller */
    guard let recognizerRunneViewController: UIViewController = MBViewControllerFactory.recognizerRunnerViewController(withOverlayViewController: customOverlayViewController) else {
      debugPrint("Failed to run the recognizer view")
      return
    }
    recognizerRunneViewController.modalPresentationStyle = .fullScreen
    self.present(recognizerRunneViewController, animated: true, completion: nil)
  }
```
To delegate methods

``` swift
  override func viewDidLoad() {
    super.viewDidLoad()
    super.scanningRecognizerRunnerViewControllerDelegate = self
    super.metadataDelegates.firstSideFinishedRecognizerRunnerViewControllerDelegate = self
  }

  func recognizerRunnerViewController(_ recognizerRunnerViewController: UIViewController & MBRecognizerRunnerViewController, didFinishScanningWith state: MBRecognizerResultState) {
    
    DispatchQueue.main.async {
      if state == .valid { 
        recognizerRunnerViewController.pauseScanning()
        recognizerRunnerViewController.playScanSuccessSound()
        for recognizer in self.recognizerCollection.recognizerList where
          recognizer.baseResult?.resultState == MBRecognizerResultState.valid {
            
            if recognizer is MBBlinkIdCombinedRecognizer {
              if let blinkIdRecognizer = recognizer as? MBBlinkIdCombinedRecognizer {
                let result = blinkIdRecognizer.result
                debugPrint("\(blinkIdRecognizer.result.description)")
              }
            }
        }
      }
      recognizerRunnerViewController.resumeScanningAndResetState(true)
    }
  }
  
  func recognizerRunnerViewControllerDidFinishRecognition(ofFirstSide recognizerRunnerViewController: UIViewController & MBRecognizerRunnerViewController) {
    // Change the label here.
  }

```
Please let me know what is the root cause of this issue and how to fix this?

**Comment by mparadina** [comment]
Hello @yo2bh 

Can you please take us through the steps on how did you integrate the SDK?
Did you do it via Cocoapods or did you do the integration process without them?

Also, did you `Embed&Sign` the `Microblink.xcframework`, and did you add the additional frameworks `libc++.tbd `, `libiconv.tbd`, and `libz.tbd` in the General section in your Xcode project?

This is shown in the guide here: https://github.com/BlinkID/blinkid-ios#integration-without-cocoapods

Let me know if that helped.

Regards,
Milan

**Comment by yo2bh** [comment]
All additional frameworks are already added to the project.
I have only replaced the Microblink.framework with the latest version.

That will create the issue while scanning, crashing the app as I mentioned in the above comment.

**Comment by yo2bh** [comment]
Is Microblink bundle required in Microblink 5.7.1?

**Comment by mparadina** [comment]
Hi @yo2bh 

The `Microblink.bundle` is not required in version 5.7.1 since it is now part of the `Microblink.framework` file. 

We recommend removing it since it is most likely connected with the issue you are currently experiencing.

Can you please let me know if removing the `.bundle` file helped?

Regards,
Milan

**Comment by yo2bh** [comment]
@mparadina - 
Yes, after removing the `Microblink.bundle`, the issue gets resolved.
hence closing this issue.
