### ISSUE TITLE
Fields like Height, EyeColor, HairColor are missing in MBBlinkIdRecognizerResult

### ISSUE THREAD

**Issue by Nikita-Kharde** [BlinkID/blinkid-ios#323]
- Xcode version:  11.1
  - BlinkID SDK version: 5.7.1
  - Trying to scan:  Driving License

I'm using MBBlinkIdRecognizer for scanning driving licenses. After scanning any license, I get a MBBlinkIdRecognizerResult in which few of the fields are missing like Height, EyeColor, HairColor etc. I get those fields in MBUsdlRecognizerResult when I use MBUsdlRecognizer for scanning. 
How can I get those fields in MBBlinkIdRecognizerResult.
Please help me with this, I would be grateful for your support.

**Comment by mparadina** [comment]
Hi @Nikita-Kharde 

Currently, those specific fields are not available with the BlinkID recognizer.

The reason for this is because the BlinkID recognizer is a generic recognizer, which contains a set of fields that are common for generally all types of documents that it currently supports reading. 
In this case, the information you've mentioned above are USDL specific.

This is why it does not return all of the fields which are located in the USDL. For extraction detailed, specific information from it, there is a recognizer specifically designed for it, and that is the USDL recognizer.

Can you please tell me more about your use-case?
This way we can come up with a conclusion which recognizer better suits your needs, once we have a better understanding of your use-case.

Also, please let me know if you have any additional questions.

Regards,
Milan

**Comment by Nikita-Kharde** [comment]
> Hi @Nikita-Kharde
> 
> Currently, those specific fields are not available with the BlinkID recognizer.
> 
> The reason for this is because the BlinkID recognizer is a generic recognizer, which contains a set of fields that are common for generally all types of documents that it currently supports reading.
> In this case, the information you've mentioned above are USDL specific.
> 
> This is why it does not return all of the fields which are located in the USDL. For extraction detailed, specific information from it, there is a recognizer specifically designed for it, and that is the USDL recognizer.
> 
> Can you please tell me more about your use-case?
> This way we can come up with a conclusion which recognizer better suits your needs, once we have a better understanding of your use-case.
> 
> Also, please let me know if you have any additional questions.
> 
> Regards,
> Milan

Thanks for the detailed information about the recognizers. I think usdl recognizer best suits our use-case.

**Comment by mparadina** [comment]
Hi @Nikita-Kharde 

If the USDL recognizer is right for you, I suggest taking a look at the `.getField()` ([documentation](http://blinkid.github.io/blinkid-ios/Classes/MBUsdlCombinedRecognizerResult.html#/c:objc(cs)MBUsdlCombinedRecognizerResult(im)getField:)) method with the USDL recognizer. This method takes the type  `MBUsdlKeys` which can return a specific value from the barcode located on the backside. 
For instance, you can get the [hair color](http://blinkid.github.io/blinkid-ios/Enums/MBUsdlKeys.html#/c:@E@MBUsdlKeys@HairColor) with the sample code below:
`var usdlRecognizer: MBUsdlRecognizer?`
`usdlRecognizer?.result.getField(MBUsdlKeys.HairColor)` (put this line in the part where you handle the scan results).

Hope this helps.

Regards,
Milan

**Comment by Nikita-Kharde** [comment]
> Hi @Nikita-Kharde
> 
> If the USDL recognizer is right for you, I suggest taking a look at the `.getField()` ([documentation](http://blinkid.github.io/blinkid-ios/Classes/MBUsdlCombinedRecognizerResult.html#/c:objc(cs)MBUsdlCombinedRecognizerResult(im)getField:)) method with the USDL recognizer. This method takes the type `MBUsdlKeys` which can return a specific value from the barcode located on the backside.
> For instance, you can get the [hair color](http://blinkid.github.io/blinkid-ios/Enums/MBUsdlKeys.html#/c:@E@MBUsdlKeys@HairColor) with the sample code below:
> `var usdlRecognizer: MBUsdlRecognizer?`
> `usdlRecognizer?.result.getField(MBUsdlKeys.HairColor)` (put this line in the part where you handle the scan results).
> 
> Hope this helps.
> 
> Regards,
> Milan

Thanks @Milan. Got those values as said.

**Comment by mparadina** [comment]
Hi @Nikita-Kharde 

Thank you for the feedback.

Is there anything else we can help you with?

Regards,
Milan

**Comment by Nikita-Kharde** [comment]
Hi @milan,
When we open camera for scanning a document, we get an intimation to scan the front side of a document but usually with MBUsdlRecognizer we can only scan the side where barcode is present and that is the back side of a document.
So can we change up with the message what we are showing right now?
Thanks,
Nikita

**Comment by mparadina** [comment]
Hi @Nikita-Kharde 

Of course, if you are using the `MBBlinkIdOverlayViewController`, create a `settings` variable that that refers to type `MBBlinkIdOverlaySettings`.

After creating it, tap into the `.firstSideInstructionsText`method and put your custom text.

Example code of what I am referring to:
```
 let settings: MBBlinkIdOverlaySettings = MBBlinkIdOverlaySettings()
 settings.firstSideInstructionsText = "Your Custom Text"
```
Hope this helps.

Regards,
Milan

**Comment by mparadina** [comment]
Hi @Nikita-Kharde 

I forgot to mention that the way shown above is alright, but it will not change with the device language. 
Meaning that you will put the same "hard-coded" string regardless of the device language.

To localize the string, I suggest looking at the guide [here](https://github.com/BlinkID/blinkid-ios#-localization).

Regards,
Milan

**Comment by mparadina** [comment]
Hi @Nikita-Kharde 

Just following up on the thread.

Did you manage to change the strings displayed on the scanning screen?

Let me know if you have any additional questions.

Regards,
Milan

**Comment by Nikita-Kharde** [comment]
Hi Milan,
Yes I was able to change the string displayed on the scanning screen successfully.
I will reach out to you if anything important. Your help was appreciable.
Thanks,
Nikita

**Comment by mparadina** [comment]
Hi @Nikita-Kharde 

Thank you for the feedback. :)

Closing the issue.

Regards,
Milan
