### ISSUE TITLE
Blinkid cordova - submit problems to app store - 

### ISSUE THREAD

**Issue by robertinmc** [BlinkID/blinkid-ios#324]
Hello we have a problem width the upload to Apple from our app that use BlinkId. 
When we make the archive we don't have any problem, in fact we can use the app to test. But when we upload the app to store to test on testfly we have this problem: 

 
![adjunto_1](https://user-images.githubusercontent.com/49195107/93999871-a7c74e80-fd96-11ea-8750-459553c4e8b4.jpg)

we found a similar issue  
https://github.com/BlinkID/blinkid-cordova/issues/30 

and we exec the commands without problems. 
But when upload again when have other error: 
 
![adjunto_2](https://user-images.githubusercontent.com/49195107/93999926-ba418800-fd96-11ea-989c-4473b7b6fd25.jpg)

please there are any solution for this issue.

**Comment by dCubelic** [comment]
Hi @robertinmc,

it is possible that Microblink.framework file got copied inside the bundle resources.
Can you check that Microblink.framework is NOT found under Project Settings -> Build Phases -> Copy Bundle Resources. If it is, try removing it and retrying the upload.

Best regards,
Dominik

**Comment by robertinmc** [comment]
Hello,
 if we remove microblink.frame in the project build, we can load but the application crash openning.   There's some problems with cordova authomatic generation.

![image](https://user-images.githubusercontent.com/49195107/94431091-23f5d380-0195-11eb-9313-38eb7f6eef9b.png)

**Comment by mparadina** [comment]
Hi @robertinmc 

What exception is displayed when the application crashes?

Regards,
Milan

**Comment by mparadina** [comment]
Hi @robertinmc 

Just to make a follow-up here.

To double-check, you can also test if the `Microblink` file has been renamed into `MicroBlink`​.
You can check this in` PackageContents/Frameworks/Microblink.framework/Microblink` file-path.

So, the file in the `Microblink.framework` folder must be named `Microblink`, not `MicroBlink`.
There could be a chance that some variables were hardcoded into the name `MicroBlink`.

If that is the case, I would suggest making a case-sensitive search and renaming every file and variable with the name `MicroBlink` to `Microblink`.

Let me know if this helps. 


Regards,
Milan

**Comment by mparadina** [comment]
Hi @robertinmc 

Closing the issue as it is inactive.
Feel free to reopen it, or create a new issue in case anything comes up!
