### ISSUE TITLE
Mismatch between iOS and Android results for Australia New South Wales Driver Licence

### ISSUE THREAD

**Issue by Out1and3r** [BlinkID/blinkid-ios#327]
Hi Team,

SDK: BlinkID SDK 5.7.0
Document: Australia New South Wales Driver Licence

Mismatch between Android and iOS class names and format for State Name:
iOS result: "Class Info Region" : "NewSouthWales"
Android result: "Class Region Name" : "NEW_SOUTH_WALES"

Tested using BlinkID Sample App

Could you please check this issue?

Also is there a rule when library use no separator or space or underscore(_) in the result?

Please let me know if you have any additional questions.
Thank you.

Regards,
Alex

**Comment by mijo-gracanin** [comment]
Hi @Out1and3r ,
iOS and Android SDKs follow naming conventions for their platforms. That's why there are some differences.
Can you work around the issue, like casting enums to int? We guaranty that region enums int value match on both platforms.

**Comment by AlexN-Join** [comment]
Hi @mijo-gracanin,

Thank you for your reply. Could you please point me to the documentation with region enums codes to "names" references?

**Comment by Out1and3r** [comment]
Hi @mijo-gracanin,

Thank you for your reply. Could you please point me to the documentation where links between enum int value and actual "region name" are set? So we could code those references for all documents in advance.

Thank you.

**Comment by mijo-gracanin** [comment]
@Out1and3r here you go: http://blinkid.github.io/blinkid-ios//Enums/MBRegion.html

**Comment by Out1and3r** [comment]
Thank you so much. Workaround works.
