### ISSUE TITLE
MBBlinkIdCombinedRecognizer missing mrzText in result

### ISSUE THREAD

**Issue by lucas-kummerle-perger** [BlinkID/blinkid-ios#328]
### Step 1: Are you in the right place?

  - For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with `BlinkID` and `Microblink` tags.

  - For issues or feature requests related to **the code in this repository**
    file a Github issue.

  - For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Microblink support](https://help.microblink.com/).

### Step 2: Describe your environment

  - Xcode version: 12.2
  - BlinkID SDK version: 5.8.0
  - What are you trying to scan: Passport

### Step 3: Describe the problem

- When using the `MBBlinkIdCombinedRecognizer` and scanning a passport the `mrzResult` contains an empty string for the `mrzText`, even though `isParsed` is `true` and other mrz information is also available, indicating that this was picked up correctly.

### Step 4: Relevant code

- The same issue occurs in your sample app. In the debugger type `po self.blinkIdRecognizer!.rpoesult.mrzResult.mrzText` once the passport has been scanned.

**Comment by mparadina** [comment]
Hi @lucas-kummerle-perger 

Would you mind telling me which passport are you trying to scan?
From which country?

Regards,
Milan

**Comment by lucas-kummerle-perger** [comment]
Hi @mparadina,

This is a German passport

**Comment by mparadina** [comment]
Hi @lucas-kummerle-perger 

Thank you for the swift response.

Can you try putting the `anonymizationMode` to `.none`?
The anonymization mode defines whether sensitive data should be removed from images, result fields, or both. 

It applies to the MRZ on the German passport.

You would need to implement this in the part when you initialize the BlinkID recognizer.

For instance:
```
self.blinkIdRecognizer = MBBlinkIdCombinedRecognizer()
self.blinkIdRecognizer?.anonymizationMode = .none
```

Let me know if this helped.

Regards,
Milan

**Comment by lucas-kummerle-perger** [comment]
Thank you for the quick response as well! That is working now. Is there more information available on exactly what data the anonymizationMode removes for other documents?

**Comment by mparadina** [comment]
Hi @lucas-kummerle-perger 

Yes, you can find all of the documents along with anonymized fields here:
https://github.com/BlinkID/blinkid-ios/blob/master/documentation/BlinkIDRecognizerResult.md#anonymized-fields

Let me know if there any additional questions.

Regards,
Milan
