### ISSUE TITLE
Unable to scan US state ID with MBIdBarcodeRecognizer

### ISSUE THREAD

**Issue by johnmillz** [BlinkID/blinkid-ios#329]
### Step 1: Are you in the right place?

  - For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with `BlinkID` and `Microblink` tags.

  - For issues or feature requests related to **the code in this repository**
    file a Github issue.

  - For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Microblink support](https://help.microblink.com/).

### Step 2: Describe your environment

  - Xcode version: 11.5
  - BlinkID SDK version: 5.8.0
  - What are you trying to scan: US state ID 

### Step 3: Describe the problem

  - What happened? When trying to scan the above document I cannot scan the first page. From the release notes, this recognizer replaces the `MBUsdlRecognizer`, however it doesn't seem like a drop-in replacement. Is there any additional configuration required to use this recognizer?

As a separate note, I see the image extraction interfaces are not applied to this recognizer which I believe the `MBUsdlRecognizer` was using to scan the front page - could this be related?

### Step 4: Relevant code

Should be reproducible by replacing `MBBlinkIdCombinedRecognizer` with `MBIdBarcodeRecognizer` and removing image extraction in the sample application.

**Comment by mparadina** [comment]
Hi @johnmillz 

Apologies for the delay in our response.

Can you please tell me from which state is the document?

Regards,
Milan

**Comment by johnmillz** [comment]
I've tried with Texas, New York, and Arkansas all of which scanned when using the deprecated `MBUsdlRecognizer`

**Comment by mparadina** [comment]
Hi @johnmillz 

With the IDBarcode recognizer, you can only obtain the information located on the barcode on the USDL (which is, in most cases, located on the backside of the document).
This recognizer does not take images of the document.

The USDL combined recognizer takes the image of the frontside of the document, and only reads the information from the backside of the DL.

If you require both images (front and backside of the document), I recommend trying out the BlinkID (Combined) recognizer, which can also extract information from the front and the backside of the DLs.

You can find more information about it here:
https://github.com/BlinkID/blinkid-ios#-blinkid-recognizers

Let me know if you have any additional questions.

Regards,
Milan

**Comment by johnmillz** [comment]
Thanks @mparadina, using the `MBBlinkIdCombinedRecognizer` I was able to scan most of my USA and Canadian test data. However, the New York State ID scans but returns null values for all of the textual fields, is this something you are able to reproduce?

**Comment by mparadina** [comment]
Hi @johnmillz 

Just to double-check, is the document a real sample, or a sample from the internet?

Also, which is its issue date?

Regards,
Milan

**Comment by johnmillz** [comment]
@mparadina These are all samples provided by a third-party company that specialises in ID document verification. They are images I'm displaying on a monitor rather than physical documents but a cut above what might be found from a web search. 

The issuing date is 09/20/2017

Cheers.

**Comment by johnmillz** [comment]
@mparadina any idea what might be happening in this instance?

**Comment by mparadina** [comment]
Hi @johnmillz 

Just to confirm, we should be reading the document properly.

However, I will need more information regarding the document to get a more detailed view of the issue.

When scanning the document, do you get any alert messages, for instance, "Document not supported", or is the scanner "stuck in a loop"?

I can also suggest trying out our Vision application (which you can download [here](https://apps.apple.com/us/app/microblink-vision/id1464662310)), and selecting the BlinkID > Worldwide Documents, to see if you can scan the document.

Regards,
Milan

**Comment by johnmillz** [comment]
Hi @mparadina using the vision application and selecting `BlinkID` > `Worldwide Documents` I can scan the document but the results screen displays 3 images and a message:

> "We don't support this document type in full, so, data extraction is not complete. Please contact sales for more information."

**Comment by mparadina** [comment]
Hi @johnmillz 

Thank you for the feedback.

If I correctly understood from the previous responses, the sample is not a real document?
If so, there could be a number of reasons why the SDK is struggling with extracting information from it since the SDK is trained on real documents.

For instance, the document could be in an invalid format or have some misplaced information when comparing it to the real document.
Also to add, you've mentioned that you're scanning the sample from a monitor screen, which can also make the scanning process more difficult since this type of scanning can produce the [Moire pattern](https://mathworld.wolfram.com/MoirePattern.html#:~:text=A%20Moir%C3%A9%20pattern%20is%20an,the%20other%20is%20held%20fixed.). This can also be a blocker from extracting the information from the document.

Did you maybe try scanning a real sample?

Regards,
Milan

**Comment by mparadina** [comment]
Hi @johnmillz 

Closing the issue as it is inactive.
Feel free to reopen it, or create a new issue in case anything comes up!
