### ISSUE TITLE
Unabled to scan passport and imm13 with MBBlinkIdRecognizer

### ISSUE THREAD

**Issue by jamesongchiyang** [BlinkID/blinkid-ios#333]
### Step 1: Are you in the right place?

  - For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with `BlinkID` and `Microblink` tags.

  - For issues or feature requests related to **the code in this repository**
    file a Github issue.

  - For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Microblink support](https://help.microblink.com/).

### Step 2: Describe your environment

  - Xcode version:  12.2.0
  - BlinkID SDK version: 5.9.0
  - What are you trying to scan:  Passport and Immi13

### Step 3: Describe the problem
I try to scan passport and immi13, but there is no response ( No feedback, can't recognise the passport and immi13). Previously, MBMrtdRecognizer able to recognize.

  - For passport and immi13, I update from MBMrtdRecognizer to MBBlinkIdRecognizer (MBMrtdRecognizer deprecated 5.8.0) and set following variable to true,
`allowUnverifiedMrzResults`
`allowUnparsedMrzResults`
`recognitionModeFilter.enableMrzPassport `
For immi13
`recognitionModeFilter.enableMrzVisa`

### Step 4: Relevant code
```var passportRecognizer : MBBlinkIdRecognizer?
self.passportRecognizer = MBBlinkIdRecognizer()
self.passportRecognizer?.returnFullDocumentImage = true;
self.passportRecognizer?.allowUnverifiedMrzResults = true;
self.passportRecognizer?.allowUnparsedMrzResults = true;
self.passportRecognizer?.anonymizationMode = .fullResult;
self.passportRecognizer?.recognitionModeFilter.enableMrzPassport = true;
```

```
var imm13Recognizer: MBBlinkIdRecognizer?
self.imm13Recognizer = MBBlinkIdRecognizer()
self.imm13Recognizer?.returnFullDocumentImage = true;
self.imm13Recognizer?.allowUnverifiedMrzResults = true;
self.imm13Recognizer?.allowUnparsedMrzResults = true;
self.imm13Recognizer?.recognitionModeFilter.enableMrzVisa = true;
```

Note: If I miss any setup, please advise me. Thank you.

**Comment by mparadina** [comment]
Hi @jamesongchiyang 

Can you please tell me which documents are you trying to scan?
From which countries?

Regards,
Milan

**Comment by jamesongchiyang** [comment]
Hi @mparadina 

scanning Philippine passport using MBBlinkIdRecognizer.
scanning Malaysia immigration passport using MBBlinkIdRecognizer.
All passport are sample record from internet resource.

Regards,
James

**Comment by mparadina** [comment]
Hi @jamesongchiyang 

Just to double-check, did you try scanning real documents?

Sometimes the samples from internet resources can have incorrect data formats (for instance, incorrectly shown Machine Readable Zone format), and the BlinkID recognizer can have a difficult time reading and extracting information from those samples. 

Regards,
Milan

**Comment by jamesongchiyang** [comment]
Hi @mparadina 

No we don't have any real documents to scan, thus we scanning from internet document resources.

I think is license key issue. My team just gave me a new license key which able for me to scan the passport however the imm13 issue still persist (Maybe is internet resources issue). 
Will take note on your advise. 
My team will contact your support if any issue related.
Thank you for your time. I will close this issue for now.

Regard,
James
