### ISSUE TITLE
Conflicting framework names: PDF417 and BlinkID Mobile SDK  

### ISSUE THREAD

**Issue by bratapfelmus** [BlinkID/blinkid-ios#334]
Hi Microblink team,

I'm raising this issue on behalf of the Jumio Mobile SDK (iOS), which currently integrates the Microblink **PDF417** SDK 7.0.0 for barcode reading. We've run into the problem of one of our customers already using **PPBlinkID** SDK 5.4.1 in their application for unrelated reasons. Now they are faced with the issue of conflicting names for 'microblink.framework'. 

Anything ideas on how to resolve this? 

Thanks, 
Bernadette

**Comment by anjapenic** [comment]
Hello Bernadette,

Please contact us at support@microblink.com, since the issue requires a specific solution regarding combining two SDKs in a single app.

Best regards,
Anja

**Comment by bratapfelmus** [comment]
@anjapenic will do, thanks!

**Comment by anjapenic** [comment]
Hello Bernadette,

Just a quick follow up, do you need help with anything else?

Regards,
Anja

**Comment by bratapfelmus** [comment]
@anjapenic issue has been resolved, thanks!
