### ISSUE TITLE
localizedName returning empty

### ISSUE THREAD

**Issue by matantech** [BlinkID/blinkid-ios#336]
**Step 2: Describe your environment**

iOS version1: 14.1
BlinkID SDK version: 5.8.0
What are you trying to scan: Israeli IDCard

**Step 3: Describe the problem**

I just started using the demo trial of BlinkID, with MBBlinkIdRecognizer on Native swift iOS app.
when scanning Israeli document the support on Hebrew letters seems to be missing.
I'm able to get the whole ID card or Driving License data except the Hebrew letters.
Please help
Thanks

**Comment by mparadina** [comment]
Hi @matantech 

Thank you for waiting for our response.

At the moment, we do not support reading Hebrew letters.

Currently, from the front side of the Israeli ID, we support reading the date of birth, date of expiry, date of issue, and the personal ID number, while on the backside, we support reading the document number.

Regarding the Israeli driver's license, we support reading the date of birth, date of expiry, date of issue, document number, first and last name, personal number, and vehicle class from the front side of the document.

Also to note, you can see the full list of which documents along with which fields we support reading with the BlinkID recognizer here:
https://github.com/BlinkID/blinkid-ios/blob/master/documentation/BlinkIDRecognizerResult.md
 
Let me know if this helped.

Regards,
Milan

**Comment by mparadina** [comment]
Hi @matantech 

Closing the issue as it is inactive.
Feel free to reopen it, or create a new one in case anything comes up.
