### ISSUE TITLE
recognizerRunnerViewController(withOverlayViewController) returns nil

### ISSUE THREAD

**Issue by lucas-kummerle-perger** [BlinkID/blinkid-ios#337]
### Step 2: Describe your environment

  - Xcode version: 12.4
  - BlinkID SDK version: 5.8.0
  - What are you trying to scan: 

### Step 3: Describe the problem

We are tracking an error for some users when calling `MBViewControllerFactory.recognizerRunnerViewController(withOverlayViewController: view)`, which is returning nil for them. The function documentation doesn't elaborate under what condition this returns nil. Please let us know what causes this.

**Comment by mijo-gracanin** [comment]
Hi @lucas-kummerle-perger ,
the function can return nil if `view.cameraSettings.cameraType` doesn't have a match in `AVCaptureDevice.devices(for: .video)`.
A sample project which demonstrates the issue would be most helpful.

**Comment by lucas-kummerle-perger** [comment]
Hi Mijo,
Thanks for clarifying. Unfortunately it's only happening to some customers and we cannot reproduce the issue, so we cannot provide any sample code.

**Comment by mparadina** [comment]
Hi @lucas-kummerle-perger 

Closing the issue as it is inactive.
Feel free to reopen it, or create a new issue in case anything comes up!
