### ISSUE TITLE
Missing ios-arm64_i386_x86_64-simulator in Microblink.xcframework

### ISSUE THREAD

**Issue by apps4everyone** [BlinkID/blinkid-ios#338]
Trying to run on M1 Simulator with latest Xcode.
Therefore the `ios-arm64_i386_x86_64-simulator` in missing in `Microblink.xcframework`

Xcode version: latest/AppStore
BlinkID SDK version: latest/master

This is also for https://github.com/BlinkID/blinkid-swift-package

**Comment by mparadina** [comment]
Hi @apps4everyone 

With version 5.9.0 we did not have the support for M1 Simulators.
However, we've released version 5.10.0, which supports running them.

You can download and test it here:
https://github.com/BlinkID/blinkid-ios/releases/tag/v5.10.0

Regards,
Milan

**Comment by apps4everyone** [comment]
thx, great (and fast) job
