### ISSUE TITLE
Example of usage of MBBlinkIdOverlayTheme 

### ISSUE THREAD

**Issue by radimmotycka** [BlinkID/blinkid-ios#344]
Hi,

Please would you advise how to use MBBlinkIdOverlayTheme?
I have no clue where to instantiate it or pass it as an argument?
Please how can I use that class in the printscreen below. 
Didnt get it from the documentation :( it only states "To customize MBBlinkIdOverlayViewController, use MBBlinkIdOverlayTheme class to customize your look." but HOW, WHERE?

Many thans

<img width="887" alt="Screen Shot 2021-03-18 at 1 24 18 PM" src="https://user-images.githubusercontent.com/65539674/111625578-4a640580-87ed-11eb-9441-2423499118d7.png">

**Comment by TCvetkovic** [comment]
Hi @radimmotycka.

You can use it like this:
```swift
MBBlinkIdOverlayTheme.shared().instructionsTextColor = .red
MBBlinkIdOverlayTheme.shared().successFlashColor = .green
```

This is just an example. It is possible to customize fonts, colors, images, and corner radius.

**Comment by TCvetkovic** [comment]
Hi @radimmotycka ,

I hope my answer helped you. As this issue is inactive, I am closing it. 
If anything comes up, feel free to reopen this or create a new issue.
