### ISSUE TITLE
Front or Back

### ISSUE THREAD

**Issue by soledue** [BlinkID/blinkid-ios#347]
hello,
how to recognize which side of the document is scanned?

**Comment by TCvetkovic** [comment]
Hi @soledue,

It is not possible to recognize when is which side of the document scanned. 
It possible to recognize when the document is completely scanned and results confirmed by using the delegate method: 
`func verifyDidFinishScanningID(_ verifyViewController: UIViewController, combinedRecognizer: MBBlinkIdCombinedRecognizer, verifyItem: MBVerifyItem)`

**Comment by mparadina** [comment]
Hi @soledue 

If you are using the BlinkID Combined recognizer, it always firstly requires the front side of the document, and when it extracts all of the necessary information, then it proceeds to the backside.

More information here:
https://github.com/BlinkID/blinkid-ios#-blinkid-combined-recognizer

You can also check if the wrong side of the document is trying to be scanned with the processing status feature, with the BlinkID Combined's result.

Documentation: 
http://blinkid.github.io/blinkid-ios/Enums/MBProcessingStatus.html#/c:@E@MBProcessingStatus@MBProcessingStatusScanningWrongSide

An example code would be:
```
let processingStatus = self.blinkIdRecognizer?.result.processingStatus
            
if processingStatus! == .scanningWrongSide {
print("Scanning wrong side!")
  }
```

Let me know if this helped.

Regards,
Milan

**Comment by soledue** [comment]
do you have an example where MBBlinkIdCombinedRecognizer is used?

**Comment by mparadina** [comment]
You can see the example of the usage of the `MBBlinkIdCombinedRecognizer` in the `ViewController.swift` in our `BlinkID-Sample-Swift` sample here:
https://github.com/BlinkID/blinkid-ios/blob/master/Samples/BlinkID-sample-Swift/BlinkID-sample-Swift/ViewController.swift

There you have, for example, how and where to create it and how to handle its results when the scanning process has been finished.

Let me know if you have any additional questions.

Regards,
Milan

**Comment by soledue** [comment]
thank you
