### ISSUE TITLE
Individually Scan and capture ID document irrespective of theirs sides.

### ISSUE THREAD

**Issue by Nandhunandhu** [BlinkID/blinkid-ios#348]
Hi, 
	I’m working in a project where I need to scan and capture either front or back side of an ID.
(I.e) I have two image views. In the first one I need to show the front side of the ID and the back side of the ID in the second image view.

I want to scan an ID document and then capture the ID document image only, it may be front or back.
I have tried this with MicroBlink SDK’S documentOverlayViewController and its delegates.In that, I am facing two difficulties.

1. I can get the entire camera frame image, but not the ID document image alone.
2. I can scan and capture either the front side only or front and back together. In short , I just need to capture and show the rectangular sized objects irrespective of their sides (front or back).

  Here’s my code, 
  
  //MARK: - Scan Document View controller
  
           class ScanDocViewController: MBDocumentOverlayViewControllerDelegate {  
           
               IBOutlet weak var imageView: UIImageView!
               var blinkIDRecognizer: MBBlinkIdRecognizer?
                
                   func openScanVc() {
                             self.blinkIDRecognizer = MBBlinkIdRecognizer() 
                           self.blinkIDRecognizer?.returnFullDocumentImage = true
           
                                /** Create settings **/
                   let settings: MBDocumentOverlaySettings = MBDocumentOverlaySettings()
                   settings.captureHighResImage = true
       	           settings.tooltipText.removeAll()
	           settings.tooltipText.append("Position the ID to capture")  
	
                  /** Create recognizer collection **/
                  let recognizerList = [self.blinkUnCombined!]
         	 let recognizerCollection: MBRecognizerCollection = MBRecognizerCollection(recognizers: recognizerList)  	
       	
       	         /** Create your overlay view controller **/
                  let documentOverlayViewController: MBDocumentOverlayViewController =
                   MBDocumentOverlayViewController(settings: settings, recognizerCollection: recognizerCollection, delegate: self)

                 /** Create recognizer view controller with wanted overlay view controller **/
                  guard let recognizerRunnerViewController: UIViewController = 
                                          MBViewControllerFactory.recognizerRunnerViewController( 
                                          withOverlayViewController: documentOverlayViewController) 
                  else {
                          return
                   } 		 	
                   recognizerRunnerViewController.modalPresentationStyle = .fullScreen

                   /**Present the recognizer runner view controller. **/
                   /** You can use other presentation methods as well (instead of presentViewController) **/
                      self.present(recognizerRunnerViewController, animated: true, completion: nil)
         
         }

//MARK: - MBDocumentOverlayViewControllerDelegate 

          func documentOverlayViewControllerDidFinishScanning(_ documentOverlayViewController: MBDocumentOverlayViewController, state: MBRecognizerResultState) {
                 print("scanned")
           }

          func documentOverlayViewControllerDidCaptureHighResolutionImage(_ documentOverlayViewController: MBDocumentOverlayViewController, highResImage: MBImage) {

                  if let image = highResImage.image {
		       self.imageView.image = image
                 }
           }

           func documentOverlayViewControllerDidTapClose(_ documentOverlayViewController: MBDocumentOverlayViewController){
               self.dismiss(animated: true, completion: nil)
         } 
    
    
    In the above code, if I’m using “MBBlinkIdRecognizer”, I can scan and capture only the front side but not the back side. And if I’m using “MBBlinkIdCombinedRecognizer”, I can scan both sides together like one after another(As "MBBlinkIdCombinedRecognizer" scans the front side and asks the user to flip the card to scan the back side). 

So, kindly share some ideas to solve those difficulties.  
Thanks in advance.

Regards,
Nandhini

**Comment by mparadina** [comment]
Hi @Nandhunandhu 

Thank you for waiting for our response.

So, if I've understood everything correctly regarding the first question, you want to get the whole camera frame when the recognition has finished, not just the `fullDocumentImage`?

If this is the case, I recommend using the `MBSuccessFrameGrabberRecognizer`, which retrieves the whole camera frame image. 
More information here:
https://github.com/BlinkID/blinkid-ios#-success-frame-grabber-recognizer

If you only want to get the document image, I recommend implementing this code in the `documentOverlayViewControllerDidFinishScanning` method:

```
 func documentOverlayViewControllerDidFinishScanning(_ documentOverlayViewController: MBDocumentOverlayViewController, state: MBRecognizerResultState) {
             print("scanned")
            //frontside image
           let fullDocumentFrontImage: UIImage! = self.blinkIdRecognizer?.result.fullDocumentFrontImage?.image
            //backside image
            let fullDocumentBackImage : UIImage! = self.blinkIdRecognizer?.result.fullDocumentBackImage?.image
            
            DispatchQueue.main.async {
                imageView.image = fullDocumentFrontImage // or fullDocumentBackImage
            }
       }
```

Regarding the second question, I'm not sure if I've understood it correctly. 
However, this is my understanding: 
With the BlinkID recognizer, you can capture only the front side of the document, while with the BlinkID Combined, you can capture both the front and backside of the document. There is currently no option for separately scanning the backside.

You can read more about the differences regarding these two recognizers here:
https://github.com/BlinkID/blinkid-ios#-blinkid-recognizer

If I correctly understood, you want to pause the scanning process, display the scanned image to the end-user, and then proceed to the scanning process of the backside?

Regards,
Milan

**Comment by mparadina** [comment]
Hi @Nandhunandhu 

Closing the issue as it is inactive.
Feel free to reopen it, or create a new issue if anything comes up!
