### ISSUE TITLE
import BlinkID, when I installed the git lfs and the Pod, once I have imported the library, I am always getting this error, even I cleaned up and close the project and other stuff, what can I do?

### ISSUE THREAD

**Issue by moMMoSadeghi** [BlinkID/blinkid-ios#349]
### Step 1: Are you in the right place?

  - For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with `BlinkID` and `Microblink` tags.

  - For issues or feature requests related to **the code in this repository**
    file a Github issue.

  - For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Microblink support](https://help.microblink.com/).

### Step 2: Describe your environment

  - Xcode version: 
  - BlinkID SDK version:
  - What are you trying to scan: 

### Step 3: Describe the problem

  - What happened? How can we make the problem occur and reproduce? This could be a description, log/console output, etc.

### Step 4: Relevant code

```swift
// TODO(you): code here to reproduce the problem
```

**Comment by mparadina** [comment]
Hi @iMoei 

Can you please tell me which error are you getting after you've installed the SDK into your project?
Would you mind pasting it here again? It looks like the error was not presented in your response.

Regards,
Milan

**Comment by iMoei** [comment]
No such module 'BlinkID'

it says, no module.

**Comment by mparadina** [comment]
Thank you for the swift response @iMoei

When importing BlinkID into your project, you need to import Microblink, not BlinkID.

So `import Microblink`  should solve the issue.

You can see the example here:
https://github.com/BlinkID/blinkid-ios/blob/master/Samples/BlinkID-sample-Swift/BlinkID-sample-Swift/ViewController.swift#L10

Let me know if it helped.

Regards,
Milan

**Comment by iMoei** [comment]
> import Microblink

No such module 'Microblink'

I tried that, and nothing has changed. both not recognised.

**Comment by mparadina** [comment]
@iMoei can you please inspect the size of the `Microblink.xcframework`, which was obtained via CocoaPods, and share the size here?

Just to double-check, did you maybe notice any exceptions/errors when you ran the `pod install` command when you've obtained the SDK?

Lastly, after you've cleaned the project, have you maybe tried building the project to see if the "No such module" will still be presented?

Regards,
Milan

**Comment by iMoei** [comment]
yes, the size of the app is 179.9 MB.
the size of Blink Test.xcworkspace is 23Kb. It is awkward. 
and here is the message of terminal. 
![IMAGE 2021-06-02 16:37:01](https://user-images.githubusercontent.com/37694875/120500324-0da5b480-c3c1-11eb-8040-403931100733.jpg)

**Comment by iMoei** [comment]
@mparadina 
In meanwhile I deleted the project and build a new one, here I have two errors, and now there is another added,

" framework not found Microblink.xcframework"

**Comment by mparadina** [comment]
@iMoei 

From the Terminal screen, there seem to be no issues.

To double-check, which version of CocoaPods are you using?
When you open the `Pods` folder, is the `Microblink.xcframework` located there?

Also to ask, if you've added other frameworks in your projects, have they all been installed properly? 
Only BlinkID is causing issues?

Regards,
Milan

**Comment by iMoei** [comment]
@mparadina 
Yes, only this pod, I decided not to use it, because it makes me so many troubles.

**Comment by mparadina** [comment]
@iMoei I'm sorry to hear that you've decided not to implement the SDK due to implementation difficulties.

If it's possible, you can contact us directly at support@microblink.com and we can schedule a call to go through the issue and find the solution.

Also, let me know if you have any additional questions.

Regards,
Milan

**Comment by mparadina** [comment]
Hi @moMMoSadeghi 

Closing the issue as it is inactive.
Feel free to reopen it, or create a new one in case anything comes up!
