### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by dfeinzimer** [BlinkID/blinkid-ios#353]
### Step 1: Are you in the right place?

N/A

### Step 2: Describe your environment

N/A

### Step 3: Describe the problem

The integration documentation in README.md in this repo appers to be outdated. [This section](https://github.com/BlinkID/blinkid-ios#2-referencing-header-file) states the import statement to be `import BlinkID` where it is actually `import Microblink`.

### Step 4: Relevant code

N/A

**Comment by mijo-gracanin** [comment]
Hi @kernelpop , thanks for reporting this. We'll update the documentation along with the next release.

**Comment by mparadina** [comment]
Hi @dfeinzimer 

Closing the issue as it is inactive.
Feel free to reopen it, or create a new issue in case anything comes up!
