### ISSUE TITLE
Extraction didn't completed when connected to pulse secure

### ISSUE THREAD

**Issue by Mithlesh-Navlakhe** [BlinkID/blinkid-ios#357]
Below are the detail of tools and version of BlinkId we are using

  - Xcode version: 12.4
  - BlinkID SDK version: 5.10.0
  - What are you trying to scan: National Identity 

The problem we are facing
  - Scanning is not working(keeps on loading) while user is connected to pulse secure. This issue happens only in IOS, android it's working fine.

**Comment by mparadina** [comment]
@Mithlesh-Navlakhe is it alright with you to close the issue since you've found out what seemed to cause the scanning issue?

**Comment by Mithlesh-Navlakhe** [comment]
@mparadina Yes, you can close it. Thanks for the help.

**Comment by mparadina** [comment]
Thank you @Mithlesh-Navlakhe. Closing the issue.
