### ISSUE TITLE
I am not able to download the PPBlinkId v5.14.0 using this link:- https://github.com/BlinkID/blinkid-ios/releases/download/v5.14.0/blinkid-ios_v5.14.0.tar.gz  it returns Error 503 Backend.max_conn reached. Please check    

### ISSUE THREAD

**Issue by assharma** [BlinkID/blinkid-ios#358]
### Step 1: Are you in the right place?

  - For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with `BlinkID` and `Microblink` tags.

  - For issues or feature requests related to **the code in this repository**
    file a Github issue.

  - For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Microblink support](https://help.microblink.com/).

### Step 2: Describe your environment

  - Xcode version: 
  - BlinkID SDK version:
  - What are you trying to scan: 

### Step 3: Describe the problem

  - What happened? How can we make the problem occur and reproduce? This could be a description, log/console output, etc.

### Step 4: Relevant code

```swift
// TODO(you): code here to reproduce the problem
```

**Comment by mparadina** [comment]
Hi @assharma 

We've tried reproducing the issue on our end, but we can successfully obtain the tar.gz file from Releases.
Can you please try downloading the file again to see if the issue was resolved?

**Comment by mparadina** [comment]
Hi @assharma 

Closing the issue as it is inactive.
Feel free to reopen it, or create a new issue if anything comes up!
