### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by ashrafessam** [BlinkID/blinkid-ios#360]
Is there is any plan to add egyptian national ID and saudian National ID?

**Comment by mparadina** [comment]
Hi @ashrafessam 

We support reading both the Egypt ID and the Saudi Arabia ID documents.
To be more exact these are the fields we support reading:

**Egypt ID front side**: document number and the personal ID number
**Egypt ID backside**: date of issue, personal ID number and the date of expiry

**SA ID front side**: date of birth, date of expiry, document number, date of issue and the full name.
**SA ID backside**: MRZ 

This information, along with other documents and fields we support reading can be found [here](https://github.com/BlinkID/blinkid-ios/blob/master/documentation/BlinkIDRecognizerResult.md#all-fields).

Let me know if you have any additional questions.

**Comment by ashrafessam** [comment]
Thank you so much

**Comment by mparadina** [comment]
@ashrafessam of course, glad I could help.

Is there maybe anything else I can assist you with?

**Comment by ashrafessam** [comment]
No Thanks

**Comment by ashrafessam** [comment]
I want to know the price for production license

**Comment by mparadina** [comment]
For more detailed information regarding the price and the purchase of the license key, I recommend contacting our Sales team at sales@microblink.com.
The team will give you a more detailed response on how to acquire the key.

Let me know if there is anything else you need assistance with.

**Comment by mparadina** [comment]
Hi @ashrafessam 

Closing the issue as it was resolved.
Feel free to reopen it, or create a new issue in case anything comes up!
