### ISSUE TITLE
No versions of 'blinkid-swift-package' match the requirement 5.15.2..<6.0.0

### ISSUE THREAD

**Issue by gevorgyanvahagn** [BlinkID/blinkid-ios#365]
### Step 1: Are you in the right place?

  - ❌ For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with `BlinkID` and `Microblink` tags. 

  - ✅ For issues or feature requests related to **the code in this repository**
    file a Github issue.

  - ❌ For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Microblink support](https://help.microblink.com/).

### Step 2: Describe your environment

  - Xcode version: 13.3
  - BlinkID SDK version: 5.15.2

### Step 3: Describe the problem

I've added a SPM dependency to my local package:
`.package(name: "BlinkID", url: "https://github.com/BlinkID/blinkid-swift-package", from: "5.15.2")`

and Xcode fails resolving package dependancies with an error:
`Dependencies could not be resolved because no versions of 'blinkid-swift-package' match the requirement 5.15.2..<6.0.0 and root depends on 'blinkid-swift-package' 5.15.2..<6.0.0.`

When I change the version to `5.15.1` it works perfectly.

**Comment by mparadina** [comment]
Hi @gevorgyanvahagn 

We are aware of the issue regarding SPM and the 5.15.2 version.
The issue will be fixed in 5.16.0, and until then, the solution would be to revert back to the 5.15.1 version.

I will update you here once the release is out.

**Comment by gevorgyanvahagn** [comment]
@mparadina  thanks for response!

**Comment by mparadina** [comment]
@gevorgyanvahagn, we've released BlinkID 5.16.0, which you can find [here](https://github.com/BlinkID/blinkid-ios/releases/tag/v5.16.0).

Can you please try obtaining it via SPM and let me know if it is now working as expected?

**Comment by gevorgyanvahagn** [comment]
@mparadina  yes, it is working as expected, thank you
