### ISSUE TITLE
Templating - Sample doesn't work 

### ISSUE THREAD

**Issue by diana622ster** [BlinkID/blinkid-ios#37]
Hi 

I'm testing the Templating Sample bu using the ID card which attached in the projet. but  it doesn't seem to work. 
Always get the same error as below, seems the location of "ID_DOCUMENT_NUMBER" is not correct  or maybe i missed something else.

WTF] buildDateRegex [DateParserFactory.cpp:304] 2016-08-24 11:43:48.653 Templating-Sample[5674:3616329] Unknown date format for date parser!

[W] validateParser [TemplatingRecognitionData.cpp:85] 2016-08-24 11:44:01.027 Templating-Sample[5674:3616330] Required parser 'DocumentNumber' from parser group 'DocumentNumberNew' did not produce result!

[W] validateParser [TemplatingRecognitionData.cpp:85] 2016-08-24 11:44:01.269 Templating-Sample[5674:3616330] Required parser 'LastName' from parser group 'LastName' did not produce result!

[W] validateParser [TemplatingRecognitionData.cpp:85] 2016-08-24 11:44:01.513 Templating-Sample[5674:3616330] Required parser 'Sex' from parser group 'SexCitizenshipDob' did not produce result!

[W] validateParser [TemplatingRecognitionData.cpp:85] 2016-08-24 11:44:01.849 Templating-Sample[5674:3616330] Required parser 'Citizenship' from parser group 'SexCitizenshipDob' did not produce result!

.....

Could you please help me on this ?  

Do you have any document to explain how to define the location and dewarpedHeight of ID document ? 

thanks in advance for your help.

**Comment by Pickles112358** [comment]
Hello,

We have updated our Templating-sample last week. If the one before did not work for any reason, this one should.

Kind regards,
Dino

**Comment by Cerovec** [comment]
Hi,
please check if the sample still doesn't work as expected. If it does, please close the issue.
Jurica.
