### ISSUE TITLE
MicroBlink Version

### ISSUE THREAD

**Issue by vtaneeru** [BlinkID/blinkid-ios#38]
Hello,
   How can I check micro blink framework version number?

I am seeing different issues based on the version I am using.
1) If I use latest version via cocoa pods/add framework I am getting many reference errors
This  https://github.com/BlinkID/blinkid-ios/issues/27 solved my issue by getting v.2.1.0 and able to build with out compile errors
2) With v2.1.0 I am getting license error even though I use the right key.

Which is the stable version I can use?

**Comment by Pickles112358** [comment]
Hello,

Version number can be checked like this:
[PPCoordinator buildVersionString];

Kind regards,
Dino
