### ISSUE TITLE
Error with Argument 'self'

### ISSUE THREAD

**Issue by AlfredoMayFire** [BlinkID/blinkid-ios#40]
I'm writing in regards to an error I'm getting.

In the "Getting Started" section, step 4 I'm getting an error when implementing the code.(I've already successfully installed the dependency through cocoapods)

Here's the line of code producing the error.

`let scanningViewController: UIViewController = PPViewControllerFactory.cameraViewControllerWithDelegate(self, coordinator: coordinator!, error: nil)`

Here's the error

/Users/a.pomales/Desktop/AppleDev/Scanner/Scanner/DetailViewController.swift:120:113: Argument type 'DetailViewController' does not conform to expected type 'PPScanningDelegate'

Any help would be greatly appreciated?

**Comment by Pickles112358** [comment]
The problem here is that your DetailViewController does not conform to protocol PPScanningDelegate (available here: https://github.com/BlinkID/blinkid-ios/blob/master/MicroBlink.framework/Headers/PPScanningDelegate.h)
Your DetailViewController needs to conform to it and implement it's mandatory methods

Kind regards,
Dino

**Comment by AlfredoMayFire** [comment]
How do I implement this in a swift project? Isn't that code you linked written in objective-c Sorry if it's an obvious question, I'm just starting out.

**Comment by Pickles112358** [comment]
I suggest looking at our Swift demo apps and start by adding your functionality to them. One of them is available here:
https://github.com/BlinkID/blinkid-ios/tree/master/Samples/BlinkID-sample-Swift

I'd also suggest looking through Apple's Swift programming manual available here:
https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/index.html#//apple_ref/doc/uid/TP40014097-CH3-ID0

It contains all useful information about aspects of iOS development in Swift.

Kind regards,
Dino

**Comment by AlfredoMayFire** [comment]
Hi, just needed to include PPScanningDelegate to the statement class ViewController: UIViewController, PPScannignDelegate {
