### ISSUE TITLE
unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by ratzr15** [BlinkID/blinkid-ios#43]
I'm using BlinkID in my swift file of ObjC project (using bridging headers)

 function signature specialization <preserving fragile attribute, Arg[1] = [Closure Propagated : reabstraction thunk helper from @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> () to @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> (@out ()), Argument Types : [@callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> ()]> of generic specialization <preserving fragile attribute, ()> of Swift.StaticString.withUTF8Buffer <A> ((Swift.UnsafeBufferPointer<Swift.UInt8>) -> A) -> A

**Comment by Cerovec** [comment]
Hi,
can you please describe in more detail what's the issue? Is this a crash?
Can you create a small sample app which demonstrates this so we can recreate it on our end?

**Comment by Cerovec** [comment]
Hi,
please check the new release v2.5.1 where nullability attributes were corrected for all result classes.
BR,
Jurica.

**Comment by ratzr15** [comment]
Sure, Thank you

**Comment by Cerovec** [comment]
Hi,
please let us know if this issue is still open even after v2.5.1 and v2.6.0.
Best,
Jurica.

**Comment by Cerovec** [comment]
Hi,
any news on this?
Thanks!

**Comment by juraskrlec** [comment]
Closed as inactive
