### ISSUE TITLE
No detection on black background 

### ISSUE THREAD

**Issue by nicoduj** [BlinkID/blinkid-ios#46]
Hi,

It seems that recognition of documents like ID Card on black background doesn't work at all. On white background it always performs ok . Any change on that ? I tested on 2.4 / 2.5, same problem, but I a m quite sure that it worked before.

White background sample that works fine  (masked for sharing purpose) :
![img_1080](https://cloud.githubusercontent.com/assets/19813688/21224812/401f5130-c2ce-11e6-86d1-fe809a92d75e.JPG)
Black background that doesn't work (no recognition from MRTDRecognizer) : 
![img_3390](https://cloud.githubusercontent.com/assets/19813688/21224830/512477bc-c2ce-11e6-86b2-a9551bab9ca3.JPG)

My code for setting the recognizer :  

    PPSettings *settings = [[PPSettings alloc] init];
    settings.licenseSettings.licenseKey = blinkIDapiKey;
    settings.metadataSettings.dewarpedImage = YES; // get dewarped image of ID documents
        PPMrtdRecognizerSettings *mrtdRecognizerSettings = [[PPMrtdRecognizerSettings alloc] init];
        mrtdRecognizerSettings.dewarpFullDocument = YES;
        if (unparsedResults) // doesn't work if YES or NO
            mrtdRecognizerSettings.allowUnparsedResults = YES;
        // Add MRTD Recognizer setting to a list of used recognizer settings
        [settings.scanSettings addRecognizerSettings:mrtdRecognizerSettings];

**Comment by nicoduj** [comment]
Anyone has any idea about this issue ?

**Comment by mvayngrib** [comment]
i'm experiencing the same issue

**Comment by Cerovec** [comment]
Hi,
sorry, but unfortunately we cannot recreate that issue on our end. With our passports we don't have issues detecting MRTD documents on black backgrounds. And these samples we cannot use because of the deleted areas.
Do you still have the same issue on version 2.6.0? 

Best,
Jurica.

**Comment by nicoduj** [comment]
Hi, I planed to check on latest version by the end of the week. Meanwhile, I can send to you my photo without deleted areas if you want.

**Comment by Cerovec** [comment]
We double checked - on that example, the detection of the Machine readable zone has issues because of the image preprocessing step. Because we stretch the contrast of the image, and since the background is the darkest part of the image, the MRZ part actually loses some of the characters. And this makes the detector fail.

We won't be able to do a quick fix here - our core team will have to take a deeper look.

**Comment by culoi** [comment]
Closing the issue, this was solved in the new version of the BlinkID. 
Please reopen if you have additional questions or contact us directly at support@microblink.com
