### ISSUE TITLE
Dewarp passport

### ISSUE THREAD

**Issue by vladimirzivanov** [BlinkID/blinkid-ios#47]
How to dewarp passport? In yours sample apps i saw 'Detector-sample' which dewarp personal id and driver license. For passport just took a image but it doesn't dewarp. Can I do that?

**Comment by DoDoENT** [comment]
You can try [this example](https://github.com/BlinkID/blinkid-ios/tree/master/Samples/BlinkID-sample/BlinkID-sample), but also enable returning of dewarped image as described [here](https://github.com/BlinkID/blinkid-ios/wiki/Using-MRTD-recognizer).

**Comment by vladimirzivanov** [comment]
How to see the image which is scaning?

**Comment by DoDoENT** [comment]
After obtaining PPImageMetadata as explained in link above, you can get UIImage from its [image property](http://cocoadocs.org/docsets/PPBlinkID/2.5.1/Classes/PPImageMetadata.html#//api/name/image). You can then display this UIImage as you wish.

**Comment by vladimirzivanov** [comment]
Thanks. Can i somehow get whole image which is procesing (from camera, not croped) and get bounds of object if is it recognized(in coordinate)?

**Comment by DoDoENT** [comment]
Yes, you can. To obtain every video frame as PPImageMetadata, enable receiving of [currentFrame](http://cocoadocs.org/docsets/PPBlinkID/2.5.1/Classes/PPMetadataSettings.html#//api/name/currentFrame). To obtain frame that was used to obtain successful recognition, enable receiving of [successfulFrame](http://cocoadocs.org/docsets/PPBlinkID/2.5.1/Classes/PPMetadataSettings.html#//api/name/successfulFrame).

**Comment by vladimirzivanov** [comment]
Thanks for all. And how to get coordinates of recognized object on successful frame?

**Comment by DoDoENT** [comment]
Yes, it is possible. You just need to implement [scanningViewController:didFinishDetectionWithResult:](http://cocoadocs.org/docsets/PPBlinkID/2.5.1/Protocols/PPScanningDelegate.html#//api/name/scanningViewController:didFinishDetectionWithResult:)

**Comment by zjoka** [comment]
We are trying to understand how PPDetectorResult works. For example if we use PPQuadDetectorResult.detectionLocation to get coordinate points, how to actually use return value to show corner points on screen. Example code below give us strange results. 

`
override func cameraViewController(_ cameraViewController: UIViewController, didFinishDetectionWith result: PPDetectorResult) {
        if let docResult = result as? PPQuadDetectorResult {
            if result.status == PPDetectionStatus.success{
                let p = docResult.detectionLocation
                topLeftView.frame = CGRect(x: p.upperLeft.x, y: p.upperLeft.x, width: 5, height: 5)
                topRightView.frame = CGRect(x: p.upperRight.x, y: p.upperRight.y, width: 5, height: 5)
                bottomLeftView.frame = CGRect(x: p.lowerLeft.x, y: p.lowerLeft.y, width: 5, height: 5)
                bottomRightView.frame = CGRect(x: p.lowerRight.x, y: p.lowerRight.y, width: 5, height: 5)
            }
        }
    }
`

**Comment by DoDoENT** [comment]
The coordinates in PPQuadDetectorResult.detectionLocation are given in image's coordinate sytem. To transform those coordinates into screen coordinate system, use [transform](http://cocoadocs.org/docsets/PPBlinkID/2.5.1/Classes/PPDetectorResult.html#//api/name/transform) property.
