### ISSUE TITLE
Will release the Malaysia iKad recognizer for ios version?

### ISSUE THREAD

**Issue by leeyikkong** [BlinkID/blinkid-ios#53]
Hi, may I know when will release or is it will release the iKad recognizer for ios version?

Thank you

**Comment by culoi** [comment]
Hello @leeyikkong 

iKad recognizer was added in version [1.2](https://github.com/BlinkID/blinkid-ios/blob/master/Release%20notes.md#120)

Added recognition of Malysian ID cards (MyKads). To use MyKad recognition initialize the scanning library using [PPMyKadRecognizerSettings](https://github.com/BlinkID/blinkid-ios/blob/master/MicroBlink.framework/Headers/PPMyKadRecognizerSettings.h)

**Comment by leeyikkong** [comment]
so it is under the MykadrecognizerSettings? I found it the iKadRecognizer is added in version 2.5.0

thank you
