### ISSUE TITLE
US license scanning issue

### ISSUE THREAD

**Issue by mvayngrib** [BlinkID/blinkid-ios#55]
doesn't scan well unless the barcode is centered, rather than the whole id card

**Comment by culoi** [comment]
Hi @mvayngrib 

Just point the camera of the device towards the barcode and everything should be read automatically.

Can you please send us a short video or image that you are trying to scan?

**Comment by mvayngrib** [comment]
@culoi I'm scanning the below image. The hint says "Position ID card in this frame" but it doesn't scan the barcode until I center the *barcode* in the frame. Since I want to get the dewarped ID card, I don't want to center just the barcode

https://dmv.ny.gov/sites/default/files/styles/panopoly_image_original/public/dl_back_hilights_text_0.png?itok=MP9_YXW9

![blinkid](https://cloud.githubusercontent.com/assets/83948/22291032/36c7814c-e2d2-11e6-92a9-6fc805b44c20.gif)

**Comment by mvayngrib** [comment]
@culoi ping :)

**Comment by culoi** [comment]
Hello @mvayngrib 

I tried with the same image using iPhone SE and barcode doesnt have to be centered. As matter of fact, it scans barcode almost istantly regardless position inside the frame. 

![nycscan](https://cloud.githubusercontent.com/assets/24894049/23299198/e204c07c-fa80-11e6-8cd7-f88f7db0f0ed.gif)


We just released 2.6.0 version. Can you please try it?

**Comment by culoi** [comment]
Sorry, closed it accidently

**Comment by mvayngrib** [comment]
@culoi thanks for getting back to me. I tried 2.6.0 but with the same results as before. I know iOS does its own QR/barcode detection, is that what you guys are using? If yes, then it's probably some issue with that, because just I tried using their raw QR/barcode detection capabilities with similar results.

**Comment by mvayngrib** [comment]
@culoi btw, see a module we developed for using BlinkID in react native, on both Android and iOS: https://github.com/tradle/react-native-blinkid  It doesn't even close to the whole scope of your SDK, but it makes it easy to try out BlinkID with just Javascript

**Comment by Cerovec** [comment]
Hi,
we are using our own PDF417 decoding library which works much better when high density barcodes are scanned.
The problem in your case is that the barcode is scanned from screen. And the [moire](https://en.wikipedia.org/wiki/Moiré_pattern) effect makes the scanning harder. Can you try scanning on real document? Or at least printed ones using a regular printer?
Will your users scan real documents or documents from screen

**Comment by mvayngrib** [comment]
@Cerovec actually, my last response was based on trying it out on my own physical driving license, but yes, the first one was from a screen.

Our users will be scanning physical documents

thanks for your help :)

**Comment by Cerovec** [comment]
No problem! If you issue is resolved, please consider closing it. :)

**Comment by mvayngrib** [comment]
@Cerovec well I still have trouble scanning the driving license unless the barcode is centered. Maybe I'm using the SDK in a suboptimal way. This is my code here (a React Native module): https://github.com/tradle/react-native-blinkid/blob/master/ios/RNBlinkID.m  I'd be happy to show you what I'm doing live if you like, my Skype id is luigimvm

**Comment by juraskrlec** [comment]
Hi @mvayngrib ,
we've created react native application and successfully integrated your wrapper. We've tested it and barcode doesn't have to be tested.  Please, use our latest BlinkID framework [v2.7.1](https://github.com/BlinkID/blinkid-ios/releases/tag/v2.7.1) and change your Podfile accordingly. In your `[RNBlinkID.m](https://github.com/tradle/react-native-blinkid/blob/master/ios/RNBlinkID.m)` remove [these code lines](url).
Let us know if everything is ok.

Jura

**Comment by mvayngrib** [comment]
@juraskrlec awesome, will test and let you know

**Comment by mvayngrib** [comment]
@juraskrlec sorry for the slow response, but I just tested it and it works well. Thanks!
