### ISSUE TITLE
Error: While Integrating your library both the way using cocoapods and without it

### ISSUE THREAD

**Issue by chintanViPrak** [BlinkID/blinkid-ios#60]
Showing Recent Issues

ld: warning: ignoring file ../../MicroBlink.framework/MicroBlink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): ../../MicroBlink.framework/MicroBlink
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PPEudlRecognizerResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPUsdlRecognizerResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPMyKadRecognizerResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPMrtdRecognizerResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPMyKadRecognizerSettings", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPEudlRecognizerSettings", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPRecognizerResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPUsdlRecognizerSettings", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPViewControllerFactory", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPMrtdRecognizerSettings", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPSettings", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPCameraCoordinator", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Cerovec** [comment]
Hi,
you should have git lfs installed (as in instructions [here](https://github.com/BlinkID/blinkid-ios#installation-with-cocoapods)).
Git lfs is required because our binary ../../MicroBlink.framework/MicroBlink is built with bitcode and has more than 100MB, which is the file size limit on github.
Can you install git lfs and try again?

**Comment by chintanViPrak** [comment]
Yes I have done that and tried all the solutions you mentioned in earlier issues. but still there is the same error. Other thing, I tried the sample code and it is working.

**Comment by nicoduj** [comment]
Hi,
Just in case, use terminal to install / update your pods, and not the new GUI of CocoaPods (it seems to fail using gitl lfs).

**Comment by chintanViPrak** [comment]
Hello there I've some questions:

1) If I'm using cocoapods for the installation than also I need to clone?

and if than....

2). I'm quite new to programming, and one thing you've mentioned in your document is after installing Git Large File Storage by running these commands: brew install git-lfs, git lfs install.. Clone this git repository. So how to do Clone?

**Comment by Cerovec** [comment]
1) No, the cocoapods handle the integration automatically. You only need to use command line tools - see here how to install: https://guides.cocoapods.org/using/getting-started.html
2) Instructions how to install without cocoapods, including how to clone the git repo, is provided in our wiki: https://github.com/BlinkID/blinkid-ios/wiki/Getting-started#integration-without-cocoapods
Cloning is done with git command in terminal `git clone git@github.com:BlinkID/blinkid-ios.git`

**Comment by Cerovec** [comment]
Please let us know if this helped you solve the issue. If it did, please consider closing it.

**Comment by charleshkang** [comment]
I've installed using Cocoapods and git lfs, but I'm getting linker errors as well on `  pod 'PPBlinkID', '~> 2.6.0’

**Comment by charleshkang** [comment]
@Cerovec I've installed using Cocoapods and git lfs, but I'm getting linker errors as well on `pod 'PPBlinkID', '~> 2.6.0’

**Comment by Cerovec** [comment]
Having a valid git lfs installation should definitely solve the problem. Let us know if this is still an issue for you.
Thanks,
Jurica.

**Comment by juraskrlec** [comment]
Closing as inactive
