### ISSUE TITLE
Autofocus

### ISSUE THREAD

**Issue by srdjanns** [BlinkID/blinkid-ios#62]
Does MicroBlink have ability to request the camera to refocus? If it does have, can you give an example of implementation? Thank you.

**Comment by Cerovec** [comment]
Hi,
the SDK actually automatically refocuses the camera, in two ways:
- by using continuous autofocus all the time
- by manually refocusing the camera every x seconds. X is defined in PPCameraSettings class, and you can set it, for example, by `settings.cameraSettings.autofocusInterval = 3.0f;`

Also, Microblink performs manual focus at point when the user taps the screen, and after that immediately switches back to continuous autofocus.

Also, you can set autofocus restruction, to either Near or Far. This allows you to specify how far from the document will the user hold the device. For example, `settings.cameraSettings.cameraAutofocusRestriction = PPCameraAutofocusRestrictionNear`

Alternatively, Microblink allows you to perform completely customized integration where you can control the camera (and focus), and just provide the video images to Microblink SDK for processing.

Can you briefly explain your use case when would you like to manually call refocus?

**Comment by srdjanns** [comment]
Hi,
Thanks for the reply.
Can you explain " Microblink performs manual focus at point when the user taps the screen, and after that immediately switches back to continuous autofocus." a little bit more detailed?

Is there a possibility to manually refocus to some exact point (i.e. CGPoint(20, 20))?

**Comment by Cerovec** [comment]
Hi,
do you have any news with this issue?

**Comment by Cerovec** [comment]
This means if the user taps on the point CGPoint(20,20), BlinkID SDK will focus the camera on that point. If it doesn't, BlinkID will use continuous autofocus to focus on the overall image.

**Comment by srdjanns** [comment]
Thanks for the answer, but what I need is to manually refocus to a certain point on screen, without touching the screen, but programmatically. I have a custom view controller above your camera view controller and I need to send point on screen which is touched and recognized on my custom VC to your camera VC. Is that possible?

**Comment by Cerovec** [comment]
Maybe I didn't explain enough, sorry :)

Scanning View Controller internally has a tap gesture recognizer which captures user's taps. If the user taps on a certain point on the screen, the camera will refocus on that point.

So if I understood you correctly, you basically just need the default behaviour :)

Just make sure you disable the user interaction on your custom VC.

If this doesn't work as expected, can you send us some sample source where we can check why it doesn't work?

**Comment by srdjanns** [comment]
Sorry, maybe it's my fault, I didn't explain it clearly :) 

My custom view controller doesn't inherit your PPOverlayViewController, and that same custom VC is overlapping your camera VC, hence when my VC registers the user's touch, how can I pass that touch point to your VC? Is there any method to pass CGPoint, just like there is a property to set the scanning area (@property (nonatomic) CGRect scanningRegion;)

P.S. I use your custom VC (which inherits PPOverlayViewController) and it is blank, because I need your camera without any elements, just clear screen.

**Comment by Cerovec** [comment]
> how can I pass that touch point to your VC

There is no API method for this, but should be done automatically in your use case :)

Is your custom VC transparent?
Can you share a screnshot of your UI?

Did you try disabling user interaction on your VC (`self.view.userInteractionEnabled = NO;`)?

**Comment by ssimidzija-execom** [comment]
Yes, my custom VC is transparent.

I tried  disabling user interaction on my custom VC and in that case your controller recognized the touch.
But then I have a problem because I don't have user interaction over any of the elements which my VC contains (i.e. I don't have ability to click on UIButton and stuff like that) and that is not an option for me.

**Comment by srdjanns** [comment]
Yes, my custom VC is transparent.

I tried disabling user interaction on my custom VC and in that case your controller recognized the touch.
But then I have a problem because I don't have user interaction over any of the elements which my VC contains (i.e. I don't have ability to click on UIButton and stuff like that) and that is not an option for me.

**Comment by Cerovec** [comment]
This seems like an easy fix :)
You can have one extra UIView instance, which is of the same size as the superview of your hierarchy, which has transparent background, and userInteractionEnabled set to NO. All other views (which support user interaction) can have it set to YES.

**Comment by srdjanns** [comment]
I need to disable user interaction on main view (self.view.userInteractionEnabled = NO;). I don't know how to make UIView which is the same dimension as main view, but not to be subview of main view.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
