### ISSUE TITLE
MyKad Recogniser Address and Long Full Name OCR is not working reliably

### ISSUE THREAD

**Issue by hollowaykeanho** [BlinkID/blinkid-ios#64]
Under the lab condition with evenly distributed lighting, the MyKad address OCR failed to extract the info correctly. We have verified that the problem comes from different devices. The rate of failing has reach to a point where we have to literally scrap the feature and request user to fill in on their own.

## Bug Evidences
For card with address on iPhone 6s:
![dan-IC](https://lh3.googleusercontent.com/5Xp8MKleHDsdz-LQvXJVOZESRoddr76P9hYa6buahrESdSviHT77bHYDXI03yAGiBPjbZcO7g70Hg62DkeQByAxtcjrviNw7hEAft97l87HnsuKJR_T3_CfH8EvBJh3GDy38A3-Do3OUqiy0MrooZ2YG-JpHQyNOfNsxfjEcMUQh5ND0naLK1TUxM5GEN4p7bjJmpUTVDbsQ7Xfn_oKe9inSqAZTxwQNm03vrxfo6fQ2CfqEmYyzwVvgfGM0Kw_UIPH7P7pVfW-WCa8bZsKPN4Yy537PYTg04YgJyHpZx_4yUKUdEjA1NIqq6eLJzgfnjzLggE9jZPAAMDleGylsGhcuxDPC63-zLMIRnRszUQXGbU3wTf1ex_RfvjtxBG9vqb0UvXt1OkV01WYwDApiZj0zmT3XhLwL8_E5OxLfKfW3pgesLTk-dYPtYS3mgMOK_ymP12_E05JQOlIBLlTA6v_cSM1ns4PbO82WSilLb004k8cyJlkJGNrntzTsnPmCKpadoVNBwoy_9FunVOLENv74xdyaEqn_cy7yXQkUIt9b5vAMohzTpAVJojxZvOGyINnYlW-faph1t0qYTycHD6oBVXm3WFSBau2d7WzKaep4DIS10AR-LccQ8SlCNCX_DLrxhXAemY9sTQ8XMdyoXFWOkp12SjRNPaUt0HBI_1Q=w1430-h1906-no)

<br/>
it failed to recognized, only give:

![out](https://lh3.googleusercontent.com/9-TBE3X0gvEpnWf4GpOwLJaS3PhlFLmRdvrpb_IW6Ext-MkK_v84_RhD5q-8bi3-Ld65HeGy_yt99CLQSfZ3xEKTxdcjKv38QAVIXFLQuuV4JtQyWTSOvOJ54RW3rmvwP2TjYDQTZqOBhVFPDx5gOAAETfi4lrm6HA99IHnd6k73oYj_0VfswxZIWhBX-uIfhkEKdYE-ambsImLJPmHw9zFTajutNt1D4L_TzT5lzF_I7MaX_B9QXDuzWT7Kd7OZ8mPl8mVGAigdZI0hC8xLkLz97_cpBO8wlwGoOYX9lGuCuKbvdjB8qTmb9864OD8t2a0ajMG7hSH2yXx6exIRtWyrsOf7sJC56CfI-OXaT5xpQw8HohQ3GFLbz5Gci3qXQQdhH_-GMhdDkFuX1MoM-j4yWCbXFzwcc2RO9lg3ek7WaDjAx6z5yu_Mld1wsxWnSDM-buTyD4X4RKj7o5FOwU7CWLwezlTIiErA4PAs4cxvC5wZWDFz0NJUJ6zoEooXO_BoG3WPZuwNWS6oxTweez3tjkqE0_x-jZvnh36r-JynZvVHnu05SzQv-MQcFR4-339yt_zkeimkRVS9kZd8LkS9HjKq1XEVWGP3Y6VtE-fsGkQMr--eHFwM70d7hLnXChRqbGQ7wxJXA773HWca3FaIH_POeODan8uUvfIzJJg=w750-h1334-no)

<br/>
and 

![out](https://lh3.googleusercontent.com/fUu0pAqmmSGfkDrBZcoBZWlu3uCh9ZKr2E4O6A_5LaE7F7BFTtirQMv744r3s_fJ05LolFHQhHQRAsO0CHft-qZHfauNbnF4dOPj4KJtkL_H7hPM9EiMDCHk3hxz-FPGBxI1Vib9LbYuBGURC_MxZ-GUKvtgA5yXUL-TZlk4Tuvr_FkeSz60cuP5HlVr92WzSithpwXqQejCKAd_-AfaCoNFVGe05PuyPilbdO3lAMC9ny-BSVIywVwt3wYOKZmvVAQ-ryJ99dc3FmaaPnZZww7Ys3h8qJsSSUDhfIUGCXMqUgKjkpFXH5XFtBhnnAd4LBZY9mJA5PsVKnd5h2PIzQvXAAQp0sZ23H2vHpYbxVmltFI0LVhf0-V-Umbq7MyDc2i56NXri8gTwUiA_WV4xP42G-PaY4wuTVE8EeFZQmge5JcKqOy8mFH2TN3nrzIMsM7fyTSIZwZqyoTsFe-gIMO5bAUrYKHW3JtqGZ4Vhg5z_RDIXJIPTAGAOmOdlaWgILe74tKBFGUkhn3vUymoPwH3LH-i7IsW-RByG9Ze-Dn38F9S7zbcjDDRxoI547tp5rV42ntM_0UduMvAqFeAhKITAnN-FGT6_RE7Bg-FG_JyEFJRdAdPUufeXT44jAkHzPaDFoO8J8yN37ZJxYx-oFA_9y7GewxmPVdS7I7KS4c=w719-h1280-no)

<br/>

### 2nd Case with different IC on iPhone 5s:

![ic-2](https://lh3.googleusercontent.com/FunoM7zf2uMAjlc8ugzes8SgnV4Fstm5-YmoKLLqfTuBCIXz1wTXyNteDf-uR2JzgFkNeAnKUl02NmUcrODLN2_H6gl6OwL39jsrxkogS9jrqm1qo8MxCX7Jo1g7doqiX-lgcqmvC3fVLownTpMj4ppgRQv51DvH-YU4mK-oiHZU2axgTp7CRUaHkpXUCQdb-sNS5WwPTuyNORQUoVDzxqX2mwblMt8ZYn-VoOTUzZhwtZsMDzShgWeIhWBHzooS3rxwapJj4ovdh6Pi-SwA_fcBoD8CIOMHI56V5iwOnM61zYhzLD1OBqgH-EoAG9OhUSbwqaKXCdAYK63cJcexKZz4vSoZN6DeyXtmuvjCMmg6bVLTcnc9ek7sDYBniJp7_6Liq5xxMpnBZkYW1iInvNizTwBbcZqyhXmuhRz6DjzJ3sg_0kB1z-_h-gj6pI7OG72wQWmhlfReY22b9ZLFfe1tU78B7NDHBX-pPajl9KA20s2rOCseDuZD5Hpv1BqVRVw6st0RIXIcetpZYCHMHj_joB2vBiENhx92wgg36VQHaQQkPQfrrqMAb4pX8zSYa16l6m-xB6D-MPAEDocXyIWt7MuMfllMlyIdqoehDo0KJd_r8CrP4lfSQY7QwSAIERZDauA-rgRTMrtXsnWc1k003dYqQgslzZ9V32EwYbo=w1024-h768-no)

<br/>
yields:

![scan03](https://lh3.googleusercontent.com/62Rcab-CfbT9LSHv-2lKGdJ-QOj0a8JS4bACVWqJVWvOEqTTTOnsiuYFU9192liXAucw2CByXEsHSFXD6N0_K7RYv0SJHxY8tmLXr2TMdvcpOhryhkojwCT04-9XWfws2sScFCE6Wqy6fUFi0gCh6iugr9UJ60naQxQZVef8dXVjMEW1BsLNXu6CWNq-FPKL2MqIhqGYwBOSu_JNbadOZpYHjg3b1CUf0lH3e5wZnyVMgSc9_XouN99nyZdREDBvXQm9CJNrwnuVar46yuxpD7ZSRtXmkc5gIS_4nkQSKpVE5o2lJrNsiep4gqDZF4HOU-6rpAEmZIksZvyTM9bhFpNAX7MdQt2n7Li3Xasq2rn8boaJmlUSZri_JoZWL7u_KCjdPjgOOoyx58akuyb0QBCwnyyViTIOPJJ9wpsNWYZa-f9KI6ApQjGSsPhgW4c5SPm_OuosOykI8FoSOA5xr1pid-C5CMxXlJ5tFekqHY_VbiOUkwx4E7g9__t1jUBWNp51VDc41rtqK5KhYyk8kRTRVdGHNYp0hNe0DvuHWHZQuThYJpony-JmnzANI_3Q1XONx8PGAGYlLZ6HWMSa67PapRr7WR83fSPKKIwHfr8TrDGTT59h0mC0s8RPyxrmXeTApBn-gGv9ChHEzUj9Jw97DKT6fc23tPzxZ_-aqpA=w640-h1136-no)

![scan04](https://lh3.googleusercontent.com/5dWBDHb4YsZNh1bkmA_ulHtWoY_-qbZCcA5MvoW5ffsXmUyiKuMd5P8PZn9XFmf8GEYSFXWeK5wXXfZV3nM4MzJqNwa-yyGoa2CnNdSK1isGbXznO2mUtH-5T5IJm240fc7eNesMPeLwVfP-OCSgbeE70efwy6n00Ftpc6D-Isk7Yo81aFvXUIzCKm6p7wJV6c_GXTOgLSoc57-SKMhvcUtNjtRtxt1zgJC0yLfsbaWnRabBAszg2RKQm0-OYC7lzrh6sB2VW6kgLqUeYzkQTAemurMX18XAhvb_magCcQ4cX6oBM3nrTlqh6_UPx0UFb1Yw3Jh189SpOTEDXKLN9eulT4bPL6jPZuHO-Rsw36uGW-xJOqUtMtWGpAo8mSJcj1DSZHiFJeCJiZ6OqsCfdHClRWqdIgkQilpK7-NDowE39ENBWwzhQyzZwU4FPJQREjDl8217b-cVF3Y0t5e-70rlYhQMoxTrUeQYwiNRYvvvwYXdwIn1LmtQo9wgDVyw7MCvezfV_mF1oa3zptfHeOzQu6ciT43CmF2bAquPssB-AserCTDD5jZTvlB0_VLV3mKtkBBsDUTpgPWBlYE4_23wXmjejO7YmP8QN2LB7LBld9xuP6M6u-rbxuk9Su32VYsW-0ni0lzGe9v92hwFjH9ZXK_85wOWosKG9Adw5C4=w640-h1136-no)

<br/>

## Test Environments and Constants
1. Test devices: iPhone 5S (iOS10), iPhone 6s
2. Lighting: evenly distributed
3. IC: 2 different ICs from respective owners
4. Other particles are working fine.

**Comment by culoi** [comment]
Hello @hollowaykeanho,

OCR of address can never be 100% correct. Maybe in future with machine learning process.
We are working on scan improvement with every release, but to speed up a process, we need more samples to have larger data to work with. More date processed = more accuracy in performing OCR. Very simple.

**Comment by hollowaykeanho** [comment]
Hello @culoi ,

I understand you need more sample to train the algorithm but this is not a simple document where we can forge or make up from. Perhaps contact the government [department](http://www.jpn.gov.my/en/) directly for sourcing some sample cards.

**Comment by Cerovec** [comment]
Hi,
please check if this happens in version v2.8.0, released a few moments ago.
We also added a feature which splits the address into parts: street, ZIP code, city and state.
Best,
Jurica.

**Comment by hollowaykeanho** [comment]
@culoi, you can source some scammer's identification cards (real card) through our local country forum Lowyat.net. Example: https://forum.lowyat.net/topic/3561373/all. 

**DISCLAIMER**: I'm not responsible for victims (scammer's IC) that are already made available over the internet nor held liable for any damages in any form caused by such circumstance. The link available here is purely a simple web search and the information is as IT IS. If any legal or authority and investigating parties reach here, please use the link and search for the Lowyat.net topic owner.

**Comment by hollowaykeanho** [comment]
@Cerovec, yes, the problem is still persisting. No observable changes with the existing test cases. For the priority of the UX, the application will ask the user to fill in the address manually instead of using the scanner.

**Comment by hollowaykeanho** [comment]
This issue expands to NRIC full name for Muslims citizen since their name is as long as an address (or longer).
