### ISSUE TITLE
small warning with XCode 8.3

### ISSUE THREAD

**Issue by nicoduj** [BlinkID/blinkid-ios#67]
Hi,

just updated to blinkID latest and get a small warning  while compiling, in case you didn't noticed ! : 
![blinkid_warning_xcode_8_1](https://cloud.githubusercontent.com/assets/19813688/24903785/bda94908-1eae-11e7-9905-b6b174443280.png)

**Comment by Cerovec** [comment]
Thanks for reporting this. This was introduced by Xcode update, because now Clang warns about errors in case in filenames.
We alreday fixed it internally - new release will have this fixed.
Best,
Jurica.

**Comment by Cerovec** [comment]
Please check if this happens in v2.8.0 (released a few moments ago).
If not, please close the issue.
Thanks,
Jurica.

**Comment by efpies** [comment]
Still happens in 2.8.0, and Xcode produces even more warnings.

<img width="702" alt="2017-05-30 14 56 14" src="https://cloud.githubusercontent.com/assets/1215572/26582048/2b2361c0-4548-11e7-8200-8a57ffb55e30.png">

Also 2.8.0 added a new warning

<module-includes>:1:1: Umbrella header for module 'MicroBlink' does not include header 'PPTapToFocusOverlaySubview.h'

**Comment by Cerovec** [comment]
Hi,

we didn't include actually a fix in 2.8.0 due to git case insensitivity. However, the problem should now be solved in [2.9.0](https://github.com/BlinkID/blinkid-ios/releases/tag/v2.9.0)

it also solved the issue with 'PPTapToFocusOverlaySubview.h'

If it does, please close the issue.

Best,
Jurica.

**Comment by Cerovec** [comment]
Closed as solved. If it still persists in new versions - @nicoduj, @efpies, please reopen the issue.
