### ISSUE TITLE
fails to scan Russian Passport

### ISSUE THREAD

**Issue by mvayngrib** [BlinkID/blinkid-ios#68]
issued 12.10.2015 (that's the date issued it says on the passport, not sure if that means October or December)

reproduced on several iphones. The mrz font is quite thin, is that the issue?

**Comment by Cerovec** [comment]
Hi,
That's hard to say without actually seeing the document and trying to reproduce it.
Would it be possible you send us an image of the document?
You can send it to support@microblink.com.
Best,
Jurica.

**Comment by mvayngrib** [comment]
@Cerovec i'll check with the owner and get back to you

**Comment by mvayngrib** [comment]
@Cerovec ok, sent
