### ISSUE TITLE
Embedding MicroBlink Frameworks into Another Framework

### ISSUE THREAD

**Issue by Jovial-Ionnex** [BlinkID/blinkid-ios#69]
Dear Developers,

I'm having trouble with Embedding MicroBlink Frameworks into our framework for a certain project actually. The Issues came from the fact that the Client App which implement our Framework was not able to detect the MicroBlink Frameworks. The error shows as the "Module MicroBlink not found.
Hence, I was wondering if there is other way to Embed the frameworks. In addition, I also have tried to add the Framework Search Path to point to MicroBlink Frameworks, but it was not working also.

Thanks in Advance.

**Comment by juraskrlec** [comment]
Hi @Jovial-Ionnex 
we have implemented sample for Dynamic Framework and embedding MicroBlink framework. It is located in the branch [feature/dynamic-lib](https://github.com/BlinkID/blinkid-ios/tree/feature/dynamic-lib). Dynamic lib project is located in [MicroBlinkDynamic sample](https://github.com/BlinkID/blinkid-ios/tree/feature/dynamic-lib/Samples/MicroBlinkDynamic). 
Let us know if everything works with your project. 

Jura

**Comment by Cerovec** [comment]
Hi @Jovial-Ionnex,
just as an addition. That project's goal was to wrap our regular static library into a dynamic one. Some users actually prefer having dynamic library instead of an static one.
This project is also an example how to wrap our framework into a dynamic one.
It's now merged into master branch.

Other options also exist.

If you're wrapping our framework into your static library - it's also possible. You just need to prelink our framework (In build settings, Use single object prelink, and add a path to microblink library in prelink_libs setting). 

Also, don't forget about resources. MicroBlink.bundle is a resource bundle which packages everything the library needs to function properly. That bundle should also be included in your framework.

Let us know if you need any other help with this.

**Comment by Jovial-Ionnex** [comment]
Dear All,

Noted with Thanks. I managed to Embed the framework into our framework. However, I actually have troubles with the Unit Testing of MicroBlink Library. The error shows as EXC_BAD_ACCESS on the creation of PPCoordinator actually as shown below.
```
func testInitiatePPCoordinator() {
        let error: NSErrorPointer = nil
        if PPCameraCoordinator.isScanningUnsupported(for: .back, error: error) {
            return
        }
        
        let settings: PPSettings = PPSettings(resourceBundle: Bundle(for: type(of: self)))
        settings.licenseSettings.licenseKey = "<My License Key>" // License Key Omitted for Confidential reason
        
        do {
            let recognizerSetting = PPMyKadRecognizerSettings()
            recognizerSetting.showFaceImage = true
            recognizerSetting.showFullDocument = true
            
            settings.scanSettings.add(recognizerSetting)
        }
        
        let coordinator = PPCameraCoordinator(settings: settings) // Debugger stops at here showing EXC_BAD_ACCESS
}
```

Hence, I was wondering if you could help me find what is the issue about. Additionally, I did try to implement the Framework with embedded Microaamework into a client as another way to test the framework. I end up having error on the MicroBlink Library. In this case, I first thought it was our framework issue. So I scrapped our framework and change it to MicroBlink Library only. However, the same problem also occurred as shown in the code and image below.

```
private func createBlinkIDSettings() -> PPCoordinator {
        let settings: PPSettings = PPSettings(resourceBundle: Bundle(identifier: "com.xendity.reader")!)
        settings.licenseSettings.licenseKey = "<My License Key>" // License Key Omitted for Confidential reason
        
        do {
            settings.scanSettings.add(initiateMyKadSettings())
            settings.scanSettings.add(initiateMRTDSettings())
        }
        
        return PPCoordinator(settings: settings, delegate: self)
    }
    
    private func initiateMyKadSettings() -> PPMyKadRecognizerSettings {
        let recognizerSetting = PPMyKadRecognizerSettings()
        recognizerSetting.showFaceImage = true
        recognizerSetting.showFullDocument = true
        return recognizerSetting
    }
    
    private func initiateMRTDSettings() -> PPMrtdRecognizerSettings {
        let recognizerSetting = PPMrtdRecognizerSettings()
        recognizerSetting.dewarpFullDocument = true
        return recognizerSetting
    }
    
    public func initiateBlinkIDProcess(image: UIImage) {
        let coordinator = createBlinkIDSettings()
        let queue = DispatchQueue(label: "com.queue.Serial", qos: .background)
        queue.async {
            coordinator.processImage(PPImage(uiImage: image))
        }
    }
```

![Uploading Screen Shot 2560-04-26 at 1.59.13 PM.png…]()

**Comment by Jovial-Ionnex** [comment]
Here is the screenshot.

![screenshot](https://cloud.githubusercontent.com/assets/27202375/25420323/334fcb3c-2a8a-11e7-9f04-dcdfddf1684e.png)

**Comment by juraskrlec** [comment]
Hi @Jovial-Ionnex 
you need to add new Target with package name under Targets settings (add Single View Application) and add it as a host for your unit test target. Package name is required for license key, that was your problem. 
![screen shot 2017-04-26 at 12 03 37](https://cloud.githubusercontent.com/assets/26868155/25429285/c08f1b0e-2a78-11e7-81da-e56e622e417b.png)

**Comment by Jovial-Ionnex** [comment]
Dear Sir Juraskrlec,

Noted with Thanks. Appreciate your help actually. I managed to get the Unit Test to work. However, I'm still having the same issue of ASSERTION FAILED as shown in the image of my previous post one. After some debugging, I found out it cannot find MicroBlink.bundle resources even though the bundle was there and has been setup in PPSettings(resourceBundle: Bundle(identifier: "com.xendity.reader")!) way.

However, if I put the MicroBlink.bundle in the Client Project and use the PPSettings() normally. It worked as normal. I also tried to actually check the Bundle path using .path(forResource:,ofType:) and found out that MicroBlink.bundle is there actually. Hence, I was wondering on why it cannot find the Bundle.

Thank you.

**Comment by juraskrlec** [comment]
Hi @Jovial-Ionnex 
this behaviour seems pretty strange, we will look into it. In the meantime, use 
`
PPSettings *settings = [[PPSettings alloc] initWithResourceBundle:[NSBundle mainBundle]];
`
for testing inside your framework.

Jura

**Comment by Jovial-Ionnex** [comment]
Dear juraskrlec,

After further debugging, I just found out that the it was caused by the PPSettings using Bundle.bundlepath instead of using Bundle.path(forResource:, ofType:).

My bad for assuming that way actually. Nevertheless, I already reflect my code to ensure the Bundle.bundlepath will direct to MicroBlink.bundle as shown below.

```
let path = Bundle(identifier: "com.xendity.reader")!.bundlePath + "/MicroBlink.bundle"
let bundle = Bundle(path: path)!
let settings: PPSettings = PPSettings(resourceBundle: bundle)
```        

Thanks again for the previous help. You may close this case.

Best Regards

Jovial
