### ISSUE TITLE
MicroBlink causes app to exit when Address Sanitizer is enabled

### ISSUE THREAD

**Issue by billinghamj** [BlinkID/blinkid-ios#7]
Xcode 7 has a new feature called Runtime Sanitization/Address Sanitizer. See here: https://developer.apple.com/library/prerelease/ios/documentation/DeveloperTools/Conceptual/WhatsNewXcode/Articles/xcode_7_0.html#//apple_ref/doc/uid/TP40015242-SW6

It's a tool which basically keeps track of your use of pointers and alerts you when you've done something wrong (e.g. releasing memory which is still in scope).

When it is enabled, immediately after MicroBlink is initialized, the app exits. It doesn't seem to be exiting with a non-zero exit code though as Xcode does not catch any exceptions or signals.

**Comment by Cerovec** [comment]
Hi,
thanks or reporting that.
We've just started testing the product using XCode 7, and we'll definitely look into that.
If you can provide any other information, it would be appreciated.
Thanks,
Jurica.

**Comment by Cerovec** [comment]
SDK Version 1.0.0 was just released. Can you please check if this problem still persists?

**Comment by billinghamj** [comment]
I'm having a play with this now. I know we were having problems using up-to-date SDKs though - we're currently stuck to an unknown version from some months ago to avoid whatever caused it to break.

Will try with the latest and see if I can get it working at all.

**Comment by billinghamj** [comment]
Okay so I'm on the latest SDK version. It's working fine with our app which is great. But I can confirm that it still crashes when address sanitizer is on.

**Comment by billinghamj** [comment]
Seems that it doesn't crash on iPad Air 2, but it does crash on iPhone 6 Plus.

**Comment by Cerovec** [comment]
We're using Xcode beta 4, iPhone 6 plus iOS 9 beta 4, and are not experiencing crashes, but connection losses to device. 
Are you referring to the same issue?

<img width="1440" alt="screen shot 2015-07-29 at 09 32 12" src="https://cloud.githubusercontent.com/assets/628039/8952412/02cd436c-35d7-11e5-9cdb-9736b6521662.png">

**Comment by billinghamj** [comment]
In our case, it is not a "crash" as such. The app simply exits and closes to the home screen. That message in Xcode doesn't seem to appear though.

**Comment by Cerovec** [comment]
At this moment, we can't be sure that this isn't an issue with beta versions of iOS and Xcode.
Can you use Instruments (Leaks and Allocations) for memory checking?

**Comment by billinghamj** [comment]
I've tried running the BlinkID-sample (rather than our own project). Can confirm I experience exactly the same behavior as you.

Will use instruments now.

**Comment by billinghamj** [comment]
Uploaded the session here: http://s000.tinyupload.com/index.php?file_id=05018421905736738712

**Comment by Cerovec** [comment]
The leaks have been reported in your app, can you confirm that the leaks also exist while using BlinkID-sample app when scanning the same ID document?
Thanks,
Jurica.

**Comment by billinghamj** [comment]
The issue occurs both in our app, and in the BlinkID-sample app. The session I uploaded above is from the BlinkID-sample app.

No ID document needs to be scanned for the issue to occur. Merely leaving the scanning controller open with no ID causes the crash within a few seconds.

**Comment by Cerovec** [comment]
For some reason, we cannot reproduce the crash.

With device setup I wrote above (Xcode7 / iOS 9 beta 4, iPhone 6 plus), instruments session is here:
https://jumbo.iskon.hr/download/90382d39-fc30-49d4-9384-7be8f7b380e3

Note: this contains two full scans of ID document, not just leaving the scanning controller open.
Note2: we're using BlinkID-sample app from the current HEAD in master branch.

**Comment by billinghamj** [comment]
The screenshot you showed above though ([this comment](https://github.com/BlinkID/blinkid-ios/issues/7#issuecomment-125872764)) is exactly what's happening for us. Isn't that happening to you also?

**Comment by Cerovec** [comment]
I get that.
Can you just explain how your Instruments trace relates to this issue?
In the trace there are memory leaks, so in response I attached trace we're getting - without leaks.
I'm trying to pin down memory related issue.

**Comment by Cerovec** [comment]
Hi,
does this issue still persist with Xcode 7.2?
Thank,
Jurica.

**Comment by billinghamj** [comment]
I'm afraid we're actually not using BlinkID any more, so I'm not able to test this - sorry.

Might be worth closing this issue for now, but referencing it in the future if the issue arises again.

**Comment by Cerovec** [comment]
If so - please close the issue.

Also, if you have some time, please let us know over short email
info@microblink.com why you decided not to use our product. We would
appreciate that information to figure out how to make the product better.

Thanks!

On Wed, Dec 16, 2015 at 1:09 PM, James Billingham <notifications@github.com>
wrote:

> I'm afraid we're actually not using BlinkID any more, so I'm not able to
> test this - sorry.
>
> Might be worth closing this issue for now, but referencing it in the
> future if the issue arises again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlinkID/blinkid-ios/issues/7#issuecomment-165087558>.
>



-- 
Jurica Cerovec, M.Sc.

mobile: +385 98 993 8076
skype: cerovec

http://photomath.net
http://microblink.com

**Comment by billinghamj** [comment]
It was primarily because the success rate on UK driving licenses was very low, and we didn't have the time or resources to collect enough good photos of licenses to help you properly train BlinkID.

**Comment by Cerovec** [comment]
You can try version 1.2.0, which now has improved UKDL scanning, based on samples we collected over the last couple of months.
We hope it helps and would appreciate the feedback.
Thanks!
