### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by kyramckenna** [BlinkID/blinkid-ios#71]
Hi, 
I am using Xcode 8.3.1 (latest) and I can't run any of the example apps due to Apple Mach-O Linker (Id) Errors.

<img width="1440" alt="screen shot 2017-05-02 at 13 50 03" src="https://cloud.githubusercontent.com/assets/4291402/25618292/4e899dde-2f3e-11e7-939c-e71cb97fe0be.png">

Could anyone check this please?

Kind Regards,
Kyra

**Comment by juraskrlec** [comment]
Hi @kyramckenna 
you need to install Git LFS
```
brew install git-lfs
git lfs install
```

**Be sure to restart your console after installing Git LFS**

After that, clone repo once again, everything will work. 

Best,
Jura

**Comment by juraskrlec** [comment]
Hi @kyramckenna 
did installing git-lfs helped you? If so, please close this issue :) 

Best, 
Jura

**Comment by Chrisrdavid7** [comment]
<img width="1280" alt="screen shot 2017-05-08 at 8 04 24 pm" src="https://cloud.githubusercontent.com/assets/12600704/25830248/92959fc4-3429-11e7-9028-d42189412b4a.png">

**Comment by Chrisrdavid7** [comment]
@juraskrlec m8...

**Comment by juraskrlec** [comment]
@Chrisrdavid7 This seems to be problem with Homebrew installing Go. Run `brew update` and `brew doctor`

**Comment by Chrisrdavid7** [comment]
Yea, i figured it out. I had to install brew all over again. Everything
works fine
