### ISSUE TITLE
Multiple settings or multiple template not supported - License key error

### ISSUE THREAD

**Issue by chonex143** [BlinkID/blinkid-ios#73]
Hi, I am using **OCRRecognizerSettings** and i need to scan `front` and `back` portion of the ID. So, i create two settings for this. One is for front and second is back. 

When i added only `front` it will scan.
But when i added the two settings which is `front` and `back` it will have error **License key error**

*here is the logs:*
`[E] updateRecognizers [MasterRecognizer.cpp:60] 2017-05-03 17:53:24.513742+0800 FlexM_Wallet[970:297612] Multiple settings objects of type 'Generic BlinkOCR recognizer' found. This is not supported!
[E] __38-[PPCoordinator initializeRecognizers]_block_invoke_2 [PPCoordinator.mm:314] 2017-05-03 17:53:24.513931+0800 FlexM_Wallet[970:297612] [net.photopay.frame.processing] Failed to initialize master recognizer
[E] __38-[PPCoordinator initializeRecognizers]_block_invoke_2 [PPCoordinator.mm:319] 2017-05-03 17:53:24.514698+0800 FlexM_Wallet[970:297612] License error message:`

**Comment by juraskrlec** [comment]
Hi @chonex143 
you cannot add same multiple recognisers to settings. 
You have two options: 

1. To implement your own `DecodingInfo` as seen [here](https://github.com/BlinkID/blinkid-ios/blob/feature/starbucks-template-sample/Samples/Templating-Sample/Templating-Sample/StarbucksCardRecognizerSettings.m)
2. To first scan front size with one recogniser, and on results, change recogniser for back and apply it to settings with `applySettings`

Best,
Jura

**Comment by chonex143** [comment]
Thanks. It help a lot!
