### ISSUE TITLE
PPSingaporeIDFrontRecognizerSettings and PPSingaporeIDBackRecognizerSettings not scanning

### ISSUE THREAD

**Issue by chonex143** [BlinkID/blinkid-ios#74]
Hi, i cannot scan Singapore ID. 

I just use the `PPSingaporeIDFrontRecognizerSettings` and `PPSingaporeIDBackRecognizerSettings` as my settings.

here the sample code:  
` let singaporeIDFront = PPSingaporeIDFrontRecognizerSettings()
   settings.scanSettings.add(singaporeIDFront)`

 see this sample image ID link: [here](https://i.ytimg.com/vi/EjUHMPL-LFg/maxresdefault.jpg)

**Comment by juraskrlec** [comment]
Hi @chonex143 
we've tried and we've successfully scanned your ID. Can you please tell us a little bit more about your problem?

Best, Jura

![img_0002](https://cloud.githubusercontent.com/assets/26868155/25752466/ad292d1a-31b8-11e7-8b04-036a8a553aca.PNG)

**Comment by chonex143** [comment]
Hi @juraskrlec,

Thank you for a fast respond. Can you show me your implementation? Because mine cannot delegate to output result. It just logging the scanned data. Maybe i missed some code. Thank you.

**Comment by juraskrlec** [comment]
Hi @chonex143 

in repository, there are samples and one of them is implementation of BlinkID in Swift. You can see [Swift implementation](https://github.com/BlinkID/blinkid-ios/blob/master/Samples/BlinkID-sample-Swift/BlinkID-sample-Swift/ViewController.swift).

Best,
Jura
