### ISSUE TITLE
Determine Legitimacy of ID Card

### ISSUE THREAD

**Issue by Jovial-Ionnex** [BlinkID/blinkid-ios#78]
Dear MicroBlink Developers,

I have noticed that the Scanning of ID Card can be falsified when one of our tester actually draw the ID Card manually using Handwriting. (Don't ask how, they just that good)

My concern is that if let us say that the user is scanning an ID Card, how does your Library Determine the legitimacy of the ID Card? Is there any method for it?

Thank you.

Best Regards,

Jovial

**Comment by Cerovec** [comment]
Hi,

BlinkID SDK is currently focused just on reading the IDs. You can read IDs with barcodes, with MRZ, and some of the IDs where the data is on the front/back side without any standard.
Currently the SDK doesn't deal with Legitimacy check other than verifying check digits on MRZ. This is an interesting topic for our future development. 

Jurica.

**Comment by imizaac** [comment]
An interesting hack in this area might be to compare the displayed value of the ID number to the barcode value of the ID number. If a person does not know what they are doing, these two might present a discrepancy. It wouldn't work for competent counterfeiters, but would be a good first step. 

As far as verifying check digits, this would be an easy enough thing to build within your own project if you were so inclined. It may be prone to error if the OCR misreads values, so you might be best to use the barcodes for consistency.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
