### ISSUE TITLE
Can I use Detector-sample only?

### ISSUE THREAD

**Issue by smartsanja** [BlinkID/blinkid-ios#79]
I want to use the image auto crop module of the blinkID ios sdk. (Detector-sample). Do I need to purchase the full sdk for that?

**Comment by cularj** [comment]
Please contact sales@microblink.com
Technically, you can definitely use just the detector feature.

Regards,
Jure

**Comment by Cerovec** [comment]
If your issue was resolved, please consider closing this issue.
Thanks!

**Comment by Cerovec** [comment]
Closing as inactive.
