### ISSUE TITLE
[request] use resource bundles

### ISSUE THREAD

**Issue by billinghamj** [BlinkID/blinkid-ios#8]
If you bundle MicroBlink's resources into a bundle, it effectively 'namespaces' them and prevents them from overlapping with the app's own resources.

Right now, if the app has a resource called IDCard.png (for example), MicroBlink's own asset ends up interfering with it, and inconsistently your app will end up with one or the other resource.

How it can be done: http://www.mokacoding.com/blog/sharing-assets-with-cocoapods-resource-bundle-and-dynamically-loaded-fonts/

Maybe not something to do with much urgency, but similarly to cocoapods, it's worth thinking about doing at some point.

**Comment by Cerovec** [comment]
Great suggestion!
We're already using bundles for resources in other projects and are planning to go in that directions in BlinkID.
In the meantime, the quickest fix is to add PP as namespace to existing resources.

**Comment by Cerovec** [comment]
Hi,
this is implemented in v1.3.0. Please check it out and close if it the idea is completed.

**Comment by Cerovec** [comment]
Closing as solved and inactive.
