### ISSUE TITLE
Problem importing headers in PPBlinkIDRecognizers

### ISSUE THREAD

**Issue by matijabogdanovic** [BlinkID/blinkid-ios#82]
There is an inconsistency in header file names and import statements in `PPBlinkIDRecognizers`. This causes import errors on a case sensitive file system.
i.e. the file name is `PPGermanIdFrontRecognizerSettings.h` and the import statement uses: `PPGermanIDFrontRecognizerSettings.h`

**Comment by DoDoENT** [comment]
Hi @matijabogdanovic!

Which version are you using? After [latest release](https://github.com/BlinkID/blinkid-ios/releases/tag/v2.8.0), there is a [commit](https://github.com/BlinkID/blinkid-ios/commit/98bd34656eeaf562dd8e246525ca016082d48933) to master branch that should fix that issue.

**Comment by matijabogdanovic** [comment]
Both stable releases (2.7.0, and 2.8.0), installed via pods, have had issues. 

Keep on the good work.
