### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by itsrawand199** [BlinkID/blinkid-ios#83]
Help me! i did exactly as the docs 

![screenshot at may 29 23-17-40](https://cloud.githubusercontent.com/assets/22601834/26561195/0d42384e-44c5-11e7-9d5e-3d5a57821e95.png)

**Comment by juraskrlec** [comment]
Hi @itsrawand199 
can you please send me your output when you type `git lfs` in your terminal?

Jura

**Comment by itsrawand199** [comment]
![screenshot at may 30 18-35-01](https://cloud.githubusercontent.com/assets/22601834/26591557/b74029f4-4566-11e7-97b6-80d4550ed3e1.png)
here it says this on the terminal

the question is, i dont know how to clone a repository

**Comment by juraskrlec** [comment]
Go to [Blink ID repository](https://github.com/BlinkID/blinkid-ios) and you will have on the right side button with text **Clone or download**. Press it and copy URL like on the picture
<img width="479" alt="screen shot 2017-05-31 at 10 32 27" src="https://cloud.githubusercontent.com/assets/26868155/26623072/c8e56864-45ec-11e7-866a-42747457b29e.png">
After that, go to your wanted folder in terminal and write `git clone https://github.com/BlinkID/blinkid-ios.git`

**Comment by dtomicAZ** [comment]
Hi,

I have this problem too, I installed Git LFS, cloned repository, then opened BlinkID-sample-Swift, and cannot run app because of this issue, I am using Xcode 8.3.3.

Can you check that? Thank you.

**Comment by juraskrlec** [comment]
Hi @dtomicAZ 
you will need to clone new repo after you have installed Git Bfs. Or you can go to your local cloned repo and execute `git lfs pull`

**Comment by dtomicAZ** [comment]
@juraskrlec Thanks, git lfs pull did help.

Currently I added blinkid manually, because blinkid cocoapods still won't work.

I tried this:
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update

then pod install and again I see Apple Mach-O Linker Error.

I tried create new project, then install blinkid using cocoapods, but still I get error.

Any help with this ?

**Comment by juraskrlec** [comment]
@dtomicAZ 
Are you using Swift or Objective C? If you are using Swift, you need to uncomment `# use_frameworks!`
After you have installed pod, you **need** to open `.xcworkspace` file, not `.xcodeproj`.
When you install pod file, under Pods folder there needs to be PPBlinkID folder
![screen shot 2017-06-14 at 17 51 53](https://user-images.githubusercontent.com/26868155/27142039-3123a5c4-512a-11e7-8b0a-7182e7ab2654.png)

**Comment by Cerovec** [comment]
@dtomicAZ,

do you still have issues with compiling the project?

**Comment by dtomicAZ** [comment]
It's ok now, I had to completely uninstall pod:

gem list --local | grep cocoapods
uninstall all from the list:

gem uninstall cocoapods
gem uninstall cocoapods-core
gem uninstall cocoapods-downloader
...

then install it again:
sudo gem install cocoapods

remove the cache:
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update

and then finally pod install again in procjet.

**Comment by Cerovec** [comment]
Interesting.

Thanks for sharing that.

@itsrawand199 - any update on your end? Did you manage to link with BlinkID SDK using the instructions above?

**Comment by juraskrlec** [comment]
Closed as inactive
