### ISSUE TITLE
not gives the result properly

### ISSUE THREAD

**Issue by itsrawand199** [BlinkID/blinkid-ios#85]
downloaded the sample project to see how it works,, i got a paper on my hand with BL2-205 written on,
but when i tap start scanning, it gives me this on the output which is wrong it has */*#^$@2 these
![screenshot at jun 01 06-58-36](https://cloud.githubusercontent.com/assets/22601834/26664144/026871de-4698-11e7-9b8a-b5d47425dc06.png)

**Comment by juraskrlec** [comment]
Can you please give us the example?

**Comment by itsrawand199** [comment]
here is the code @juraskrlec `- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    
    if (self.priceParserId!= nil) {
        self.labelResult.text = [NSString stringWithFormat:@"Price parsed out of the OCR result is: %@", self.priceParserId];
    } else {
        self.labelResult.text = nil;
    }
}
/**
 * Method allocates and initializes the Scanning coordinator object.
 * Coordinator is initialized with settings for scanning
 *
 *  @param error Error object, if scanning isn't supported
 *
 *  @return initialized coordinator
 */
- (PPCameraCoordinator *)coordinatorWithError:(NSError **)error {
    
    /** 0. Check if scanning is supported */
    
    if ([PPCameraCoordinator isScanningUnsupportedForCameraType:PPCameraTypeBack error:error]) {
        return nil;
    }
    
    
    /** 1. Initialize the Scanning settings */
    
    // Initialize the scanner settings object. This initialize settings with all default values.
    PPSettings *settings = [[PPSettings alloc] init];
    
    
    /** 2. Setup the license key */
    
    // Visit www.microblink.com to get the license key for your app
    settings.licenseSettings.licenseKey = @"SB7VUQXV-I2Y4HPHY-Z66RL5BM-KF647IE7-DAZFRNSU-DJDLG7CG-WN6EME6A-SOCH5JXO";
    // this license key is valid temporarily until 2017-08-03
    
    
    /**
     * 3. Set up what is being scanned. See detailed guides for specific use cases.
     * Here's an example for initializing raw OCR scanning.
     */
    
    // To specify we want to perform OCR recognition, initialize the OCR recognizer settings
    PPBlinkOcrRecognizerSettings *ocrRecognizerSettings = [[PPBlinkOcrRecognizerSettings alloc] init];
    
    
    // We want raw OCR parsing
    [ocrRecognizerSettings addOcrParser:[[PPRawOcrParserFactory alloc] init] name:self.rawOcrParserId];
    
    PPPriceOcrParserFactory *priceParser = [[PPPriceOcrParserFactory alloc] init];
    
    // Price doesn't need to be present for output to be valid
    priceParser.isRequired = NO;
    
    // We want to parse prices from raw OCR result as well
    [ocrRecognizerSettings addOcrParser:priceParser name:self.priceParserId];
    
    // Add the recognizer setting to a list of used recognizer
    [settings.scanSettings addRecognizerSettings:ocrRecognizerSettings];
    
    
    /** 4. Initialize the Scanning Coordinator object */
    PPCameraCoordinator *coordinator = [[PPCameraCoordinator alloc] initWithSettings:settings delegate:nil];
    
    return coordinator;
}


#pragma mark - PPScanDelegate

- (void)scanningViewControllerUnauthorizedCamera:(UIViewController<PPScanningViewController> *)scanningViewController {
    // Add any logic which handles UI when app user doesn't allow usage of the phone's camera
}

- (void)scanningViewController:(UIViewController<PPScanningViewController> *)scanningViewController didFindError:(NSError *)error {
    // Can be ignored. See description of the method
}

- (void)scanningViewControllerDidClose:(UIViewController<PPScanningViewController> *)scanningViewController {
    
    // As scanning view controller is presented full screen and modally, dismiss it
    [self dismissViewControllerAnimated:YES completion:nil];
}

- (void)scanningViewController:(UIViewController<PPScanningViewController> *)scanningViewController didOutputResults:(NSArray *)results {
    
    // Here you process scanning results. Scanning results are given in the array of PPRecognizerResult objects.
    NSLog(@"%@",results);
    // first, pause scanning until we process all the results
    [scanningViewController pauseScanning];
    
    // Collect data from the result
    for (PPRecognizerResult *result in results) {
        
        if ([result isKindOfClass:[PPBlinkOcrRecognizerResult class]]) {
            PPBlinkOcrRecognizerResult *ocrRecognizerResult = (PPBlinkOcrRecognizerResult *)result;
            
            NSLog(@"OCR results are:");
            NSLog(@"Raw ocr: %@", [ocrRecognizerResult parsedResultForName:self.rawOcrParserId]);
            self.labelResult.text = self.rawOcrParserId;
            self.labelResult.text = [ocrRecognizerResult parsedResultForName:self.rawOcrParserId];
            //self.labelResult.text = results[0];
            
            NSString *price = [ocrRecognizerResult parsedResultForName:self.priceParserId];
            NSLog(@"Price: %@", price);
            if (price != nil && price.length > 0) {
                self.priceParserId = price;
            }
            
            PPOcrLayout *ocrLayout = [ocrRecognizerResult ocrLayout];
            NSLog(@"Dimensions of ocrLayout are %@", NSStringFromCGRect([ocrLayout box]));
        }
    };
    scanningViewController.editButtonItem.title  = @"ته‌واو";
    [scanningViewController playScanSuccesSound];
    
    // resume scanning while preserving internal recognizer state
    [scanningViewController resumeScanningAndResetState:NO];
}

// dismiss the scanning view controller when user presses OK.
- (void)alertView:(UIAlertView *)alertView clickedButtonAtIndex:(NSInteger)buttonIndex {
    [self dismissViewControllerAnimated:YES completion:nil];
}`

**Comment by Cerovec** [comment]
Hi,
what exactly are you trying to scan?

If it's just BL2-205 - why are you using PPPriceOcrParserFactory, which is intended for scanning prices?

Also, if the data you're scanning is just small, you should try to implement custom UI which has a smaller scanning area, to avoid any OCR noise from the background of the text.

If you can send us the document you're trying to scan, that might help us understand what would be the best approach for scanning for your use case.

Best,
Jurica.

**Comment by Cerovec** [comment]
Hi @itsrawand199,

please provide an update for this issue.

Jurica.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
