### ISSUE TITLE
Need To capture full document image.

### ISSUE THREAD

**Issue by manomuthu-optisol** [BlinkID/blinkid-ios#86]
Hi,

In my application i need to capture the full image which we are scanning in side the frame. But in output am getting only the scanned mrtd code position. 

If the document was not readable also i need to capture the image. In android i have noticed that there is method called image listener does in iOS we have any of those. If there please share the sample code.

Thanks in advance

Regards,
Muthukumar

**Comment by cularj** [comment]
Hi,

to capture full document image you have to add PPMetadataSettings to your instance of PPSettings with dewarped property set to YES and in PPMrtdDetectorSettings instance set detectFullDocument property to YES like the example below:

```
PPMetadataSettings *metadataSettings = [[PPMetadataSettings alloc] init];
metadataSettings.dewarped = YES;
settings.metadataSettings = metadataSettings;

PPMrtdDetectorSettings *mrtdDetectorSettings= [[PPMrtdDetectorSettings allco]] init;
mrtdDetectorSettings.detectFullDocument = YES;
```
You will also need to implement scanningViewControllerDidOutputMetadata method in your PPScanningDelegate like this:
```
- (void)scanningViewController:(UIViewController<PPScanningViewController> *)scanningViewController didOutputMetadata:(PPMetadata *)metadata {
     if ([metadata isKindOfClass:[PPImageMetadata class]]) {
        PPImageMetadata *imageMeta = (PPImageMetadata *)metadata;
        UIImage *image = imageMeta.image; // captured image
}

```

Regards,
Jure.

**Comment by manomuthu-optisol** [comment]
Hi Jure,

Thanks for your immediate reply. The code which you have given was working fine in positive scenario. I need to capture image if user doesn't got the scanning result. In my application i will allow the user to scan for 25 sec if he doesn't detect any value i need to  capture the image. And need to display it in application. 

Regards,

Muthukumar

**Comment by cularj** [comment]
In that case you can set the property currentFrame to YES in PPMetadataSettings instance, which means that you will get processed video frame in scanningViewControllerDidOutputMetadata method. This means that you will get every processed video frame in that method, but since you only need the frame after 25 seconds, you can add a property that is set to NO and using a timer set it after 25 seconds to YES. Then in scanningViewControllerDidOutputMetadata implement something like this:
```
- (void)scanningViewController:(UIViewController<PPScanningViewController> *)scanningViewController didOutputMetadata:(nonnull PPMetadata *)metadata {
    if ([metadata isKindOfClass:[PPImageMetadata class]]) {
        PPImageMetadata *imageMetadata = (PPImageMetadata *) metadata;

        if (imageMetadata.imageType == PPImageMetadataTypeCurrentFrame && self.timeout) {
            UIImage *image = imageMetadata.image; 
        }
    }
}
```
Where self.timeout is property that is set to YES after 25 seconds using a timer.

Regards,
Jure.

**Comment by manomuthu-optisol** [comment]
Thanks for your response will try this and revert back soon.

**Comment by Cerovec** [comment]
Hi @manomuthu-optisol,

do you have an update for this issue?

Thanks!

**Comment by manomuthu-optisol** [comment]
Hi,
Yes , I have used PPDocumentSpecification to detect the document and capture its instance.

**Comment by Cerovec** [comment]
Excellent!

Do you get good results?
Is there something else we can do to help?

**Comment by manomuthu-optisol** [comment]
Yes i have got the result. Thanks for your help guys :)
