### ISSUE TITLE
Settings for camera frame

### ISSUE THREAD

**Issue by chonex143** [BlinkID/blinkid-ios#87]
How to setup camera frame settings? I got problem in iPhone 5 and SE. 

P.S Our design is fix and it will not be change.

<img width="653" alt="screen shot 2017-06-01 at 6 18 57 pm" src="https://cloud.githubusercontent.com/assets/25475522/26675593/18569e30-46f7-11e7-8c2f-240d5fa02870.png">

**Comment by juraskrlec** [comment]
Hi @chonex143 
this is the same issue as this [one](https://github.com/BlinkID/blinkid-ios/issues/80). Did you implement custom UI?

**Comment by chonex143** [comment]
@juraskrlec  yes. I have custom UI. I close that issue because i though my client is ok with the default UI.

**Comment by chonex143** [comment]
sadly, he want to pursue the custom UI.

**Comment by Cerovec** [comment]
Is there something we can do to help you?

Custom UI documentation is here: https://github.com/BlinkID/blinkid-ios/wiki/Customizing-Camera-UI

**Comment by chonex143** [comment]
@Cerovec is there any setting for the camera frame? I need to make it bigger for iPhone 5 and SE.

**Comment by juraskrlec** [comment]
Yo will need to create custom overlay controller with your custom camera frame,

**Comment by Cerovec** [comment]
Hi @chonex143,

please provide an update for this issue. Were you successful in creating the custom UI?
