### ISSUE TITLE
Using the scan controller in a navigation bar

### ISSUE THREAD

**Issue by yaakovgamliel** [BlinkID/blinkid-ios#88]
My app requires that the scanner controller runs inside a navigation controller, the issue is that the camera controller makes it self root controller for my window, any suggestions

**Comment by juraskrlec** [comment]
Hi @yaakovgamliel 
can you please tell me how are you showing your view controller: `pushViewController ` or `presentViewController `. If you are using navigation view controller, you need to use `pushViewController `

**Comment by Cerovec** [comment]
HI @yaakovgamliel,

did the advice help?

Please provide some feedback so that we know the status of this issue.

**Comment by yaakovgamliel** [comment]
this week I should be back to the task, I'll post a more detailed scenario then

**Comment by Cerovec** [comment]
OK, looking forward.
Any sample code, screenshots, or anything that would help us in understanding what you want to accomplish would be more than useful.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
