### ISSUE TITLE
Duplicate symbol _unionRect

### ISSUE THREAD

**Issue by nazarTrynko** [BlinkID/blinkid-ios#89]
duplicate symbol _unionRect in:

/Users/Mac/Library/Developer/Xcode/DerivedData/MyProject-fldkvfcujzcdxofogmdndkirdkst/Build/Intermediates/MyProject.build/Debug-iphonesimulator/MyProject.build/Objects-normal/x86_64/AIRGoogleMapMarker.o
/Users/Mac/Documents/MyProject/ios/Pods/PPBlinkID/MicroBlink.framework/MicroBlink(MicroBlink-x86_64-master.o)
ld: 1 duplicate symbol for architecture x86_64

Have some conflict with GoogleMaps, can't resolve

**Comment by Cerovec** [comment]
Hi @nazarTrynko,

thanks for reporting this. Since you closed the issue in the meantime, is this something we need to look into?

Thanks,
Jurica.

**Comment by nazarTrynko** [comment]
Hi @Cerovec! No, it was resolved by updating to the last version of BlinkId
