### ISSUE TITLE
Unable to scan ids on certain devices

### ISSUE THREAD

**Issue by jasontwong** [BlinkID/blinkid-ios#93]
I'm running the v2.9.0 SDK and I'm unable to get the USDL barcode scanning to work on iPad Pro 12.9in and iPad 4. I've successfully scanned using an iPad Air 2, iPhone 6, iPhone 7, and iPhone 5. This is using the sample app `Blink-sample` from CocoaPods.

**Comment by cularj** [comment]
Hi @jasontwong,

have you tried setting camera closer to the USDL? I tried it on iPad 4 and have successfully scanned the USDL barcode, it seems that the frame used to help position the card on the screen is too small for iPad 4. Please let us know if this helps.

**Comment by imizaac** [comment]
Hey Jason.

If you're still struggle you might find answers by playing with the scale and tolerance settings. I've found that can help make things scan. Hope that helps.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
