### ISSUE TITLE
Configurations for PPMyKadRecognizerSettings

### ISSUE THREAD

**Issue by Jovial-Ionnex** [BlinkID/blinkid-ios#96]
Dear MicroBlink Developers,

One of our testers actually complained that the Scanning for MyKad was ridiculously fast, in which they did not have time to adjust the camera to get the right angle for the MyKad scanning as attached in the zipped video below. 

[VID_20170721_182107.mp4.zip](https://github.com/BlinkID/blinkid-ios/files/1165209/VID_20170721_182107.mp4.zip)

Hence, the scanning result itself become inaccurate. In this case, as the pre-defined MyKad settings is limited only to 2 configuration. I was wondering if I could also configure it's Number of Stable Detection Threshold? (While I can create custom settings for it, I would preferred if I could just used your existing pre-defined settings.)

Additionally, is there any way to provide delay for the scanning, in which to allow the User to adjust their camera for scanning?

Thank you.

Best Regards,

Jovial

**Comment by Pickles112358** [comment]
Hi @Jovial-Ionnex

I know this issue happened a while ago but we have made some changes to our SDK to improve scanning performance. If you would still like to implement something like Number of Stable Detections Threshold you can wait for several outputs from scanningViewController:didOutputResults before presenting them to the user.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
