### ISSUE TITLE
Not returning PPMetadata using Template

### ISSUE THREAD

**Issue by chonex143** [BlinkID/blinkid-ios#98]
I am using my own template settings to scan my ID's. The id's data are scanned but it cannot return  PPMetadata in delegate.

**Comment by chonex143** [comment]
This are is detectors:

        //Add Specifications
        let idSpec = PPDocumentSpecification.new(from: PPDocumentPreset.id1Card)
        idSpec.setDecodingInfo(newFrontIdDecodingInfoArray)
        
        //Add Detectors
        let detectorSettings = PPDocumentDetectorSettings(numStableDetectionsThreshold: 1)
        detectorSettings.setDocumentSpecifications([idSpec])

**Comment by cularj** [comment]
Hi @chonex143 ,

what data are you trying to extract from PPMetadata? 
When creating PPSettings you need to set properties that you want to extract from PPMetadata in delegate. In PPSettings there is a property metadataSettings, in it you can set what you want to be returned to delegate.

Kind regards,
Jure

**Comment by chonex143** [comment]
Hi @cularj ,

I need only the image of the scanned ID.

**Comment by cularj** [comment]
When creating PPSettings, you can set successfulFrame to true or currentFrame to true to get images.
successfulFrame returns image that returned a valid scanning result, currentFrame returns the currently captured image. You should have something like this when setting PPSettings

```
 let settings: PPSettings = PPSettings()
 settings.metadataSettings.successfulFrame = true; // or currentFrame
```
and in delegate something like this:

```
func scanningViewController(_ scanningViewController: UIViewController?, didOutputMetadata metadata: PPMetadata) {
        if (metadata is PPImageMetadata) {
            let result: PPImageMetadata = metadata as! PPImageMetadata
            let image: UIImage = result.image()
    }
}
```

Kind regards,
Jure

**Comment by chonex143** [comment]
@cularj I already added this to my settings. I also try scanned using `PPSingaporeIDFrontRecognizerSettings` settings and it will give me `PPMetadata` results.

But when i switch to my Template settings it cannot give me `PPMetadata` results.

**Comment by cularj** [comment]
So ID is successfully scanned using you template settings but no metadata is returned? What version of SDK are you using?

**Comment by chonex143** [comment]
@cularj I am using old version `pod 'PPBlinkID', '~> 2.8.0`.

**Comment by chonex143** [comment]
I found the bug. 

The `PPMetadata delegate` will not trigger because i only added one (1) `PPDecodingInfo`. But when i added some scanned items in `PPDecodingInfo` it will trigger the `PPMetadata Delegate`. and i don't know why?

**Comment by cularj** [comment]
Do you mean when adding another PPDecodingInfo to PPDocumentSpecificationInfo?

**Comment by chonex143** [comment]
Yes @cularj .

**Comment by DoDoENT** [comment]
Hi @chonex143!

Are you using [Detector recognizer](http://cocoadocs.org/docsets/PPBlinkID/2.11.0/Classes/PPDetectorSettings.html) (which can only return images, but cannot perform OCR), or [BlinkOcr recognizer with added detector](http://cocoadocs.org/docsets/PPBlinkID/2.11.0/Classes/PPBlinkOcrRecognizerSettings.html) (which can also perform OCR and parsing on detected segments)?

In case of Detector recognizer, the images returned to Metadata will be only those as specified with PPDecodingInfo.

On the other hand, in case of BlinkOcr recognizer, if you create a decoding info and have at least one parser in parser group of equivalent name, then you will not get the image represented by this decoding info, unless you also enable [receiving of debug dewarped images](http://cocoadocs.org/docsets/PPBlinkID/2.11.0/Classes/PPDebugMetadata.html#//api/name/debugDewarpedElements) in [debug metadata](http://cocoadocs.org/docsets/PPBlinkID/2.11.0/Classes/PPMetadataSettings.html#//api/name/debugMetadata). However, if there is no existing parser group with same name as your Decoding Info, then the image represented by the Info will be sent to `PPMetadata Delegate` as [dewarped image](http://cocoadocs.org/docsets/PPBlinkID/2.11.0/Classes/PPMetadataSettings.html#//api/name/dewarpedImage) (i.e. it will behave exactly the same as [Detector recognizer](http://cocoadocs.org/docsets/PPBlinkID/2.11.0/Classes/PPDetectorSettings.html)).

**Comment by chonex143** [comment]
Ahh i see. 

Ok, Thank you for a fast reply @cularj and @DoDoENT .

**Comment by chonex143** [comment]
Close issue. It is done.
