### ISSUE TITLE
Setting dewarpedImage to YES doesn't call didOutputMetadata

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [BlinkID/blinkid-ios#99]
In the Templating-Sample app, it sets `settings.metadataSettings.dewarpedImage = YES;` but never does call `scanningViewController:didOutputMetadata:`. If I set `settings.metadataSettings.debugMetadata.debugDewarpedElements = YES;` then it does call that method. But it doesn't seem to be working for the non-debug images.

**Comment by DoDoENT** [comment]
Do you have at least one parser added to the parser group that has the same name as the decoding info for which you obtain the image? If yes, then only debug dewarped image will be sent. If no, then only non-debug dewarped image will be sent.

**Comment by jordanhbuiltbyhq** [comment]
In the sample code, which I haven't modified, I can see that it uses ID_FIRST_NAME for the group id and the decoding info unique id. What needs to be done then to get the non-debug dewarped image?

**Comment by DoDoENT** [comment]
If you want non-debug images, then you must restrain from creating a parser group of the same name as decoding info. The OCR will then not be performed on that image and it will be returned as non-debug image.

**Comment by jordanhbuiltbyhq** [comment]
Okay thanks. I am interested in performing the OCR and also seeing the non-debug image. I intend to use this to ultimately detect the document being scanned to get the dewarped image of the document itself, in addition to pulling out the text on the document, simultaneously.

**Comment by DoDoENT** [comment]
When OCR is performed, the image that is being OCRed is returned as debug dewarped image. If no OCR is performed on the image, then image is returned as non-debug dewarped image. If you need to both perform OCR and obtain the image, you should stick with obtaining the debug dewarped image (it has the same overhead as returning non-debug dewarped image) - this is much more efficient than creating two decoding infos of same size and location with sole purpose of obtaining the non-debug image (image dewarp is performed for each decoding info separately - the SDK will not figure out that there are multiple same decoding infos and return only a single image from them).

**Comment by jordanhbuiltbyhq** [comment]
Okay perhaps the Templating-Sample project should be updated to enable the debug dewarped elements instead of non-debug, since it doesn't do any non-debug when performing the OCR which the sample does, so `settings.metadataSettings.dewarpedImage = YES;` does nothing in this sample.

**Comment by Pickles112358** [comment]
Hi @jordanhbuiltbyhq 

We are following up to see if you have solved this problem. Just as a heads up, we are preparing a major release of the SDK (probably within 2 months) where these small inconsistencies within the API will be fixed and simplified.

**Comment by jordanhbuiltbyhq** [comment]
Yes this report can be closed.
